import { randomUUID } from 'node:crypto';
const domains=['appearance','locale','network','grid','privacy','appPermissions'];
const validators={appearance:v=>v&&['system','light','dark'].includes(v.mode),locale:v=>v&&typeof v.language==='string'&&(!v.region||typeof v.region==='string') ,network:v=>v&&['system','manual','off'].includes(v.proxyMode??'system')&&(!v.proxyUrl||/^https?:\/\//.test(v.proxyUrl))&&(!('proxySecret' in v)),grid:v=>v&&typeof v.enabled==='boolean',privacy:v=>v&&typeof v.telemetry==='boolean',appPermissions:v=>v&&typeof v==='object'};
const redact=(settings)=>{const value=structuredClone(settings);if(value.network){delete value.network.proxySecret;delete value.network.token;value.network.proxySecretRef=value.network.proxySecretRef??null;}return value;};
export class SystemService {
  constructor({audit,repository,scopeId='00000000-0000-0000-0000-000000000001'}={}) { this.audit=audit;this.repository=repository;this.scopeId=scopeId;this.version=1;this.contextVersion=1;this.settings={appearance:{mode:'system'},locale:{language:'en-US'},network:{proxyMode:'system',proxySecretRef:null},grid:{enabled:true},privacy:{telemetry:false},appPermissions:{}};this.events=[];this.ready=this.#load(); }
  async #load(){if(this.repository?.ensure) await this.repository.ensure(this.scopeId,this.settings); const loaded=await this.repository?.load?.(this.scopeId); if(loaded){this.version=Number(loaded.settingsVersion);this.contextVersion=Number(loaded.contextVersion);this.settings=loaded.settings;}}
  snapshot(){return {settingsVersion:String(this.version),settings:redact(this.settings)};}
  context(){return {contextVersion:String(this.contextVersion),settings:redact(this.settings),runtimeVersion:'v1'};}
  async patch({patch,baseVersion,actorId,requestId}){await this.ready;if(String(baseVersion)!==String(this.version))throw Object.assign(new Error('version_conflict'),{statusCode:409,current:this.snapshot()});const domain=patch?.domain;if(!domains.includes(domain)||!validators[domain]?.(patch.value))throw Object.assign(new Error('invalid_request'),{statusCode:422});const next=structuredClone(this.settings);next[domain]=structuredClone(patch.value);const restartRequired=domain==='network';const event={eventId:randomUUID(),contextVersion:String(this.contextVersion+1),domain,restartRequired};if(this.repository?.save){const saved=await this.repository.save(this.scopeId,{settingsVersion:String(this.version),settings:next},event);this.version=Number(saved.settingsVersion);this.contextVersion=Number(saved.contextVersion);}else{this.settings=next;this.version+=1;this.contextVersion+=1;this.events.push(event);}this.settings=next;await this.audit?.record({requestId,actorId,action:'system.settings.patch',targetType:'system_settings',targetId:null,summary:{domain,settingsVersion:String(this.version),restartRequired}});return {...this.snapshot(),restartRequired,contextVersion:String(this.contextVersion)};}
  getEvents(after=0){return this.events.filter((e)=>Number(e.contextVersion)>Number(after));}
}
