import { createHash, randomUUID } from 'node:crypto';

const digest = (value) => createHash('sha256').update(JSON.stringify(value ?? {})).digest('hex');
export class ActionService {
  constructor({ registry, permissions, audit } = {}) { this.registry = registry; this.permissions = permissions; this.audit = audit; this.runs = new Map(); this.handlers = new Map(); }
  register(action, handler) { this.registry.register(action); if (handler) this.handlers.set(action.actionId, handler); }
  list() { return { items: this.registry.list(), registryVersion: String(this.registry.version) }; }
  async plan({ actionId, input = {}, subjectId, appId, requestId }) { const action = this.registry.get(actionId); if (!action) throw Object.assign(new Error('action_not_found'), { statusCode: 404 }); const permission = this.permissions.check({ subjectId, appId: appId ?? action.ownerAppId, capability: action.requiredCapability, declared: [action.requiredCapability], requestId }); const confirmationRequired = action.riskLevel === 'high' || permission.decision !== 'allow'; const plan = { planId: randomUUID(), actionId, actionVersion: String(this.registry.version), inputDigest: digest(input), inputSummary: Object.keys(input), riskLevel: action.riskLevel, requiredCapability: action.requiredCapability, confirmationRequired, permission, expiresAt: new Date(Date.now() + 5 * 60_000).toISOString() }; this.runs.set(plan.planId, { ...plan, subjectId, state: 'planned', requestId }); await this.audit?.record({ requestId, actorId: subjectId, action: 'action.plan', targetType: 'action', targetId: actionId, summary: { riskLevel: action.riskLevel, confirmationRequired } }); return plan; }
  async execute({ actionId, input = {}, subjectId, appId, planId, confirmed = false, requestId }) { const plan = this.runs.get(planId); const action = this.registry.get(actionId); if (!action) throw Object.assign(new Error('action_not_found'), { statusCode: 404 }); if (!plan || plan.subjectId !== subjectId || plan.actionId !== actionId || plan.state !== 'planned') throw Object.assign(new Error('confirmation_required'), { statusCode: 428 }); const permission = this.permissions.check({ subjectId, appId: appId ?? action.ownerAppId, capability: action.requiredCapability, declared: [action.requiredCapability], requestId }); if (permission.decision !== 'allow') throw Object.assign(new Error('permission_denied'), { statusCode: 403 }); if ((action.riskLevel === 'high' || plan.confirmationRequired) && !confirmed) throw Object.assign(new Error('confirmation_required'), { statusCode: 428 }); const existing = [...this.runs.values()].find((x) => x.requestId === requestId && x.runId); if (existing) return existing; const run = { runId: randomUUID(), planId, actionId, subjectId, requestId, state: 'queued', handlerCalls: 0, createdAt: new Date().toISOString() }; this.runs.set(run.runId, run); await this.audit?.record({ requestId, actorId: subjectId, action: 'action.execute', targetType: 'action_run', targetId: run.runId, summary: { actionId } }); plan.state = 'queued'; queueMicrotask(async () => { if (run.state === 'cancel_requested') return; run.state = 'running'; const handler = this.handlers.get(actionId); try { run.handlerCalls += 1; run.result = handler ? await handler(input, { runId: run.runId }) : { ok: true }; run.state = 'succeeded'; } catch (error) { run.state = 'failed'; run.error = error.message; } }); return run; }
  get(runId, subjectId) { const run = this.runs.get(runId); if (!run || run.subjectId !== subjectId) throw Object.assign(new Error('action_run_not_found'), { statusCode: 404 }); return run; }
  cancel(runId, subjectId, requestId) { const run = this.get(runId, subjectId); if (['succeeded', 'failed', 'cancelled'].includes(run.state)) return run; if (run.state === 'queued') run.state = 'cancelled'; else run.state = 'cancel_requested'; run.cancelRequestId = requestId; return run; }
}
