import { createHash, randomUUID } from 'node:crypto';

const digest = (value) => createHash('sha256').update(JSON.stringify(value ?? {})).digest('hex');
const safeError = (error) => String(error?.message ?? 'handler_failed').slice(0, 240).replace(/token|secret|password/gi, '[redacted]');

export class ActionService {
  constructor({ registry, permissions, audit, repository } = {}) { this.registry=registry; this.permissions=permissions; this.audit=audit; this.repository=repository ?? new (class { constructor(){this.plans=new Map();this.runs=new Map();} async createPlan(x){this.plans.set(x.planId,x);return x;} async getPlan(id){return this.plans.get(id);} async updatePlan(id,state){const p=this.plans.get(id);if(p){p.state=state;return p;}} async createRun(x){const old=[...this.runs.values()].find(r=>r.subjectId===x.subjectId&&r.requestId===x.requestId);if(old)return {run:old,created:false};const run={...x,runId:x.runId??randomUUID()};this.runs.set(run.runId,run);return {run,created:true};} async findRunByRequest(s,r){return [...this.runs.values()].find(x=>x.subjectId===s&&x.requestId===r);} async getRun(id){return this.runs.get(id);} async transitionRun(id,from,to,patch={}){const r=this.runs.get(id);if(!r||!from.includes(r.state))return;Object.assign(r,patch,{state:to});return r;}})(); this.handlers=new Map(); }
  register(action, handler) { const definition=this.registry.register(action); this.repository.saveDefinition?.({ ...definition, actionVersion:this.registry.version }); if (handler) this.handlers.set(action.actionId,handler); return definition; }
  list() { return { items:this.registry.list().map(({ actionId, ownerAppId, requiredCapability, riskLevel, sideEffects, timeout, cancellationPolicy })=>({actionId,ownerAppId,requiredCapability,riskLevel,sideEffects,timeout,cancellationPolicy})), registryVersion:String(this.registry.version) }; }
  validateInput(action,input) { if (action.inputSchema?.type==='object' && (input===null || typeof input!=='object' || Array.isArray(input))) throw Object.assign(new Error('invalid_request'),{statusCode:422}); for(const name of action.inputSchema?.required??[]) if (!(name in input)) throw Object.assign(new Error('invalid_request'),{statusCode:422}); return true; }
  async plan({actionId,input={},subjectId,appId,requestId}) { const action=this.registry.get(actionId); if(!action) throw Object.assign(new Error('action_not_found'),{statusCode:404}); this.validateInput(action,input); const permission=this.permissions.check({subjectId,appId:appId??action.ownerAppId,capability:action.requiredCapability,declared:[action.requiredCapability],requestId}); const plan={planId:randomUUID(),requestId,actionId,actionVersion:String(action.actionVersion??this.registry.version),registryVersion:String(this.registry.version),inputDigest:digest(input),inputSummary:Object.keys(input).slice(0,32),riskLevel:action.riskLevel,requiredCapability:action.requiredCapability,confirmationRequired:action.riskLevel==='high'||permission.decision!=='allow',confirmationState:action.riskLevel==='high'||permission.decision!=='allow'?'pending':'not_required',permission,expiresAt:new Date(Date.now()+300000).toISOString(),state:'planned',subjectId}; await this.repository.createPlan(plan); await this.audit?.record({requestId,actorId:subjectId,action:'action.plan',targetType:'action',targetId:actionId,summary:{riskLevel:action.riskLevel,confirmationRequired:plan.confirmationRequired}}); return plan; }
  async execute({actionId,input={},subjectId,appId,planId,confirmed=false,requestId}) { const plan=await this.repository.getPlan(planId); const action=this.registry.get(actionId); if(!action) throw Object.assign(new Error('action_not_found'),{statusCode:404}); if(!plan||plan.subjectId!==subjectId||plan.actionId!==actionId||plan.state!=='planned') throw Object.assign(new Error('confirmation_required'),{statusCode:428}); if(Date.parse(plan.expiresAt)<=Date.now()) throw Object.assign(new Error('confirmation_required'),{statusCode:410}); if(String(plan.actionVersion)!==String(action.actionVersion??this.registry.version)) throw Object.assign(new Error('version_conflict'),{statusCode:409}); if(digest(input)!==plan.inputDigest) throw Object.assign(new Error('invalid_request'),{statusCode:422}); const permission=this.permissions.check({subjectId,appId:appId??action.ownerAppId,capability:action.requiredCapability,declared:[action.requiredCapability],requestId}); if(permission.decision!=='allow') throw Object.assign(new Error('permission_denied'),{statusCode:403}); if(plan.confirmationRequired&&!confirmed) throw Object.assign(new Error('confirmation_required'),{statusCode:428}); const created=await this.repository.createRun({runId:randomUUID(),planId,actionId,actionVersion:String(action.actionVersion??this.registry.version),inputDigest:plan.inputDigest,subjectId,requestId,timeoutAt:new Date(Date.now()+(action.timeout??30000)).toISOString(),state:'queued',handlerCalls:0}); const run=created.run; if(!created.created) return run; const consumed=await this.repository.updatePlan(planId,'queued',['planned']); if(!consumed) { await this.repository.transitionRun(run.runId,['queued'],'cancelled'); return run; } await this.audit?.record({requestId,actorId:subjectId,action:'action.execute',targetType:'action_run',targetId:run.runId,summary:{actionId}}); queueMicrotask(()=>this.#run(run,action,input)); return run; }
  async #run(run,action,input) { const started=await this.repository.transitionRun(run.runId,['queued'],'running'); if(!started)return; let timer; try { const handler=this.handlers.get(action.actionId); const result=await Promise.race([handler?handler(input,{runId:run.runId}):{ok:true},new Promise((_,reject)=>{timer=setTimeout(()=>reject(Object.assign(new Error('action_timeout'),{code:'timeout'})),action.timeout??30000);})]); clearTimeout(timer); await this.repository.transitionRun(run.runId,['running'],'succeeded',{handlerCalls:1,resultSummary:result&&typeof result==='object'?{ok:result.ok??true}:undefined}); } catch(error) { clearTimeout(timer); await this.repository.transitionRun(run.runId,['running','cancel_requested'],error.code==='timeout'?'failed':'failed',{handlerCalls:1,errorSummary:safeError(error)}); } }
  async get(runId,subjectId) { const run=await this.repository.getRun(runId); if(!run||run.subjectId!==subjectId) throw Object.assign(new Error('action_run_not_found'),{statusCode:404}); return run; }
  async cancel(runId,subjectId,requestId) { const run=await this.get(runId,subjectId); if(['succeeded','failed','cancelled'].includes(run.state))return run; const updated=await this.repository.transitionRun(runId,['queued'],'cancelled',{cancelRequestId:requestId}); if(updated)return updated; const requested=await this.repository.transitionRun(runId,['running'],'cancel_requested',{cancelRequestId:requestId}); return requested??run; }
}
