import { randomUUID } from 'node:crypto';

const iso = (value) => value ? new Date(value).toISOString() : null;
const policyOut = (r) => r && ({ policyId: r.policy_id ?? r.policyId, scopeType: r.scope_type ?? r.scopeType, scopeId: r.scope_id ?? r.scopeId, metric: r.metric, windowSeconds: Number(r.window_seconds ?? r.windowSeconds), hardLimit: r.hard_limit ?? r.hardLimit, softLimit: r.soft_limit ?? r.softLimit, version: Number(r.version), effectiveAt: iso(r.effective_at ?? r.effectiveAt) });
const reservationOut = (r) => r && ({ reservationId: r.reservation_id ?? r.reservationId, requestId: r.request_id ?? r.requestId, subjectId: r.subject_id ?? r.subjectId, scopeType: r.scope_type ?? r.scopeType, scopeId: r.scope_id ?? r.scopeId, providerAccountId: r.provider_account_id ?? r.providerAccountId, providerConfigId: r.provider_config_id ?? r.providerConfigId, modelRef: r.model_ref ?? r.modelRef, taskId: r.task_id ?? r.taskId, attemptId: r.attempt_id ?? r.attemptId, metric: r.metric, amount: Number(r.amount), state: r.state, policyVersion: Number(r.policy_version ?? r.policyVersion), windowStart: iso(r.window_start ?? r.windowStart), expiresAt: iso(r.expires_at ?? r.expiresAt), createdAt: iso(r.created_at ?? r.createdAt), updatedAt: iso(r.updated_at ?? r.updatedAt) });
const usageOut = (r) => r && ({ usageEventId: r.usage_event_id ?? r.usageEventId, requestId: r.request_id ?? r.requestId, subjectId: r.subject_id ?? r.subjectId, providerAccountId: r.provider_account_id ?? r.providerAccountId, providerConfigId: r.provider_config_id ?? r.providerConfigId, modelRef: r.model_ref ?? r.modelRef, taskId: r.task_id ?? r.taskId, attemptId: r.attempt_id ?? r.attemptId, metric: r.metric, amount: Number(r.amount), unit: r.unit, usageStatus: r.usage_status ?? r.usageStatus, estimated: Boolean(r.estimated), inputTokens: r.input_tokens ?? r.inputTokens, outputTokens: r.output_tokens ?? r.outputTokens, totalTokens: r.total_tokens ?? r.totalTokens, estimatedCost: r.estimated_cost ?? r.estimatedCost, sourceDigest: r.source_digest ?? r.sourceDigest, operation: r.operation, reservationId: r.reservation_id ?? r.reservationId, windowStart: iso(r.window_start ?? r.windowStart), occurredAt: iso(r.occurred_at ?? r.occurredAt) });

export class PostgresQuotaRepository {
  constructor(pool, { audit } = {}) { this.pool = pool; this.audit = audit; }
  async withTransaction(work) { const client = await this.pool.connect(); try { await client.query('BEGIN'); const out = await work(client); await client.query('COMMIT'); return out; } catch (e) { await client.query('ROLLBACK'); throw e; } finally { client.release(); } }
  async findPolicy(input, client = this.pool) {
    const candidates = [['subject', input.subjectId], ['provider_account', input.providerAccountId], ['provider_config', input.providerConfigId], ['model', input.modelRef], ['deployment', input.deploymentId]].filter(([, id]) => id);
    if (input.scopeType && input.scopeId) candidates.unshift([input.scopeType, input.scopeId]);
    if (!candidates.length) return undefined;
    const values = [input.metric]; const clauses = candidates.map(([type, id]) => { values.push(type, String(id)); return `(scope_type = $${values.length - 1} AND scope_id = $${values.length})`; });
    const { rows } = await client.query(`SELECT * FROM quota_policies WHERE metric = $1 AND effective_at <= now() AND (${clauses.join(' OR ')}) ORDER BY version DESC LIMIT 1`, values);
    return policyOut(rows[0]);
  }
  async listPolicies(subjectId, client = this.pool) { const { rows } = await client.query('SELECT * FROM quota_policies WHERE scope_id = $1 OR scope_type = \'deployment\' ORDER BY effective_at DESC, version DESC', [String(subjectId)]); return rows.map(policyOut); }
  async upsertPolicy(input, client = this.pool) { const { rows } = await client.query('INSERT INTO quota_policies (policy_id, scope_type, scope_id, metric, window_seconds, hard_limit, soft_limit, version, effective_at, created_by) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING *', [input.policyId ?? randomUUID(), input.scopeType, String(input.scopeId), input.metric, input.windowSeconds, input.hardLimit ?? null, input.softLimit ?? null, input.version, input.effectiveAt ?? new Date(), input.createdBy ?? null]); return policyOut(rows[0]); }
  async writeAudit(event, client) { return this.audit?.record(event, client); }
  async getReservation(id, client = this.pool) { const { rows } = await client.query('SELECT * FROM quota_reservations WHERE reservation_id = $1', [id]); return reservationOut(rows[0]); }
  async findReservationByKey(input, client = this.pool) { const { rows } = await client.query('SELECT * FROM quota_reservations WHERE task_id=$1 AND attempt_id=$2 AND metric=$3', [input.taskId, input.attemptId, input.metric]); return reservationOut(rows[0]); }
  async reserve(input, client = this.pool) {
    const { rows } = await client.query(`INSERT INTO quota_reservations (reservation_id, request_id, subject_id, scope_type, scope_id, provider_account_id, provider_config_id, model_ref, task_id, attempt_id, metric, amount, state, policy_version, window_start, expires_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,'reserved',$13,$14,$15) RETURNING *`, [input.reservationId ?? randomUUID(), input.requestId, input.subjectId, input.scopeType, String(input.scopeId), input.providerAccountId ?? null, input.providerConfigId ?? null, input.modelRef ?? null, input.taskId, input.attemptId, input.metric, input.amount, input.policyVersion, input.windowStart, input.expiresAt]); return reservationOut(rows[0]);
  }
  async reservedAmount(input, client = this.pool) { const { rows } = await client.query("SELECT COALESCE(sum(amount),0)::numeric AS amount FROM quota_reservations WHERE scope_type=$1 AND scope_id=$2 AND metric=$3 AND window_start=$4 AND state='reserved' AND expires_at > now()", [input.scopeType, String(input.scopeId), input.metric, input.windowStart]); return Number(rows[0].amount); }
  async lockQuotaWindow(input, client) { await client.query('SELECT pg_advisory_xact_lock(hashtext($1))', [`${input.scopeType}:${input.scopeId}:${input.metric}:${input.windowStart}`]); }
  async settle(input, client = this.pool) {
    const locked = await client.query('SELECT * FROM quota_reservations WHERE reservation_id = $1 FOR UPDATE', [input.reservationId]);
    const existing = reservationOut(locked.rows[0]); if (!existing) return undefined;
    const already = await client.query('SELECT * FROM usage_events WHERE task_id=$1 AND attempt_id=$2 AND metric=$3', [existing.taskId, existing.attemptId, existing.metric]);
    if (already.rows[0]) return { reservation: existing, usage: usageOut(already.rows[0]), idempotent: true };
    const finalState = input.release ? 'released' : 'settled';
    await client.query("UPDATE quota_reservations SET state=$2, updated_at=now() WHERE reservation_id=$1 AND state='reserved'", [input.reservationId, finalState]);
    if (input.release) return { reservation: await this.getReservation(input.reservationId, client), usage: null, idempotent: false };
    const { rows } = await client.query(`INSERT INTO usage_events (usage_event_id, request_id, subject_id, provider_account_id, provider_config_id, model_ref, task_id, attempt_id, metric, amount, unit, usage_status, estimated, input_tokens, output_tokens, total_tokens, estimated_cost, source_digest, operation, occurred_at, reservation_id, window_start) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22) ON CONFLICT (task_id,attempt_id,metric) DO UPDATE SET usage_event_id = usage_events.usage_event_id RETURNING *`, [randomUUID(), input.requestId, existing.subjectId, existing.providerAccountId, existing.providerConfigId, existing.modelRef, existing.taskId, existing.attemptId, existing.metric, input.amount, input.unit ?? 'count', input.usageStatus, Boolean(input.estimated), input.inputTokens ?? null, input.outputTokens ?? null, input.totalTokens ?? null, input.estimatedCost ?? null, input.sourceDigest ?? null, input.operation ?? null, input.occurredAt ?? new Date(), input.reservationId, existing.windowStart]);
    return { reservation: await this.getReservation(input.reservationId, client), usage: usageOut(rows[0]), idempotent: false };
  }
  async queryUsage(input, client = this.pool) { const values = [input.from, input.to]; let where = 'occurred_at >= $1 AND occurred_at <= $2'; if (input.subjectId) { values.push(input.subjectId); where += ` AND subject_id = $${values.length}`; } const { rows } = await client.query(`SELECT * FROM usage_events WHERE ${where} ORDER BY occurred_at DESC, usage_event_id DESC`, values); return { items: rows.map(usageOut), aggregateVersion: rows.at(-1)?.usage_event_id ?? null }; }
  async reconcile({ checkpointName = 'default', limit = 100, subjectId } = {}, transactionClient) { const run = async (client) => { await client.query("INSERT INTO quota_reconciliation_checkpoints (checkpoint_name,state) VALUES ($1,'running') ON CONFLICT (checkpoint_name) DO UPDATE SET state='running',updated_at=now()", [checkpointName]); const values = [limit]; const subjectClause = subjectId ? ' AND subject_id=$2' : ''; if (subjectId) values.push(subjectId); const { rows } = await client.query(`SELECT * FROM quota_reservations WHERE state='reserved' AND expires_at <= now()${subjectClause} ORDER BY created_at LIMIT $1 FOR UPDATE SKIP LOCKED`, values); let repaired = 0; for (const row of rows) { await client.query("UPDATE quota_reservations SET state='expired',updated_at=now() WHERE reservation_id=$1 AND state='reserved'", [row.reservation_id]); await client.query("INSERT INTO quota_reconciliation_items (item_id,reservation_id,task_id,attempt_id,metric,reason,state) VALUES ($1,$2,$3,$4,$5,'expired_reservation','resolved') ON CONFLICT DO NOTHING", [randomUUID(),row.reservation_id,row.task_id,row.attempt_id,row.metric]); repaired += 1; } await client.query("UPDATE quota_reconciliation_checkpoints SET state='completed', scanned_count=scanned_count+$2, repaired_count=repaired_count+$3, updated_at=now() WHERE checkpoint_name=$1", [checkpointName, rows.length, repaired]); return { checkpointName, scanned: rows.length, repaired, state: 'completed' }; }; return transactionClient ? run(transactionClient) : this.withTransaction(run); }
}

export class InMemoryQuotaRepository {
  constructor() { this.policies = []; this.reservations = new Map(); this.usage = new Map(); this.reconciliation = new Map(); this.auditEvents = []; this.windowLocks = new Map(); }
  async withTransaction(work) { return work(undefined); }
  async lockQuotaWindow(input) { const key = `${input.scopeType}:${input.scopeId}:${input.metric}:${input.windowStart}`; const previous = this.windowLocks.get(key) ?? Promise.resolve(); let release; const current = new Promise((resolve) => { release = resolve; }); this.windowLocks.set(key, previous.then(() => current)); await previous; return () => { release(); if (this.windowLocks.get(key) === current) this.windowLocks.delete(key); }; }
  async writeAudit(event) { this.auditEvents.push(event); }
  async findPolicy(input) { return this.policies.filter((p) => p.metric === input.metric && (!p.effectiveAt || new Date(p.effectiveAt) <= new Date()) && [['subject',input.subjectId],['provider_account',input.providerAccountId],['provider_config',input.providerConfigId],['model',input.modelRef],['deployment',input.deploymentId]].some(([t,id]) => id && p.scopeType === t && String(p.scopeId) === String(id))).sort((a,b)=>b.version-a.version)[0]; }
  async listPolicies(subjectId) { return this.policies.filter((p) => p.scopeType === 'deployment' || String(p.scopeId) === String(subjectId)); }
  async upsertPolicy(input) { const p = { ...input, policyId: input.policyId ?? randomUUID(), scopeId: String(input.scopeId), effectiveAt: input.effectiveAt ?? new Date().toISOString() }; this.policies.push(p); return p; }
  async getReservation(id) { return this.reservations.get(id); }
  async findReservationByKey(i) { return [...this.reservations.values()].find((r) => r.taskId === i.taskId && r.attemptId === i.attemptId && r.metric === i.metric); }
  async reservedAmount(i) { return [...this.reservations.values()].filter((r)=>r.scopeType===i.scopeType&&String(r.scopeId)===String(i.scopeId)&&r.metric===i.metric&&r.windowStart===i.windowStart&&r.state==='reserved'&&new Date(r.expiresAt)>new Date()).reduce((n,r)=>n+Number(r.amount),0); }
  async reserve(i) { const r={...i,reservationId:i.reservationId??randomUUID(),state:'reserved',createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()}; this.reservations.set(r.reservationId,r); return r; }
  async settle(i) { const r=this.reservations.get(i.reservationId); if(!r) return undefined; const key=`${r.taskId}:${r.attemptId}:${r.metric}`; if(this.usage.has(key)) return {reservation:r,usage:this.usage.get(key),idempotent:true}; r.state=i.release?'released':'settled'; r.updatedAt=new Date().toISOString(); if(i.release)return {reservation:r,usage:null,idempotent:false}; const u={usageEventId:randomUUID(),requestId:i.requestId,subjectId:r.subjectId,taskId:r.taskId,attemptId:r.attemptId,metric:r.metric,amount:Number(i.amount),unit:i.unit??'count',usageStatus:i.usageStatus,estimated:Boolean(i.estimated),sourceDigest:i.sourceDigest??null,occurredAt:new Date().toISOString()}; this.usage.set(key,u); return {reservation:r,usage:u,idempotent:false}; }
  async queryUsage(i) { return {items:[...this.usage.values()].filter(u=>(!i.subjectId||u.subjectId===i.subjectId)&&new Date(u.occurredAt)>=new Date(i.from)&&new Date(u.occurredAt)<=new Date(i.to)),aggregateVersion:null}; }
  async reconcile() { let repaired=0; for(const r of this.reservations.values()) if(r.state==='reserved'&&new Date(r.expiresAt)<=new Date()){r.state='expired';repaired++;} return {checkpointName:'default',scanned:repaired,repaired,state:'completed'}; }
}
