import { randomUUID } from 'node:crypto';

export class QuotaService {
  constructor({ repository, audit, clock = () => new Date() }) { this.repository = repository; this.audit = audit; this.clock = clock; }
  async preflightQuota(input) {
    const policy = await this.repository.findPolicy(input).catch(() => { throw Object.assign(new Error('quota_unavailable'), { statusCode: 503 }); });
    if (!policy) return { decision: 'deny', reason: 'quota_exceeded', policyVersion: null, requestId: input.requestId };
    const windowStart = this.windowStart(policy, this.clock()); const used = await this.repository.reservedAmount({ ...input, ...policy, windowStart }); const hard = policy.hardLimit == null ? Infinity : Number(policy.hardLimit); const soft = policy.softLimit == null ? hard : Number(policy.softLimit); const requested = Number(input.amount ?? 1); const decision = used + requested > hard ? 'deny' : used + requested > soft ? 'warn' : 'allow'; return { decision, reason: decision === 'deny' ? 'quota_exceeded' : undefined, policyVersion: policy.version, remaining: Math.max(0, hard - used), windowStart, requestId: input.requestId };
  }
  windowStart(policy, now) { const ms = Number(policy.windowSeconds) * 1000; return new Date(Math.floor(now.getTime() / ms) * ms).toISOString(); }
  async reserveQuota(input) {
    const existing = await this.repository.findReservationByKey(input); if (existing) { if (input.requestId && existing.requestId && existing.requestId !== input.requestId) throw Object.assign(new Error('reservation_conflict'), { statusCode: 409 }); return existing; }
    const policy = await this.repository.findPolicy(input); if (!policy) throw Object.assign(new Error('quota_exceeded'), { statusCode: 429 }); const windowStart = this.windowStart(policy, this.clock()); const amount = Number(input.amount ?? 1); const reservationInput = { ...input, ...policy, policyVersion: policy.version, amount, windowStart, expiresAt: input.expiresAt ?? new Date(this.clock().getTime() + 300000).toISOString() }; const reservation = await (this.repository.withTransaction ? this.repository.withTransaction(async (client) => { await this.repository.lockQuotaWindow({ ...input, ...policy, windowStart }, client); const nowCurrent = await this.repository.reservedAmount({ ...input, ...policy, windowStart }, client); if (policy.hardLimit != null && nowCurrent + amount > Number(policy.hardLimit)) throw Object.assign(new Error('quota_exceeded'), { statusCode: 429 }); return this.repository.reserve(reservationInput, client); }) : this.repository.reserve(reservationInput));
    await this.recordAudit(input, 'quota.reservation.create', reservation.reservationId, { metric: reservation.metric, amount: reservation.amount, state: reservation.state }); return reservation;
  }
  async settleUsage(input) { const result = await (this.repository.withTransaction ? this.repository.withTransaction((client) => this.repository.settle(input, client)) : this.repository.settle(input)); if (!result) throw Object.assign(new Error('reservation_not_found'), { statusCode: 404 }); await this.recordAudit(input, 'quota.reservation.settle', input.reservationId, { state: result.reservation.state, usageStatus: result.usage?.usageStatus ?? 'released' }); return { ...result, reconciliation: 'complete' }; }
  async queryUsage(input) { return this.repository.queryUsage(input); }
  async listPolicies(input) { return { items: await this.repository.listPolicies(input.subjectId) }; }
  async updatePolicy(input) { const policies = await this.repository.listPolicies(input.scopeId); const current = policies.filter((p) => p.scopeType === input.scopeType && String(p.scopeId) === String(input.scopeId) && p.metric === input.metric).sort((a,b)=>b.version-a.version)[0]; if (input.baseVersion != null && current && Number(input.baseVersion) !== Number(current.version)) throw Object.assign(new Error('policy_version_conflict'), { statusCode: 409 }); const policy = await (this.repository.withTransaction ? this.repository.withTransaction((client) => this.repository.upsertPolicy({ ...input, version: (current?.version ?? 0) + 1 }, client)) : this.repository.upsertPolicy({ ...input, version: (current?.version ?? 0) + 1 })); await this.recordAudit(input, 'quota.policy.update', policy.policyId, { scopeType: policy.scopeType, scopeId: policy.scopeId, metric: policy.metric, version: policy.version }); return policy; }
  async reconcile(input = {}) { const result = await this.repository.reconcile(input); await this.recordAudit(input, 'quota.reconciliation.run', null, { checkpointName: result.checkpointName, scanned: result.scanned, repaired: result.repaired, state: result.state }); return result; }
  async recordAudit(input, action, targetId, summary) { if (this.audit?.record) await this.audit.record({ requestId: input.requestId ?? randomUUID(), actorId: input.actorId ?? input.subjectId, action, targetType: action.includes('policy') ? 'quota_policy' : 'quota_reservation', targetId, summary }); }
}
