import { randomUUID } from 'node:crypto';

const invalid = () => Object.assign(new Error('invalid_request'), { statusCode: 422 });
const forbidden = () => Object.assign(new Error('insufficient_scope'), { statusCode: 403 });
// Keep addition of two quota values within JS safe integer precision at six decimals.
const MAX_QUOTA_VALUE = 4_000_000_000;
const bounded = (value, { integer = false, positive = false } = {}) => {
  if (typeof value !== 'number' || !Number.isFinite(value) || value < 0 || value > MAX_QUOTA_VALUE || (integer ? !Number.isSafeInteger(value) : !Number.isSafeInteger(Math.round(value * 1e6)) || Math.round(value * 1e6) / 1e6 !== value) || (positive && value === 0)) throw invalid();
  return value;
};
const instant = (value) => { const time = new Date(value); if (!value || !Number.isFinite(time.getTime())) throw invalid(); return time.toISOString(); };
const clockDate = (clock) => { const value = clock(); const date = new Date(value); if (!Number.isFinite(date.getTime())) throw Object.assign(new Error('quota_unavailable'), { statusCode: 503 }); return date; };

export class QuotaService {
  constructor({ repository, audit, clock = () => new Date() }) { this.repository = repository; this.audit = audit; this.clock = clock; }
  async preflightQuota(input) {
    this.validateRequest(input, ['metric']);
    bounded(input.amount ?? 1);
    const policy = await this.repository.findPolicy(input).catch(() => { throw Object.assign(new Error('quota_unavailable'), { statusCode: 503 }); });
    if (!policy) return { decision: 'deny', reason: 'quota_exceeded', policyVersion: null, requestId: input.requestId };
    const requested = bounded(input.amount ?? 1); const windowStart = this.windowStart(policy, clockDate(this.clock)); const used = await this.repository.reservedAmount({ ...input, ...policy, windowStart }); const hard = policy.hardLimit == null ? Infinity : Number(policy.hardLimit); const soft = policy.softLimit == null ? hard : Number(policy.softLimit); const decision = used + requested > hard ? 'deny' : used + requested > soft ? 'warn' : 'allow'; return { decision, reasonCode: decision === 'deny' ? 'quota_exceeded' : undefined, policyVersion: String(policy.version), remaining: Math.max(0, hard - used), requestId: input.requestId };
  }
  async preflight(input) { const result = await this.preflightQuota({ ...input, metric: input.metric ?? 'requests', amount: input.amount ?? 1, requestId: input.requestId ?? randomUUID() }); if (result.decision === 'deny') throw Object.assign(new Error(result.reasonCode ?? 'quota_exceeded'), { statusCode: 429 }); return { ...result, allowed: true }; }
  windowStart(policy, now) { const ms = bounded(Number(policy.windowSeconds), { integer: true, positive: true }) * 1000; return new Date(Math.floor(new Date(now).getTime() / ms) * ms).toISOString(); }
  async reserveQuota(input, transactionClient) {
    this.validateRequest(input, ['requestId', 'subjectId', 'taskId', 'attemptId', 'metric', 'scopeType', 'scopeId']);
    if (input.scopeType === 'subject' && String(input.scopeId) !== String(input.subjectId)) throw forbidden();
    const amount = bounded(input.amount ?? 1); const expiresAt = input.expiresAt ? instant(input.expiresAt) : new Date(clockDate(this.clock).getTime() + 300000).toISOString();
    const run = async (client) => { const unlock = await this.repository.lockQuotaWindow(input, client); try { const existing = await this.repository.findReservationByKey(input, client); if (existing) { if (existing.subjectId !== input.subjectId || existing.scopeType !== input.scopeType || String(existing.scopeId) !== String(input.scopeId) || Number(existing.amount) !== amount) throw Object.assign(new Error('reservation_conflict'), { statusCode: 409 }); return this.toReservationContract(existing); } const policy = await this.repository.findPolicy(input, client); if (!policy) throw Object.assign(new Error('quota_exceeded'), { statusCode: 429 }); const windowStart = this.windowStart(policy, clockDate(this.clock)); const current = await this.repository.reservedAmount({ ...input, ...policy, windowStart }, client); if (policy.hardLimit != null && current + amount > Number(policy.hardLimit)) throw Object.assign(new Error('quota_exceeded'), { statusCode: 429 }); const created = await this.repository.reserve({ ...policy, ...input, policyVersion: policy.version, amount, windowStart, expiresAt }, client); await this.auditQuota(input, 'quota.reservation.create', created.reservationId, { metric: created.metric, amount: created.amount, state: created.state }, client); return this.toReservationContract(created); } finally { unlock?.(); } };
    if (transactionClient) return run(transactionClient);
    if (this.repository.withTransaction) return this.repository.withTransaction(run);
    throw Object.assign(new Error('quota_unavailable'), { statusCode: 503 });
  }
  async settleUsage(input, authContext) { this.validateRequest(input, ['requestId', 'reservationId', 'taskId', 'attemptId', 'terminalState']); if (!authContext?.actorId || !authContext?.subjectId) throw forbidden(); if (!input.release) bounded(input.amount); const perform = async (client) => { const existing = await this.repository.getReservation(input.reservationId, client); if (!existing) return undefined; if (String(existing.subjectId) !== String(authContext.subjectId) || (!authContext.admin && String(existing.subjectId) !== String(authContext.actorId))) throw forbidden(); if (String(existing.taskId) !== String(input.taskId) || String(existing.attemptId) !== String(input.attemptId)) throw Object.assign(new Error('reservation_conflict'), { statusCode: 409 }); const out = await this.repository.settle(input, client); if (!out) return undefined; if (!out.idempotent) await this.auditQuota({ ...input, actorId: authContext.actorId }, 'quota.reservation.settle', input.reservationId, { state: out.reservation.state, usageStatus: out.usage?.usageStatus ?? 'released' }, client); return out; }; const result = this.repository.withTransaction ? await this.repository.withTransaction(perform) : await perform(undefined); if (!result) throw Object.assign(new Error('reservation_not_found'), { statusCode: 404 }); return { ...result, reservationId: input.reservationId, requestId: input.requestId, state: result.reservation.state === 'needs_review' ? 'reconciliation_required' : result.reservation.state, usageEventId: result.usage?.usageEventId, usageStatus: result.usage?.usageStatus, reconciliation: 'complete' }; }
  async releaseQuota(input, authContext) { return this.settleUsage({ ...input, release: true, usageStatus: input.usageStatus ?? 'unavailable', amount: input.amount ?? 0 }, authContext); }
  async queryUsage(input, authContext) { this.validateRequest(input, ['subjectId', 'from', 'to']); if (!authContext?.actorId || !authContext?.subjectId || String(input.subjectId) !== String(authContext.subjectId) || (!authContext.admin && String(input.subjectId) !== String(authContext.actorId))) throw forbidden(); if (instant(input.from) > instant(input.to)) throw invalid(); return this.repository.queryUsage(input); }
  async listPolicies(input) { return { items: (await this.repository.listPolicies(input.subjectId)).map((policy) => this.toPolicyContract(policy)) }; }
  async updatePolicy(input) { this.validateRequest(input, ['requestId','scopeType','scopeId','metric','windowSeconds','hardLimit','effectiveAt']); bounded(input.windowSeconds, { integer: true, positive: true }); if (input.windowSeconds > 2147483647) throw invalid(); bounded(input.hardLimit); if (input.softLimit != null) { bounded(input.softLimit); if (input.softLimit > input.hardLimit) throw invalid(); } instant(input.effectiveAt); const perform = async (client) => { const unlock = await this.repository.lockQuotaWindow(input, client); try { const policies = await this.repository.listPolicies(input.scopeId, client); const current = policies.filter((p) => p.scopeType === input.scopeType && String(p.scopeId) === String(input.scopeId) && p.metric === input.metric).sort((a,b)=>b.version-a.version)[0]; if (input.baseVersion == null && current || input.baseVersion != null && Number(input.baseVersion) !== Number(current?.version ?? 0)) throw Object.assign(new Error('policy_version_conflict'), { statusCode: 409 }); const policy = await this.repository.upsertPolicy({ ...input, version: (current?.version ?? 0) + 1 }, client); await this.auditQuota(input, 'quota.policy.update', policy.policyId, { scopeType: policy.scopeType, scopeId: policy.scopeId, metric: policy.metric, version: policy.version }, client); return this.toPolicyContract(policy); } finally { unlock?.(); } }; return this.repository.withTransaction ? this.repository.withTransaction(perform) : perform(undefined); }
  async reconcile(input = {}) { const event = { ...input, requestId: input.requestId ?? randomUUID() }; const run = async (client) => { const result = await this.repository.reconcile(input, client); await this.auditQuota(event, 'quota.reconciliation.run', null, { checkpointName: result.checkpointName, scanned: result.scanned, repaired: result.repaired, state: result.state }, client); return result; }; return this.repository.withTransaction ? this.repository.withTransaction(run) : run(undefined); }
  async auditQuota(input, action, targetId, summary, client) { const event = { requestId: input.requestId, actorId: input.actorId ?? input.subjectId, action, targetType: action.includes('policy') ? 'quota_policy' : 'quota_reservation', targetId, policyVersion: input.policyVersion, summary }; if (this.repository.writeAudit) return this.repository.writeAudit(event, client); if (this.audit?.record) return this.audit.record(event, client); throw Object.assign(new Error('audit_unavailable'), { statusCode: 503 }); }
  toReservationContract(r) { return { reservationId: r.reservationId, requestId: r.requestId, taskId: r.taskId, attemptId: r.attemptId, reservedAmount: Number(r.amount), state: r.state === 'needs_review' ? 'reconciliation_required' : r.state, expiresAt: r.expiresAt }; }
  toPolicyContract(p) { return { policyId: p.policyId, scope: { type: p.scopeType, id: p.scopeId }, metric: p.metric, limit: Number(p.hardLimit), softLimit: p.softLimit == null ? undefined : Number(p.softLimit), window: p.windowSeconds === 3600 ? 'hour' : p.windowSeconds === 86400 ? 'day' : p.windowSeconds === 2592000 ? 'month' : 'rolling', version: String(p.version), effectiveAt: p.effectiveAt, failOpen: false }; }
  validateRequest(input, fields) { if (fields.some((field) => input?.[field] === undefined || input?.[field] === null || input?.[field] === '')) throw Object.assign(new Error('invalid_request'), { statusCode: 422 }); }
}

export function createQuotaAdapter(service) {
  return {
    preflight: (input) => service.preflight({ ...input, metric: input.metric ?? 'requests', amount: input.amount ?? 1 }),
    reserve: (input, client) => service.reserveQuota(input, client),
    settle: (input) => service.settleUsage(input, { actorId: input.subjectId, subjectId: input.subjectId, admin: false }),
    release: (input) => service.releaseQuota(input, { actorId: input.subjectId, subjectId: input.subjectId, admin: false }),
    queryUsage: (input, authContext) => service.queryUsage(input, authContext),
    reconcile: (input) => service.reconcile(input)
  };
}
