import { randomUUID } from 'node:crypto';

export class QuotaService {
  constructor({ repository, audit, clock = () => new Date() }) { this.repository = repository; this.audit = audit; this.clock = clock; }
  async preflightQuota(input) {
    this.validateRequest(input, ['metric']);
    const policy = await this.repository.findPolicy(input).catch(() => { throw Object.assign(new Error('quota_unavailable'), { statusCode: 503 }); });
    if (!policy) return { decision: 'deny', reason: 'quota_exceeded', policyVersion: null, requestId: input.requestId };
    const windowStart = this.windowStart(policy, this.clock()); const used = await this.repository.reservedAmount({ ...input, ...policy, windowStart }); const hard = policy.hardLimit == null ? Infinity : Number(policy.hardLimit); const soft = policy.softLimit == null ? hard : Number(policy.softLimit); const requested = Number(input.amount ?? 1); const decision = used + requested > hard ? 'deny' : used + requested > soft ? 'warn' : 'allow'; return { decision, reasonCode: decision === 'deny' ? 'quota_exceeded' : undefined, policyVersion: String(policy.version), remaining: Math.max(0, hard - used), requestId: input.requestId };
  }
  async preflight(input) { const result = await this.preflightQuota({ ...input, metric: input.metric ?? 'requests', amount: input.amount ?? 1, requestId: input.requestId ?? randomUUID() }); if (result.decision === 'deny') throw Object.assign(new Error(result.reasonCode ?? 'quota_exceeded'), { statusCode: 429 }); return { ...result, allowed: true }; }
  windowStart(policy, now) { const ms = Number(policy.windowSeconds) * 1000; return new Date(Math.floor(now.getTime() / ms) * ms).toISOString(); }
  async reserveQuota(input) {
    this.validateRequest(input, ['requestId', 'taskId', 'attemptId', 'metric', 'scopeType', 'scopeId']);
    const existing = await this.repository.findReservationByKey(input); if (existing) return this.toReservationContract(existing);
    const policy = await this.repository.findPolicy(input); if (!policy) throw Object.assign(new Error('quota_exceeded'), { statusCode: 429 }); const windowStart = this.windowStart(policy, this.clock()); const amount = Number(input.amount ?? 1); const reservationInput = { ...policy, ...input, policyVersion: policy.version, amount, windowStart, expiresAt: input.expiresAt ?? new Date(this.clock().getTime() + 300000).toISOString() };
    if (this.repository.withTransaction) return this.repository.withTransaction(async (client) => { const existing = await this.repository.findReservationByKey(input, client); if (existing) return this.toReservationContract(existing); const unlock = await this.repository.lockQuotaWindow({ ...input, ...policy, windowStart }, client); try { const current = await this.repository.reservedAmount({ ...input, ...policy, windowStart }, client); if (policy.hardLimit != null && current + amount > Number(policy.hardLimit)) throw Object.assign(new Error('quota_exceeded'), { statusCode: 429 }); const created = await this.repository.reserve(reservationInput, client); await this.auditQuota(input, 'quota.reservation.create', created.reservationId, { metric: created.metric, amount: created.amount, state: created.state }, client); return this.toReservationContract(created); } finally { unlock?.(); } });
    await this.auditQuota(input, 'quota.reservation.create', reservation.reservationId, { metric: reservation.metric, amount: reservation.amount, state: reservation.state }); return this.toReservationContract(reservation);
  }
  async settleUsage(input) { this.validateRequest(input, ['requestId', 'reservationId', 'taskId', 'attemptId', 'terminalState']); const perform = async (client) => { const existing = await this.repository.getReservation(input.reservationId, client); if (!existing) return undefined; if (String(existing.taskId) !== String(input.taskId) || String(existing.attemptId) !== String(input.attemptId)) throw Object.assign(new Error('reservation_conflict'), { statusCode: 409 }); const out = await this.repository.settle(input, client); if (!out) return undefined; await this.auditQuota(input, 'quota.reservation.settle', input.reservationId, { state: out.reservation.state, usageStatus: out.usage?.usageStatus ?? 'released' }, client); return out; }; const result = this.repository.withTransaction ? await this.repository.withTransaction(perform) : await perform(undefined); if (!result) throw Object.assign(new Error('reservation_not_found'), { statusCode: 404 }); return { ...result, reservationId: input.reservationId, requestId: input.requestId, state: result.reservation.state === 'needs_review' ? 'reconciliation_required' : result.reservation.state, usageEventId: result.usage?.usageEventId, usageStatus: result.usage?.usageStatus, reconciliation: 'complete' }; }
  async releaseQuota(input) { return this.settleUsage({ ...input, release: true, usageStatus: input.usageStatus ?? 'unavailable', amount: input.amount ?? 0 }); }
  async queryUsage(input) { return this.repository.queryUsage(input); }
  async listPolicies(input) { return { items: (await this.repository.listPolicies(input.subjectId)).map((policy) => this.toPolicyContract(policy)) }; }
  async updatePolicy(input) { this.validateRequest(input, ['requestId','scopeType','scopeId','metric','windowSeconds','hardLimit','effectiveAt']); const perform = async (client) => { const policies = await this.repository.listPolicies(input.scopeId, client); const current = policies.filter((p) => p.scopeType === input.scopeType && String(p.scopeId) === String(input.scopeId) && p.metric === input.metric).sort((a,b)=>b.version-a.version)[0]; if (input.baseVersion == null && current || input.baseVersion != null && Number(input.baseVersion) !== Number(current?.version ?? 0)) throw Object.assign(new Error('policy_version_conflict'), { statusCode: 409 }); const policy = await this.repository.upsertPolicy({ ...input, version: (current?.version ?? 0) + 1 }, client); await this.auditQuota(input, 'quota.policy.update', policy.policyId, { scopeType: policy.scopeType, scopeId: policy.scopeId, metric: policy.metric, version: policy.version }, client); return this.toPolicyContract(policy); }; return this.repository.withTransaction ? this.repository.withTransaction(perform) : perform(undefined); }
  async reconcile(input = {}) { const event = { ...input, requestId: input.requestId ?? randomUUID() }; const run = async (client) => { const result = await this.repository.reconcile(input, client); await this.auditQuota(event, 'quota.reconciliation.run', null, { checkpointName: result.checkpointName, scanned: result.scanned, repaired: result.repaired, state: result.state }, client); return result; }; return this.repository.withTransaction ? this.repository.withTransaction(run) : run(undefined); }
  async auditQuota(input, action, targetId, summary, client) { const event = { requestId: input.requestId, actorId: input.actorId ?? input.subjectId, action, targetType: action.includes('policy') ? 'quota_policy' : 'quota_reservation', targetId, policyVersion: input.policyVersion, summary }; if (this.repository.writeAudit) return this.repository.writeAudit(event, client); if (this.audit?.record) return this.audit.record(event); }
  toReservationContract(r) { return { reservationId: r.reservationId, requestId: r.requestId, taskId: r.taskId, attemptId: r.attemptId, reservedAmount: Number(r.amount), state: r.state === 'needs_review' ? 'reconciliation_required' : r.state, expiresAt: r.expiresAt }; }
  toPolicyContract(p) { return { policyId: p.policyId, scope: { type: p.scopeType, id: p.scopeId }, metric: p.metric, limit: Number(p.hardLimit), softLimit: p.softLimit == null ? undefined : Number(p.softLimit), window: p.windowSeconds === 3600 ? 'hour' : p.windowSeconds === 86400 ? 'day' : p.windowSeconds === 2592000 ? 'month' : 'rolling', version: String(p.version), effectiveAt: p.effectiveAt, failOpen: false }; }
  validateRequest(input, fields) { if (fields.some((field) => input?.[field] === undefined || input?.[field] === null || input?.[field] === '')) throw Object.assign(new Error('invalid_request'), { statusCode: 422 }); }
}

export function createQuotaAdapter(service) {
  return {
    preflight: (input) => service.preflight({ ...input, metric: input.metric ?? 'requests', amount: input.amount ?? 1 }),
    reserve: (input) => service.reserveQuota(input),
    settle: (input) => service.settleUsage(input),
    release: (input) => service.releaseQuota(input),
    queryUsage: (input) => service.queryUsage(input),
    reconcile: (input) => service.reconcile(input)
  };
}
