import { randomUUID } from 'node:crypto';
const now = () => new Date().toISOString();
const publicConfig = (c) => ({ providerConfigId: c.providerConfigId, id: c.providerConfigId, ownerId: c.ownerId, providerAccountId: c.providerAccountId, protocolType: c.protocolType, displayName: c.displayName, baseUrl: c.baseUrl, status: c.status, validationState: c.status === 'ready' ? 'active' : c.status, version: c.version, protocolVersion: c.protocolVersion, descriptorVersion: c.descriptorVersion, credentialStatus: c.credentialStatus, createdAt: c.createdAt, updatedAt: c.updatedAt });
export class InMemoryProviderConfigRepository {
  configs = new Map(); catalogs = new Map(); policies = new Map(); refreshes = new Map();
  async list(ownerId) { return [...this.configs.values()].filter((x) => x.ownerId === ownerId && x.status !== 'revoked').map(publicConfig); }
  async get(id) { const c = this.configs.get(id); return c ? { ...c } : undefined; }
  async create(input) { const duplicate = [...this.configs.values()].find((x) => x.ownerId === input.ownerId && x.requestId === input.requestId); if (duplicate) return publicConfig(duplicate); const c = { ...input, providerConfigId: randomUUID(), version: '1', status: 'draft', credentialStatus: 'configured', protocolVersion: input.protocolVersion ?? 'v1', descriptorVersion: null, createdAt: now(), updatedAt: now() }; this.configs.set(c.providerConfigId, c); return publicConfig(c); }
  async update(id, input) { const c = this.configs.get(id); if (!c || c.version !== String(input.baseVersion)) return undefined; Object.assign(c, input, { version: String(Number(c.version) + 1), status: 'draft', updatedAt: now() }); delete c.baseVersion; return publicConfig(c); }
  async state(id, version, status, descriptorVersion) { const c = this.configs.get(id); if (!c || c.version !== String(version)) return undefined; Object.assign(c, { status, descriptorVersion: descriptorVersion ?? c.descriptorVersion, version: String(Number(c.version) + 1), updatedAt: now() }); return publicConfig(c); }
  async revoke(id, version) { return this.state(id, version, 'revoked'); }
  async getCatalog(id) { return this.catalogs.get(id); }
  async replaceCatalog(id, entries) { const previous = this.catalogs.get(id); const catalog = { providerConfigId: id, catalogVersion: String(Number(previous?.catalogVersion ?? 0) + 1), refreshedAt: now(), status: 'fresh', items: entries.map((x) => ({ ...x, providerConfigId: id, catalogVersion: String(Number(previous?.catalogVersion ?? 0) + 1), sourceDigest: `${x.modelId}:${x.taskModes.join(',')}` })) }; this.catalogs.set(id, catalog); return catalog; }
  async markCatalog(id, status) { const c = this.catalogs.get(id); if (c) c.status = status; }
  async listPolicies(id) { return [...this.policies.values()].filter((x) => x.providerConfigId === id); }
  async updatePolicy(id, input) { const key = `${id}:${input.modelId}`; const old = this.policies.get(key); if (old && old.policyVersion !== String(input.baseVersion)) return undefined; const policy = { providerConfigId: id, modelId: input.modelId, enabled: Boolean(input.enabled), assignedCapabilities: input.assignedCapabilities ?? [], defaultFor: input.defaultFor ?? [], policyVersion: String(Number(old?.policyVersion ?? 0) + 1), classificationSource: 'user', outputSpec: input.outputSpec ?? {}, pricing: input.pricing ?? {} }; this.policies.set(key, policy); return policy; }
}
export { publicConfig };

export class PostgresProviderConfigRepository {
  constructor(pool) { this.pool = pool; }
  row(r) { return r && { providerConfigId: r.provider_config_id, ownerId: r.owner_id, providerAccountId: r.provider_account_id, protocolType: r.protocol_type, displayName: r.display_name, baseUrl: r.base_url, status: r.status, version: String(r.version), protocolVersion: r.protocol_version, descriptorVersion: r.descriptor_version, credentialStatus: r.credential_status, requestId: r.request_id, createdAt: r.created_at.toISOString(), updatedAt: r.updated_at.toISOString() }; }
  async list(ownerId) { const { rows } = await this.pool.query('SELECT * FROM provider_configs WHERE owner_id=$1 AND status<>$2 ORDER BY created_at DESC', [ownerId, 'revoked']); return rows.map((r) => publicConfig(this.row(r))); }
  async get(id) { const { rows } = await this.pool.query('SELECT * FROM provider_configs WHERE provider_config_id=$1', [id]); return this.row(rows[0]); }
  async create(input) { const { rows } = await this.pool.query('INSERT INTO provider_configs(provider_config_id,owner_id,provider_account_id,protocol_type,display_name,base_url,status,protocol_version,request_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) ON CONFLICT(owner_id,request_id) DO UPDATE SET updated_at=provider_configs.updated_at RETURNING *', [randomUUID(), input.ownerId, input.providerAccountId, input.protocolType, input.displayName, input.baseUrl, 'draft', input.protocolVersion ?? 'v1', input.requestId]); return publicConfig(this.row(rows[0])); }
  async update(id, input) { const { rows } = await this.pool.query('UPDATE provider_configs SET display_name=COALESCE($3,display_name),base_url=COALESCE($4,base_url),protocol_type=COALESCE($5,protocol_type),status=\'draft\',version=version+1,updated_at=now() WHERE provider_config_id=$1 AND version=$2 RETURNING *', [id, input.baseVersion, input.displayName, input.baseUrl, input.protocolType]); return rows[0] && publicConfig(this.row(rows[0])); }
  async state(id, version, status, descriptorVersion) { const { rows } = await this.pool.query('UPDATE provider_configs SET status=$3,descriptor_version=COALESCE($4,descriptor_version),version=version+1,updated_at=now() WHERE provider_config_id=$1 AND version=$2 RETURNING *', [id, version, status, descriptorVersion ?? null]); return rows[0] && publicConfig(this.row(rows[0])); }
  async revoke(id, version) { return this.state(id, version, 'revoked'); }
  async getCatalog(id) { const { rows } = await this.pool.query('SELECT * FROM model_catalogs WHERE provider_config_id=$1 ORDER BY catalog_version DESC LIMIT 1', [id]); if (!rows[0]) return undefined; const entries = await this.pool.query('SELECT * FROM model_catalog_entries WHERE provider_config_id=$1 AND catalog_version=$2', [id, rows[0].catalog_version]); return { providerConfigId: id, catalogVersion: String(rows[0].catalog_version), status: rows[0].status, refreshedAt: rows[0].refreshed_at?.toISOString() ?? null, items: entries.rows.map((x) => ({ modelId: x.model_id, displayName: x.display_name, capabilitySummary: x.capability_summary, taskModes: x.task_modes, streaming: x.streaming, tools: x.tools, enabled: x.enabled, defaultEligible: x.default_eligible, sourceDigest: x.source_digest })) }; }
  async replaceCatalog(id, items) { const previous = await this.getCatalog(id); const version = String(Number(previous?.catalogVersion ?? 0) + 1); const client = await this.pool.connect(); try { await client.query('BEGIN'); await client.query('INSERT INTO model_catalogs(provider_config_id,catalog_version,status,refreshed_at) VALUES($1,$2,$3,now())', [id, version, 'fresh']); for (const x of items) await client.query('INSERT INTO model_catalog_entries(provider_config_id,catalog_version,model_id,display_name,capability_summary,task_modes,streaming,tools,enabled,default_eligible,source_digest) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)', [id, version, x.modelId, x.displayName, JSON.stringify(x.capabilitySummary), JSON.stringify(x.taskModes), x.streaming, x.tools, false, false, x.sourceDigest ?? x.modelId]); await client.query('COMMIT'); return this.getCatalog(id); } catch (e) { await client.query('ROLLBACK'); throw e; } finally { client.release(); } }
  async markCatalog(id, status) { await this.pool.query('UPDATE model_catalogs SET status=$2 WHERE provider_config_id=$1 AND catalog_version=(SELECT max(catalog_version) FROM model_catalogs WHERE provider_config_id=$1)', [id, status]); }
  async listPolicies(id) { const { rows } = await this.pool.query('SELECT * FROM model_policies WHERE provider_config_id=$1 ORDER BY model_id', [id]); return rows.map((x) => ({ providerConfigId: id, modelId: x.model_id, enabled: x.enabled, assignedCapabilities: x.assigned_capabilities, defaultFor: x.default_for, policyVersion: String(x.policy_version), classificationSource: x.classification_source, outputSpec: x.output_spec, pricing: x.pricing })); }
  async updatePolicy(id, input) { const { rows } = await this.pool.query('INSERT INTO model_policies(provider_config_id,model_id,enabled,assigned_capabilities,default_for,policy_version,classification_source,output_spec,pricing) VALUES($1,$2,$3,$4,$5,1,\'user\',$6,$7) ON CONFLICT(provider_config_id,model_id) DO UPDATE SET enabled=$3,assigned_capabilities=$4,default_for=$5,policy_version=model_policies.policy_version+1,output_spec=$6,pricing=$7 WHERE model_policies.policy_version=$8 RETURNING *', [id, input.modelId, input.enabled, JSON.stringify(input.assignedCapabilities ?? []), JSON.stringify(input.defaultFor ?? []), JSON.stringify(input.outputSpec ?? {}), JSON.stringify(input.pricing ?? {}), input.baseVersion ? Number(input.baseVersion) : 0]); const x = rows[0]; return x && { providerConfigId: id, modelId: x.model_id, enabled: x.enabled, assignedCapabilities: x.assigned_capabilities, defaultFor: x.default_for, policyVersion: String(x.policy_version), classificationSource: x.classification_source, outputSpec: x.output_spec, pricing: x.pricing }; }
}
