import { createHash, randomUUID } from 'node:crypto';
const digest = (value) => createHash('sha256').update(JSON.stringify(value)).digest('hex');
const exactVersion = /^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-[0-9A-Za-z.-]+)?(?:\+[0-9A-Za-z.-]+)?$/;
const binding = (input) => { const id = Object.hasOwn(input, 'capabilityProtocolId'); const version = Object.hasOwn(input, 'capabilityProtocolVersion'); if (id !== version || id && (typeof input.capabilityProtocolId !== 'string' || !input.capabilityProtocolId || typeof input.capabilityProtocolVersion !== 'string' || !exactVersion.test(input.capabilityProtocolVersion))) throw Object.assign(new Error('invalid_request'), { errorKey: 'invalid_request', statusCode: 422 }); };
export class ProviderConfigService {
  constructor({ repository, accountRepository, secretService, registry, egress, audit, profileDirectory }) { if (typeof egress?.validateTarget !== 'function') throw new TypeError('ProviderEgress.validateTarget required'); Object.assign(this, { repository, accountRepository, secretService, registry, egress, audit, profileDirectory }); }
  async requireProfile(ownerId, id, version) { if (!id && !version) return; if (!id || !version || !this.profileDirectory?.getActive || !await this.profileDirectory.getActive(ownerId, id, version)) throw Object.assign(new Error('protocol_unavailable'), { statusCode: 422 }); }
  async list(ownerId) { return { items: await this.repository.list(ownerId) }; }
  async create(input) { binding(input); const account = await this.accountRepository.getAccount(input.providerAccountId); if (!account || account.ownerId !== input.ownerId) throw Object.assign(new Error('provider_account_not_found'), { statusCode: 404 }); if (account.protocolType !== input.protocolType) throw Object.assign(new Error('protocol_mismatch'), { statusCode: 422 }); const adapter = this.registry.get(input.protocolType); await this.requireProfile(input.ownerId, input.capabilityProtocolId, input.capabilityProtocolVersion); await this.egress.validateTarget(input.baseUrl); return this.repository.withAuditedMutation((client) => this.repository.create({ ...input, requestId: input.requestId, protocolVersion: adapter.protocolVersion }, client), this.audit, (result) => ({ requestId: input.requestId, actorId: input.ownerId, action: 'provider.config.create', targetType: 'provider_config', targetId: result.providerConfigId, summary: { protocolType: result.protocolType, digest: digest({ displayName: result.displayName, baseUrl: result.baseUrl }) } })); }
  async update(id, input, ownerId) {
    binding(input);
    const current = await this.repository.get(id);
    if (!current || current.ownerId !== ownerId) throw Object.assign(new Error('provider_config_not_found'), { statusCode: 404 });
    if (current.version !== String(input.baseVersion)) throw Object.assign(new Error('version_conflict'), { statusCode: 409 });
    try {
      const account = await this.accountRepository.getAccount(current.providerAccountId);
      if (!account || account.ownerId !== ownerId || account.protocolType !== (input.protocolType ?? current.protocolType)) throw Object.assign(new Error('protocol_mismatch'), { errorKey: 'protocol_mismatch' });
      this.registry.get(input.protocolType ?? current.protocolType);
      await this.requireProfile(ownerId, input.capabilityProtocolId ?? current.capabilityProtocolId, input.capabilityProtocolVersion ?? current.capabilityProtocolVersion);
      if (input.baseUrl) await this.egress.validateTarget(input.baseUrl);
    } catch (error) {
      await this.repository.withAuditedMutation(async (client) => { const result = await this.repository.state(id, current.version, 'disabled', undefined, client); if (result) await this.repository.markCatalog(id, 'stale', client); return result; }, this.audit, () => ({ requestId: input.requestId, actorId: ownerId, action: 'provider.config.update', targetType: 'provider_config', targetId: id, result: 'failed', summary: { errorClass: error.errorKey ?? 'invalid_request' } }));
      throw error;
    }
    return this.repository.withAuditedMutation(async (client) => { const result = await this.repository.update(id, input, client); if (!result) throw Object.assign(new Error('version_conflict'), { statusCode: 409 }); await this.repository.markCatalog(id, 'stale', client); return result; }, this.audit, (result) => ({ requestId: input.requestId, actorId: ownerId, action: 'provider.config.update', targetType: 'provider_config', targetId: id, summary: { version: result.version } }));
  }
  async remove(id, ownerId, requestId) { const current = await this.repository.get(id); if (!current || current.ownerId !== ownerId) throw Object.assign(new Error('provider_config_not_found'), { statusCode: 404 }); return this.repository.withAuditedMutation((client) => this.repository.revoke(id, current.version, client), this.audit, () => ({ requestId, actorId: ownerId, action: 'provider.config.delete', targetType: 'provider_config', targetId: id, summary: {} })); }
  async validate(id, ownerId, requestId, signal) {
    const config = await this.repository.get(id);
    if (!config || config.ownerId !== ownerId) throw Object.assign(new Error('provider_config_not_found'), { statusCode: 404 });
    const validating = await this.repository.stateWithAudit(id, config.version, 'validating', undefined, this.audit, () => ({ requestId, actorId: ownerId, action: 'provider.config.validate.start', targetType: 'provider_config', targetId: id }));
    if (!validating) throw Object.assign(new Error('version_conflict'), { statusCode: 409 });
    try {
      const adapter = this.registry.get(config.protocolType);
      const account = await this.accountRepository.getAccount(config.providerAccountId);
      if (!account || account.ownerId !== ownerId || account.protocolType !== config.protocolType || account.status === 'disabled' || account.status === 'revoked') throw Object.assign(new Error('provider_account_disabled'), { errorKey: 'provider_account_disabled' });
      await this.egress.validateTarget(config.baseUrl);
      const handle = await this.secretService.resolve({ secretRef: account._secretRef, purpose: 'provider-account', subjectId: ownerId });
      const descriptor = await adapter.validate({ config, credential: await handle.read(), egress: this.egress, signal });
      const provider = await this.repository.stateWithAudit(id, validating.version, 'ready', descriptor.descriptorVersion, this.audit, () => ({ requestId, actorId: ownerId, action: 'provider.config.validate', targetType: 'provider_config', targetId: id, summary: { descriptorVersion: descriptor.descriptorVersion } }));
      if (!provider) throw Object.assign(new Error('version_conflict'), { statusCode: 409 });
      return { provider, descriptor };
    } catch (error) {
      await this.repository.stateWithAudit(id, validating.version, 'disabled', undefined, this.audit, () => ({ requestId, actorId: ownerId, action: 'provider.config.validate', targetType: 'provider_config', targetId: id, result: 'failed', summary: { errorClass: error.errorKey ?? 'upstream_unavailable' } }));
      await this.repository.markCatalog(id, 'stale');
      throw Object.assign(new Error(error.errorKey ?? error.message ?? 'upstream_unavailable'), { statusCode: error.statusCode ?? 422 });
    }
  }
  async models(id, ownerId) { const c = await this.repository.get(id); if (!c || c.ownerId !== ownerId) throw Object.assign(new Error('provider_config_not_found'), { statusCode: 404 }); return (await this.repository.getCatalog(id)) ?? { providerConfigId: id, catalogVersion: '0', status: 'unavailable', items: [], refreshedAt: null }; }
  async refresh(id, ownerId, requestId, signal) { const c = await this.repository.get(id); if (!c || c.ownerId !== ownerId) throw Object.assign(new Error('provider_config_not_found'), { statusCode: 404 }); if (c.status !== 'ready') throw Object.assign(new Error('provider_config_disabled'), { statusCode: 422 }); const adapter = this.registry.get(c.protocolType); const account = await this.accountRepository.getAccount(c.providerAccountId); if (!account || account.ownerId !== ownerId || account.status === 'disabled' || account.status === 'revoked') throw Object.assign(new Error('provider_account_disabled'), { statusCode: 422 }); try { await this.egress.validateTarget(c.baseUrl); const handle = await this.secretService.resolve({ secretRef: account._secretRef, purpose: 'provider-account', subjectId: ownerId }); const items = await adapter.listModels({ config: c, credential: await handle.read(), egress: this.egress, signal }); const catalog = await this.repository.withAuditedMutation((client) => this.repository.replaceCatalog(id, items, client, c.version), this.audit, (result) => ({ requestId, actorId: ownerId, action: 'provider.models.refresh', targetType: 'provider_config', targetId: id, summary: { catalogVersion: result.catalogVersion, count: items.length } })); return { requestId, status: 'completed', ...catalog }; } catch (error) { if (error.errorKey !== 'version_conflict') await this.repository.withAuditedMutation(async (client) => { const current = await this.repository.get(id, client); if (current?.version === c.version) await this.repository.markCatalog(id, 'stale', client); return current; }, this.audit, () => ({ requestId, actorId: ownerId, action: 'provider.models.refresh', targetType: 'provider_config', targetId: id, result: 'failed', summary: { errorClass: error.errorKey ?? 'upstream_unavailable' } })); throw Object.assign(new Error(error.errorKey ?? 'upstream_unavailable'), { errorKey: error.errorKey ?? 'upstream_unavailable', statusCode: error.statusCode ?? 422 }); } }
  async policies(id, ownerId) { const c = await this.repository.get(id); if (!c || c.ownerId !== ownerId) throw Object.assign(new Error('provider_config_not_found'), { statusCode: 404 }); return { items: await this.repository.listPolicies(id) }; }
  async policy(id, ownerId, input) { const c = await this.repository.get(id); if (!c || c.ownerId !== ownerId) throw Object.assign(new Error('provider_config_not_found'), { statusCode: 404 }); const catalog = await this.repository.getCatalog(id); const model = catalog?.items.find((x) => x.modelId === input.modelId); if (!model) throw Object.assign(new Error('model_not_found'), { statusCode: 422 }); if (input.enabled && !model.taskModes.includes('text.chat')) throw Object.assign(new Error('capability_mismatch'), { statusCode: 422 }); return this.repository.withAuditedMutation(async (client) => { const result = await this.repository.updatePolicy(id, input, client); if (!result) throw Object.assign(new Error('version_conflict'), { statusCode: 409 }); return result; }, this.audit, (result) => ({ requestId: input.requestId, actorId: ownerId, action: 'provider.model_policy.update', targetType: 'provider_config', targetId: id, summary: { modelId: input.modelId, policyVersion: result.policyVersion } })); }
}
