import { createHash, randomUUID } from 'node:crypto';
const digest = (value) => createHash('sha256').update(JSON.stringify(value)).digest('hex');
export class ProviderConfigService {
  constructor({ repository, accountRepository, secretService, registry, egress, audit }) { Object.assign(this, { repository, accountRepository, secretService, registry, egress, audit }); }
  async list(ownerId) { return { items: await this.repository.list(ownerId) }; }
  async create(input) { const account = await this.accountRepository.getAccount(input.providerAccountId); if (!account || account.ownerId !== input.ownerId) throw Object.assign(new Error('provider_account_not_found'), { statusCode: 404 }); if (account.protocolType !== input.protocolType) throw Object.assign(new Error('protocol_mismatch'), { statusCode: 422 }); const adapter = this.registry.get(input.protocolType); const result = await this.repository.create({ ...input, requestId: input.requestId, adapterVersion: adapter.protocolVersion }); await this.audit?.record({ requestId: input.requestId, actorId: input.ownerId, action: 'provider.config.create', targetType: 'provider_config', targetId: result.providerConfigId, summary: { protocolType: result.protocolType, digest: digest({ displayName: result.displayName, baseUrl: result.baseUrl }) } }); return result; }
  async update(id, input, ownerId) { const current = await this.repository.get(id); if (!current || current.ownerId !== ownerId) throw Object.assign(new Error('provider_config_not_found'), { statusCode: 404 }); const result = await this.repository.update(id, input); if (!result) throw Object.assign(new Error('version_conflict'), { statusCode: 409 }); await this.audit?.record({ requestId: input.requestId, actorId: ownerId, action: 'provider.config.update', targetType: 'provider_config', targetId: id, summary: { version: result.version } }); return result; }
  async remove(id, ownerId, requestId) { const current = await this.repository.get(id); if (!current || current.ownerId !== ownerId) throw Object.assign(new Error('provider_config_not_found'), { statusCode: 404 }); const result = await this.repository.revoke(id, current.version); await this.audit?.record({ requestId, actorId: ownerId, action: 'provider.config.delete', targetType: 'provider_config', targetId: id, summary: {} }); return result; }
  async validate(id, ownerId, requestId, signal) { const config = await this.repository.get(id); if (!config || config.ownerId !== ownerId) throw Object.assign(new Error('provider_config_not_found'), { statusCode: 404 }); const adapter = this.registry.get(config.protocolType); const account = await this.accountRepository.getAccount(config.providerAccountId); if (!account || account.ownerId !== ownerId) throw Object.assign(new Error('provider_account_not_found'), { statusCode: 404 }); const validating = await this.repository.state(id, config.version, 'validating'); if (!validating) throw Object.assign(new Error('version_conflict'), { statusCode: 409 }); const validationVersion = validating.version; try { const handle = await this.secretService.resolve({ secretRef: account._secretRef, purpose: 'provider-account', subjectId: ownerId }); const descriptor = await adapter.validate({ config, credential: await handle.read(), egress: this.egress, signal }); const provider = await this.repository.state(id, validationVersion, 'ready', descriptor.descriptorVersion); await this.audit?.record({ requestId, actorId: ownerId, action: 'provider.config.validate', targetType: 'provider_config', targetId: id, summary: { result: 'succeeded', descriptorVersion: descriptor.descriptorVersion } }); return { provider, descriptor }; } catch (error) { await this.repository.state(id, validationVersion, error.errorKey === 'authentication_failed' ? 'disabled' : 'error'); await this.audit?.record({ requestId, actorId: ownerId, action: 'provider.config.validate', targetType: 'provider_config', targetId: id, result: 'failed', summary: { errorClass: error.errorKey ?? 'upstream_unavailable' } }); throw Object.assign(new Error(error.errorKey ?? 'upstream_unavailable'), { statusCode: 422 }); } }
  async models(id, ownerId) { const c = await this.repository.get(id); if (!c || c.ownerId !== ownerId) throw Object.assign(new Error('provider_config_not_found'), { statusCode: 404 }); return (await this.repository.getCatalog(id)) ?? { providerConfigId: id, catalogVersion: '0', status: 'unavailable', items: [], refreshedAt: null }; }
  async refresh(id, ownerId, requestId, signal) { const c = await this.repository.get(id); if (!c || c.ownerId !== ownerId) throw Object.assign(new Error('provider_config_not_found'), { statusCode: 404 }); const adapter = this.registry.get(c.protocolType); const account = await this.accountRepository.getAccount(c.providerAccountId); try { const handle = await this.secretService.resolve({ secretRef: account._secretRef, purpose: 'provider-account', subjectId: ownerId }); const items = await adapter.listModels({ config: c, credential: await handle.read(), egress: this.egress, signal }); const catalog = await this.repository.replaceCatalog(id, items); await this.audit?.record({ requestId, actorId: ownerId, action: 'provider.models.refresh', targetType: 'provider_config', targetId: id, summary: { catalogVersion: catalog.catalogVersion, count: items.length } }); return { requestId, status: 'completed', ...catalog }; } catch (error) { await this.repository.markCatalog(id, 'stale'); await this.audit?.record({ requestId, actorId: ownerId, action: 'provider.models.refresh', targetType: 'provider_config', targetId: id, result: 'failed', summary: { errorClass: error.errorKey ?? 'upstream_unavailable' } }); throw Object.assign(new Error(error.errorKey ?? 'upstream_unavailable'), { statusCode: 422 }); } }
  async policies(id, ownerId) { const c = await this.repository.get(id); if (!c || c.ownerId !== ownerId) throw Object.assign(new Error('provider_config_not_found'), { statusCode: 404 }); return { items: await this.repository.listPolicies(id) }; }
  async policy(id, ownerId, input) { const c = await this.repository.get(id); if (!c || c.ownerId !== ownerId) throw Object.assign(new Error('provider_config_not_found'), { statusCode: 404 }); const catalog = await this.repository.getCatalog(id); const model = catalog?.items.find((x) => x.modelId === input.modelId); if (!model) throw Object.assign(new Error('model_not_found'), { statusCode: 422 }); if (input.enabled && !model.taskModes.includes('text.chat')) throw Object.assign(new Error('capability_mismatch'), { statusCode: 422 }); const result = await this.repository.updatePolicy(id, input); if (!result) throw Object.assign(new Error('version_conflict'), { statusCode: 409 }); await this.audit?.record({ requestId: input.requestId, actorId: ownerId, action: 'provider.model_policy.update', targetType: 'provider_config', targetId: id, summary: { modelId: input.modelId, policyVersion: result.policyVersion } }); return result; }
}
