export const installStates = Object.freeze(['discovered', 'pending_review', 'approved', 'installed', 'active', 'update_pending', 'health_check_failed', 'rolled_back', 'uninstall_requested', 'uninstalled']);

export class AppRuntimeService {
  constructor({ repository, audit, healthCheck = async () => true } = {}) { this.repository = repository; this.audit = audit; this.healthCheck = healthCheck; this.locks = new Set(); }
  async #getPublic(appId, version, build) { const app = await this.repository.getApp(appId, version, build); if (!app || !['official', 'approved'].includes(app.catalogState)) throw Object.assign(new Error('app_not_available'), { statusCode: 404 }); return app; }
  async install({ subjectId, appId, version, build, developerTest = false, actorId }) { const lock = `${subjectId}:${appId}`; if (this.locks.has(lock)) throw Object.assign(new Error('app_install_conflict'), { statusCode: 409 }); this.locks.add(lock); try { const app = await this.repository.getApp(appId, version, build); if (!app || (!developerTest && !['official', 'approved'].includes(app.catalogState))) throw Object.assign(new Error('app_not_available'), { statusCode: 404 }); const current = await this.repository.getInstall(subjectId, appId); if (current?.version === app.version && current.build === app.build && current.state !== 'uninstalled') return current; const record = { subjectId, appId, version: app.version, build: app.build, state: 'installed', previous: current?.state === 'active' ? current : null, dataRetained: true, installedAt: new Date().toISOString() }; await this.repository.saveInstall(record); const healthy = await this.healthCheck({ app, record }); if (!healthy) { record.state = current?.state === 'active' ? 'rolled_back' : 'health_check_failed'; record.activeVersion = current?.version ?? null; await this.repository.saveInstall(record); throw Object.assign(new Error('health_check_failed'), { statusCode: 422, rollback: record }); } record.state = 'active'; await this.repository.saveInstall(record); await this.audit?.record({ actorId, action: developerTest ? 'app.test_install' : 'app.install', targetType: 'app_install', targetId: appId, summary: { version: app.version, build: app.build, state: record.state } }); return record; } finally { this.locks.delete(lock); } }
  async launch({ subjectId, appId }) { const record = await this.repository.getInstall(subjectId, appId); if (!record || !['installed', 'active'].includes(record.state)) throw Object.assign(new Error('app_not_installed'), { statusCode: 409 }); record.state = 'active'; await this.repository.saveInstall(record); return record; }
  async update(input) { return this.install({ ...input, developerTest: false }); }
  async uninstall({ subjectId, appId, actorId }) { const record = await this.repository.getInstall(subjectId, appId); if (!record) throw Object.assign(new Error('app_not_installed'), { statusCode: 404 }); const app = await this.repository.getApp(appId, record.version, record.build); if (app?.uninstallPolicy === 'protected') throw Object.assign(new Error('app_uninstall_forbidden'), { statusCode: 403 }); record.state = 'uninstalled'; record.dataRetained = true; await this.repository.saveInstall(record); await this.audit?.record({ actorId, action: 'app.uninstall', targetType: 'app_install', targetId: appId, summary: { dataRetained: true } }); return record; }
  async health({ subjectId, appId }) { const record = await this.repository.getInstall(subjectId, appId); if (!record) throw Object.assign(new Error('app_not_installed'), { statusCode: 404 }); return { appId, state: record.state, healthy: record.state === 'active', version: record.version, build: record.build }; }
}
