import test from 'node:test';
import assert from 'node:assert/strict';
import { buildServer } from '../../apps/api/src/server.mjs';
import { InMemoryProviderRepository } from '../../src/provider/repository.mjs';
import { InMemoryProviderConfigRepository } from '../../src/provider-config/repository.mjs';
import { InMemoryAiTaskRepository } from '../../src/ai-task/repository.mjs';
import { InMemorySecretService } from '../../src/security/secret-service.mjs';

test('public ProviderConfig to text task API supports explicit refresh, idempotency, SSE resume and artifact authorization', async () => {
  const providerRepository = new InMemoryProviderRepository();
  const providerConfigRepository = new InMemoryProviderConfigRepository();
  const aiTaskRepository = new InMemoryAiTaskRepository();
  const secretService = new InMemorySecretService();
  const fixtureAdapter = { protocolType: 'openai-compatible', protocolVersion: 'v1', descriptorVersion: 'text.v1', taskModes: ['text.chat'], streamingText: true, cancellation: true, modelListing: true, async validate() { return { descriptorVersion: 'text.v1', inputs: ['text'], outputs: ['text'], taskModes: ['text.chat'], streaming: { text: true }, cancellation: true, modelCatalog: 'remote' }; }, async listModels() { return [{ modelId: 'fixture-text-model', displayName: 'Fixture model', taskModes: ['text.chat'], streaming: true, tools: false, capabilitySummary: { text: true } }]; } };
  const app = buildServer({ logger: false, providerRepository, providerConfigRepository, aiTaskRepository, secretService, providerAdapters: [fixtureAdapter], providerRunner: async function* () { yield 'hello'; yield ' world'; }, providerEgress: {}, quotaAdapter: { preflight: async () => ({ allowed: true, reservationRef: 'fixture-reservation' }) } });
  const bootstrap = await app.inject({ method: 'POST', url: '/api/v1/identity/admin/bootstrap', payload: { displayName: 'Task Owner', credential: 'owner-password' } });
  const ownerId = bootstrap.json().principalId;
  const token = bootstrap.json().sessionId;
  const auth = { authorization: `Bearer ${token}` };
  const accountRes = await app.inject({ method: 'POST', url: '/api/v1/provider/accounts', headers: auth, payload: { protocolType: 'openai-compatible', displayName: 'Fixture', credential: 'fixture-secret', scope: { endpoint: 'https://provider.invalid/v1' } } });
  assert.equal(accountRes.statusCode, 201);
  const account = accountRes.json();
  const configRes = await app.inject({ method: 'POST', url: '/api/v1/provider/configs', headers: auth, payload: { requestId: 'config-create-1', providerAccountId: account.accountId, protocolType: 'openai-compatible', displayName: 'Fixture config', baseUrl: 'https://provider.invalid/v1' } });
  assert.equal(configRes.statusCode, 201, configRes.body);
  const config = configRes.json();
  assert.equal(config.status, 'draft');
  const validated = await app.inject({ method: 'POST', url: `/api/v1/provider/configs/${config.id}/validate`, headers: auth, payload: { requestId: 'validate-1' } });
  assert.equal(validated.statusCode, 200, validated.body);
  const noImplicitRefresh = await app.inject({ method: 'GET', url: `/api/v1/provider/configs/${config.id}/models`, headers: auth });
  assert.equal(noImplicitRefresh.json().catalogVersion, '0');
  const refreshed = await app.inject({ method: 'POST', url: `/api/v1/provider/configs/${config.id}/models`, headers: auth, payload: { requestId: 'refresh-1' } });
  assert.equal(refreshed.statusCode, 200, refreshed.body);
  const modelId = 'fixture-text-model';
  const configModels = refreshed.json();
  assert.equal(configModels.items[0].modelId, modelId);
  const policy = await app.inject({ method: 'POST', url: `/api/v1/provider/configs/${config.id}/model-policies`, headers: auth, payload: { requestId: 'policy-1', modelId, enabled: true, assignedCapabilities: ['text'], defaultFor: [], baseVersion: '0' } });
  assert.equal(policy.statusCode, 200, policy.body);
  const input = { requestId: 'task-request-1', target: 'text', intent: 'text.chat', input: { text: 'hello' }, options: { providerConfigId: config.id, modelId } };
  const submitted = await app.inject({ method: 'POST', url: '/api/v1/ai-tasks', headers: auth, payload: input });
  assert.equal(submitted.statusCode, 202, submitted.body);
  const receipt = submitted.json();
  const duplicate = await app.inject({ method: 'POST', url: '/api/v1/ai-tasks', headers: auth, payload: input });
  assert.equal(duplicate.json().taskId, receipt.taskId);
  await new Promise((resolve) => setTimeout(resolve, 20));
  const snapshot = await app.inject({ method: 'GET', url: `/api/v1/ai-tasks/${receipt.taskId}`, headers: auth });
  assert.equal(snapshot.json().status, 'succeeded');
  assert.equal(snapshot.json().text, 'hello world');
  const events = await app.inject({ method: 'GET', url: `/api/v1/ai-tasks/${receipt.taskId}/events`, headers: auth });
  assert.match(events.headers['content-type'], /text\/event-stream/);
  const firstEvent = await aiTaskRepository.listEvents(receipt.taskId, 0);
  const resumed = await app.inject({ method: 'GET', url: `/api/v1/ai-tasks/${receipt.taskId}/events`, headers: { ...auth, 'last-event-id': String(firstEvent[0].sequence) } });
  assert.doesNotMatch(resumed.body, new RegExp(`id: ${firstEvent[0].sequence}\\n`));
  const artifactId = snapshot.json().artifactIds[0];
  const artifact = await app.inject({ method: 'GET', url: `/api/v1/artifacts/${artifactId}`, headers: auth });
  assert.equal(artifact.json().content, 'hello world');
  const strangerId = '00000000-0000-4000-8000-000000000099';
  const strangerKey = await app.inject({ method: 'POST', url: '/api/v1/secret/api-keys', headers: auth, payload: { name: 'stranger', scopes: ['artifact.read'], ownerId: strangerId } });
  const denied = await app.inject({ method: 'GET', url: `/api/v1/artifacts/${artifactId}`, headers: { authorization: `ApiKey ${strangerKey.json().secret}` } });
  assert.equal(denied.statusCode, 404);
  assert.equal(ownerId, config.ownerId);
  await app.close();
});
