import test from 'node:test';
import assert from 'node:assert/strict';
import { generateKeyPairSync, randomUUID, sign, createHash } from 'node:crypto';
import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { chromium } from '@playwright/test';
import Fastify from '../../apps/api/node_modules/fastify/fastify.js';
import { registerPackageRoutes } from '../../apps/api/src/package-routes.mjs';
import { DiskPackageStore, canonicalJson } from '../../src/apps/package-service.mjs';

test('deployment route and bridge bind authenticated subject and session', async (t) => {
  const dir = await mkdtemp(join(tmpdir(), 'dgos-package-routes-'));
  const app = Fastify({ logger: false });
  t.after(async () => { await app.close(); await rm(dir, { recursive: true, force: true }); });
  const { privateKey, publicKey } = generateKeyPairSync('ed25519');
  const appId = 'com.example.route'; const owner = randomUUID(); const stranger = randomUUID();
  const manifest = { format: 'dgos-app/v1', appId, version: '1.0.0', build: 1, releaseChannel: 'stable', minRuntimeVersion: '1.0.0', dataVersion: 1, name: { 'zh-CN': '测试', 'en-US': 'Test' }, description: { 'zh-CN': '测试', 'en-US': 'Test' }, category: 'productivity', icon: 'icon.svg', defaultWindow: { width: 800, height: 600 }, entrypoints: { web: 'index.html' }, permissions: ['dgos.aiTask.get', 'dgos.model.resolve'], capabilityAllowlist: ['dgos.aiTask.get', 'dgos.model.resolve'], trustLevel: 'standard', uninstallPolicy: 'user-removable', backgroundPolicy: 'release' };
  const files = { 'index.html': Buffer.from('<html>ok</html>').toString('base64'), 'icon.svg': Buffer.from('<svg/>').toString('base64') };
  const resourceDigests = Object.fromEntries(Object.entries(files).map(([path, content]) => [path, `sha256:${createHash('sha256').update(Buffer.from(content, 'base64')).digest('hex')}`]));
  const envelope = { manifest, files, resourceDigests, keyId: 'fixture', signature: sign(null, Buffer.from(canonicalJson({ manifest, resourceDigests })), privateKey).toString('base64') };
  let calls = 0; let revoked = false;
  const service = registerPackageRoutes(app, { store: new DiskPackageStore(dir), trustRoots: new Map([['fixture', { publicKey, source: 'official' }]]), requireScope: async (request) => { if (!request.headers['x-subject']) throw Object.assign(new Error('session_invalid'), { statusCode: 401 }); return { subjectId: request.headers['x-subject'], sessionId: request.headers['x-session'] }; }, validateCsrf: async () => {}, validateLaunchSession: async () => !revoked, bridgeAuthorize: async () => true, bridgeHandlers: { 'dgos.aiTask.get': async () => { calls += 1; return { taskId: 'fixture-task', status: 'running', text: undefined, error: undefined, artifactIds: [], defaults: { temperature: 0.7 } }; }, 'dgos.model.resolve': async () => ({ providerConfigId: 'provider-1', modelId: 'model-1', intent: 'text.chat', descriptorVersion: 'text.v1', profile: 'chat.completions', workflow: 'text.chat', defaults: { temperature: 0.7 }, limits: {}, uiSchemas: {}, assets: {}, protocolId: undefined }) } });
  await app.ready();
  await service.submit({ ...envelope, requestId: randomUUID() });
  const installed = await service.install({ subjectId: owner, appId, version: '1.0.0', build: 1, releaseChannel: 'stable' });
  const headers = { 'x-subject': owner, 'x-session': 'session-1' };
  const deployment = await app.inject({ method: 'GET', url: `/api/v1/apps/${appId}/deployment`, headers });
  assert.equal(deployment.statusCode, 200);
  assert.equal(deployment.json().versionNumber, installed.versionNumber);
  assert.equal(deployment.json().activeRelease.digest, installed.digest);
  assert.equal((await app.inject({ method: 'GET', url: '/api/v1/apps/installations', headers })).statusCode, 404);
  assert.equal((await app.inject({ method: 'GET', url: `/api/v1/apps/${appId}/deployment?subjectId=${owner}`, headers: { ...headers, 'x-subject': stranger } })).statusCode, 404);
  const launch = (await app.inject({ method: 'POST', url: `/api/v1/apps/${appId}/launch`, headers })).json();
  assert.equal((await app.inject({ method: 'GET', url: launch.entrypoint, headers })).statusCode, 200);
  const script = await app.inject({ method: 'GET', url: launch.entrypoint });
  assert.equal(script.statusCode, 200);
  assert.equal(script.headers['access-control-allow-origin'], 'null');
  assert.equal(script.headers['cross-origin-resource-policy'], 'cross-origin');
  assert.equal((await app.inject({ method: 'GET', url: `/api/v1/apps/${appId}/resources/unknown.js?launchTicket=${new URL(launch.entrypoint, 'http://fixture').searchParams.get('launchTicket')}` })).statusCode, 403);
  assert.equal((await app.inject({ method: 'GET', url: `/api/v1/apps/${appId}/resources/index.html` })).statusCode, 401);
  const requestId = randomUUID();
  const payload = { instanceId: launch.instanceId, requestId, capability: 'dgos.aiTask.get', input: { taskId: 'fixture-task' } };
  const first = await app.inject({ method: 'POST', url: `/api/v1/apps/${appId}/bridge`, headers, payload });
  assert.equal(first.statusCode, 200);
  assert.deepEqual(first.json(), { taskId: 'fixture-task', status: 'running', artifactIds: [], defaults: { temperature: 0.7 } });
  assert.equal((await app.inject({ method: 'POST', url: `/api/v1/apps/${appId}/bridge`, headers, payload })).statusCode, 200);
  assert.equal(calls, 1);
  const durable = await service.store.readReceipt(owner, appId, launch.instanceId, requestId);
  assert.deepEqual({ subjectId: durable.subjectId, sessionId: durable.sessionId, appId: durable.appId, instanceId: durable.instanceId, requestId: durable.requestId, capability: durable.capability, packageDigest: durable.packageDigest, state: durable.state }, { subjectId: owner, sessionId: 'session-1', appId, instanceId: launch.instanceId, requestId, capability: 'dgos.aiTask.get', packageDigest: installed.digest, state: 'completed' });
  assert.deepEqual(durable.result, { taskId: 'fixture-task', status: 'running', artifactIds: [], defaults: { temperature: 0.7 } });
  const resolved = await app.inject({ method: 'POST', url: `/api/v1/apps/${appId}/bridge`, headers, payload: { instanceId: launch.instanceId, requestId: randomUUID(), capability: 'dgos.model.resolve', input: { providerConfigId: 'provider-1', modelId: 'model-1', intent: 'text.chat' } } });
  assert.equal(resolved.statusCode, 200);
  assert.deepEqual(resolved.json().defaults, { temperature: 0.7 });
  assert.equal(Object.hasOwn(resolved.json(), 'protocolId'), false);
  assert.equal((await app.inject({ method: 'POST', url: `/api/v1/apps/${appId}/bridge`, headers: { ...headers, 'x-session': 'session-2' }, payload })).statusCode, 403);
  assert.equal((await app.inject({ method: 'POST', url: `/api/v1/apps/${appId}/bridge`, headers, payload: { ...payload, input: { taskId: 'other' } } })).statusCode, 409);
  const freshRequestId = randomUUID();
  await service.store.writeReceipt(owner, appId, launch.instanceId, freshRequestId, { ...durable, requestId: freshRequestId, state: 'prepared' });
  assert.equal((await app.inject({ method: 'POST', url: `/api/v1/apps/${appId}/bridge`, headers, payload: { ...payload, requestId: freshRequestId } })).statusCode, 409);
  assert.equal(calls, 1);
  revoked = true;
  assert.equal((await app.inject({ method: 'GET', url: launch.entrypoint })).statusCode, 403);
  revoked = false;
  const updated = { ...manifest, version: '1.0.1', build: 2 };
  await service.submit({ manifest: updated, files, resourceDigests, keyId: 'fixture', requestId: randomUUID(), signature: sign(null, Buffer.from(canonicalJson({ manifest: updated, resourceDigests })), privateKey).toString('base64') });
  await service.install({ subjectId: owner, appId, version: '1.0.1', build: 2, releaseChannel: 'stable', baseVersion: installed.versionNumber });
  assert.equal((await app.inject({ method: 'GET', url: launch.entrypoint })).statusCode, 403);
});

test('catalog review requires an explicit administrator role', async (t) => {
  const dir = await mkdtemp(join(tmpdir(), 'dgos-package-review-'));
  const app = Fastify({ logger: false });
  t.after(async () => { await app.close(); await rm(dir, { recursive: true, force: true }); });
  const { privateKey, publicKey } = generateKeyPairSync('ed25519');
  const owner = randomUUID();
  const manifest = { format: 'dgos-app/v1', appId: 'com.example.review', version: '1.0.0', build: 1, releaseChannel: 'stable', minRuntimeVersion: '1.0.0', dataVersion: 1, name: { 'zh-CN': '审核', 'en-US': 'Review' }, description: { 'zh-CN': '审核', 'en-US': 'Review' }, category: 'productivity', icon: 'icon.svg', defaultWindow: { width: 800, height: 600 }, entrypoints: { web: 'index.html' }, permissions: [], capabilityAllowlist: [], trustLevel: 'standard', uninstallPolicy: 'user-removable', backgroundPolicy: 'release' };
  const files = { 'index.html': Buffer.from('<html>ok</html>').toString('base64'), 'icon.svg': Buffer.from('<svg/>').toString('base64') };
  const resourceDigests = Object.fromEntries(Object.entries(files).map(([path, content]) => [path, `sha256:${createHash('sha256').update(Buffer.from(content, 'base64')).digest('hex')}`]));
  const envelope = { manifest, files, resourceDigests, keyId: 'fixture', signature: sign(null, Buffer.from(canonicalJson({ manifest, resourceDigests })), privateKey).toString('base64') };
  let actor = { subjectId: owner, sessionId: 'session', authMethod: 'session' };
  const service = registerPackageRoutes(app, {
    store: new DiskPackageStore(dir),
    trustRoots: new Map([['fixture', { publicKey, source: 'developer' }]]),
    requireScope: async () => actor,
    validateCsrf: async () => {},
  });
  await app.ready();
  const submitted = await service.submit({ ...envelope, requestId: randomUUID() });
  const body = { version: submitted.version, build: submitted.build, releaseChannel: submitted.releaseChannel, baseVersion: 1, reason: 'review' };
  const denied = await app.inject({ method: 'POST', url: `/api/v1/apps/${manifest.appId}/approve`, headers: { 'x-request-id': randomUUID() }, payload: body });
  assert.equal(denied.statusCode, 403);
  actor = { ...actor, roles: ['catalog-admin'] };
  const approved = await app.inject({ method: 'POST', url: `/api/v1/apps/${manifest.appId}/approve`, headers: { 'x-request-id': randomUUID() }, payload: body });
  assert.equal(approved.statusCode, 200);
  assert.equal(approved.json().catalogState, 'approved');
});

test('opaque iframe executes ticketed package script without sending session cookie', { timeout: 15000 }, async (t) => {
  const dir = await mkdtemp(join(tmpdir(), 'dgos-package-opaque-'));
  const app = Fastify({ logger: false });
  const { privateKey, publicKey } = generateKeyPairSync('ed25519');
  const owner = randomUUID(); const appId = 'com.example.opaque';
  const manifest = { format: 'dgos-app/v1', appId, version: '1.0.0', build: 1, releaseChannel: 'stable', minRuntimeVersion: '1.0.0', dataVersion: 1, name: { 'zh-CN': '测试', 'en-US': 'Test' }, description: { 'zh-CN': '测试', 'en-US': 'Test' }, category: 'productivity', icon: 'icon.svg', defaultWindow: { width: 800, height: 600 }, entrypoints: { web: 'index.html' }, permissions: [], capabilityAllowlist: [], trustLevel: 'standard', uninstallPolicy: 'user-removable', backgroundPolicy: 'release' };
  const files = { 'index.html': Buffer.from('<html><head><script src="./workbench.js?launchTicket=__DGOS_LAUNCH_TICKET__" defer></script></head><body><output id="status">Connecting</output></body></html>').toString('base64'), 'workbench.js': Buffer.from("document.querySelector('#status').textContent='Ready'; window.parent.postMessage({type:'fixture.ready'},'*')").toString('base64'), 'icon.svg': Buffer.from('<svg/>').toString('base64') };
  const resourceDigests = Object.fromEntries(Object.entries(files).map(([path, content]) => [path, `sha256:${createHash('sha256').update(Buffer.from(content, 'base64')).digest('hex')}`]));
  const envelope = { manifest, files, resourceDigests, keyId: 'fixture', signature: sign(null, Buffer.from(canonicalJson({ manifest, resourceDigests })), privateKey).toString('base64') };
  let revoked = false;
  const service = registerPackageRoutes(app, { store: new DiskPackageStore(dir), trustRoots: new Map([['fixture', { publicKey, source: 'official' }]]), requireScope: async (request) => ({ subjectId: request.headers['x-subject'], sessionId: request.headers['x-session'] }), validateCsrf: async () => {}, validateLaunchSession: async () => !revoked });
  app.get('/fixture-host', async (_request, reply) => reply.type('text/html').send('<html><body><iframe sandbox="allow-scripts" id="app"></iframe><script>window.addEventListener("message",e=>{if(e.source===document.querySelector("#app").contentWindow)window.fixtureReady=e.data.type});</script></body></html>'));
  await app.listen({ host: '127.0.0.1', port: 15162 });
  const browser = await chromium.launch({ headless: true });
  t.after(async () => { await browser.close(); await app.close(); await rm(dir, { recursive: true, force: true }); });
  await service.submit({ ...envelope, requestId: randomUUID() });
  await service.install({ subjectId: owner, appId, version: '1.0.0', build: 1, releaseChannel: 'stable' });
  const launch = (await app.inject({ method: 'POST', url: `/api/v1/apps/${appId}/launch`, headers: { 'x-subject': owner, 'x-session': 'fixture-session' } })).json();
  const page = await browser.newPage();
  await page.goto('http://127.0.0.1:15162/fixture-host');
  const responses = [];
  const resourceRequests = [];
  page.on('request', (request) => { if (request.url().includes('/resources/')) resourceRequests.push({ path: new URL(request.url()).pathname, cookie: request.headers().cookie, referer: request.headers().referer }); });
  page.on('response', (response) => { if (response.url().includes('/resources/')) responses.push({ path: new URL(response.url()).pathname, status: response.status() }); });
  await page.locator('#app').evaluate((iframe, entrypoint) => { iframe.src = entrypoint; }, launch.entrypoint);
  await page.waitForFunction(() => window.fixtureReady === 'fixture.ready', { timeout: 5000 });
  assert.equal(await page.frameLocator('#app').locator('#status').textContent(), 'Ready');
  assert.deepEqual(responses.map((entry) => entry.status), [200, 200]);
  assert.equal(resourceRequests.find((entry) => entry.path.endsWith('/workbench.js')).cookie, undefined);
  assert.equal(Boolean(resourceRequests.find((entry) => entry.path.endsWith('/workbench.js')).referer), false);
  revoked = true;
  assert.equal((await app.inject({ method: 'GET', url: launch.entrypoint })).statusCode, 403);
});

test('invalid bridge result keeps prepared receipt and does not rerun handler', async (t) => {
  const dir = await mkdtemp(join(tmpdir(), 'dgos-package-receipt-'));
  const app = Fastify({ logger: false });
  t.after(async () => { await app.close(); await rm(dir, { recursive: true, force: true }); });
  const { privateKey, publicKey } = generateKeyPairSync('ed25519');
  const owner = randomUUID(); const appId = 'com.example.receipt';
  const manifest = { format: 'dgos-app/v1', appId, version: '1.0.0', build: 1, releaseChannel: 'stable', minRuntimeVersion: '1.0.0', dataVersion: 1, name: { 'zh-CN': '测试', 'en-US': 'Test' }, description: { 'zh-CN': '测试', 'en-US': 'Test' }, category: 'productivity', icon: 'icon.svg', defaultWindow: { width: 800, height: 600 }, entrypoints: { web: 'index.html' }, permissions: ['dgos.aiTask.submit'], capabilityAllowlist: ['dgos.aiTask.submit'], trustLevel: 'standard', uninstallPolicy: 'user-removable', backgroundPolicy: 'release' };
  const files = { 'index.html': Buffer.from('<html>ok</html>').toString('base64'), 'icon.svg': Buffer.from('<svg/>').toString('base64') };
  const resourceDigests = Object.fromEntries(Object.entries(files).map(([path, content]) => [path, `sha256:${createHash('sha256').update(Buffer.from(content, 'base64')).digest('hex')}`]));
  let calls = 0;
  const service = registerPackageRoutes(app, { store: new DiskPackageStore(dir), trustRoots: new Map([['fixture', { publicKey, source: 'official' }]]), requireScope: async () => ({ subjectId: owner, sessionId: 'fixture-session' }), validateCsrf: async () => {}, bridgeAuthorize: async () => true, bridgeHandlers: { 'dgos.aiTask.submit': async () => { calls += 1; return { taskId: 'task-1', invalid: Infinity }; } } });
  await app.ready();
  await service.submit({ manifest, files, resourceDigests, keyId: 'fixture', requestId: randomUUID(), signature: sign(null, Buffer.from(canonicalJson({ manifest, resourceDigests })), privateKey).toString('base64') });
  await service.install({ subjectId: owner, appId, version: '1.0.0', build: 1, releaseChannel: 'stable' });
  const launch = (await app.inject({ method: 'POST', url: `/api/v1/apps/${appId}/launch` })).json();
  const requestId = randomUUID(); const payload = { instanceId: launch.instanceId, requestId, capability: 'dgos.aiTask.submit', input: { target: 'text' } };
  const first = await app.inject({ method: 'POST', url: `/api/v1/apps/${appId}/bridge`, payload });
  assert.equal(first.statusCode, 422);
  assert.equal(first.json().message, 'invalid_bridge_json');
  assert.equal((await service.store.readReceipt(owner, appId, launch.instanceId, requestId)).state, 'prepared');
  const retry = await app.inject({ method: 'POST', url: `/api/v1/apps/${appId}/bridge`, payload });
  assert.equal(retry.statusCode, 409);
  assert.equal(retry.json().message, 'upstream_outcome_unknown');
  assert.equal(calls, 1);
});
