import test from 'node:test';
import assert from 'node:assert/strict';
import { buildServer } from '../../apps/api/src/server.mjs';

test('identity and API key lifecycle exposes redacted contract', async () => {
  const app = buildServer({ logger: false });
  const bootstrap = await app.inject({ method: 'POST', url: '/api/v1/identity/admin/bootstrap', payload: { displayName: 'Admin', credential: 'correct horse battery staple' } });
  assert.equal(bootstrap.statusCode, 201);
  const receipt = bootstrap.json();
  assert.ok(receipt.sessionId);
  assert.match(bootstrap.headers['set-cookie'], /HttpOnly/);
  const session = await app.inject({ method: 'GET', url: '/api/v1/identity/admin/session', headers: { authorization: `Bearer ${receipt.sessionId}` } });
  assert.equal(session.statusCode, 200);
  const key = await app.inject({ method: 'POST', url: '/api/v1/secret/api-keys', headers: { authorization: `Bearer ${receipt.sessionId}` }, payload: { name: 'CI', scopes: ['audit.read'] } });
  assert.equal(key.statusCode, 201);
  assert.match(key.json().secret, /^dgos_/);
  const list = await app.inject({ method: 'GET', url: '/api/v1/secret/api-keys', headers: { authorization: `Bearer ${receipt.sessionId}` } });
  assert.equal(list.statusCode, 200);
  assert.equal(list.json().items[0].secret, undefined);
  const csrfDenied = await app.inject({ method: 'POST', url: '/api/v1/identity/admin/session', headers: { authorization: `Bearer ${receipt.sessionId}`, cookie: `dgos_session=${receipt.sessionId}` }, payload: { baseVersion: '1' } });
  assert.equal(csrfDenied.statusCode, 403);
  const keyDenied = await app.inject({ method: 'GET', url: '/api/v1/secret/api-keys', headers: { authorization: `ApiKey ${key.json().secret}` } });
  assert.equal(keyDenied.statusCode, 403);
  const manageKey = await app.inject({ method: 'POST', url: '/api/v1/secret/api-keys', headers: { authorization: `Bearer ${receipt.sessionId}` }, payload: { name: 'manage-ci', scopes: ['apiKey.read', 'apiKey.manage'] } });
  const keyAllowed = await app.inject({ method: 'GET', url: '/api/v1/secret/api-keys', headers: { authorization: `ApiKey ${manageKey.json().secret}` } });
  assert.equal(keyAllowed.statusCode, 200);
  const auditDenied = await app.inject({ method: 'GET', url: '/api/v1/audit/events', headers: { authorization: `ApiKey ${manageKey.json().secret}` } });
  assert.equal(auditDenied.statusCode, 403);
  const audit = await app.inject({ method: 'GET', url: '/api/v1/audit/events', headers: { authorization: `Bearer ${receipt.sessionId}` } });
  assert.equal(audit.statusCode, 200);
  assert.ok(Array.isArray(audit.json().items));
  const loginFailures = await Promise.all(Array.from({ length: 5 }, () => app.inject({ method: 'POST', url: '/api/v1/identity/admin/login', payload: { principalHint: receipt.principalId, credential: 'wrong' } })));
  assert.equal(loginFailures.every((response) => response.statusCode === 401), true);
  const rateLimited = await app.inject({ method: 'POST', url: '/api/v1/identity/admin/login', payload: { principalHint: receipt.principalId, credential: 'wrong' } });
  assert.equal(rateLimited.statusCode, 429);
  const csfrRenewed = await app.inject({ method: 'POST', url: '/api/v1/identity/admin/session', headers: { authorization: `Bearer ${receipt.sessionId}`, cookie: `dgos_session=${receipt.sessionId}`, 'x-dgos-csrf': 'test-token' }, payload: { baseVersion: '1' } });
  assert.equal(csfrRenewed.statusCode, 200);
  const rotated = await app.inject({ method: 'POST', url: `/api/v1/secret/api-keys/${key.json().key.keyId}/rotate`, headers: { authorization: `Bearer ${receipt.sessionId}` }, payload: { requestId: 'rotate-1', baseVersion: '1' } });
  assert.equal(rotated.statusCode, 200);
  assert.equal(rotated.json().previousKeyId, key.json().key.keyId);
  assert.equal(rotated.json().secret === key.json().secret, false);
  assert.equal((await app.inject({ method: 'POST', url: '/api/v1/identity/admin/bootstrap', payload: { displayName: 'Second', credential: 'second-credential' } })).statusCode, 409);
  const bad = await app.inject({ method: 'GET', url: '/api/v1/identity/admin/session' });
  assert.equal(bad.statusCode, 401);
  assert.equal(bad.json().errorKey, 'session_invalid');
  await app.close();
});
