import test from 'node:test';
import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { mkdtemp, readFile, rm } from 'node:fs/promises';
import https from 'node:https';
import net from 'node:net';
import os from 'node:os';
import path from 'node:path';
import { ProviderEgress } from '../../src/security/provider-egress.mjs';
import { createNetworkRouteFactory } from '../../src/security/network-route.mjs';
import { validateProxyConfig } from '../../src/security/proxy-transport.mjs';

const listen = (server, port) => new Promise((resolve) => server.listen(port, '127.0.0.1', () => resolve(server.address().port)));
const close = (server) => new Promise((resolve) => server.close(resolve));

test('network route applies only on activation and CONNECT pins IP with target TLS', { timeout: 10000 }, async (t) => {
  const root = await mkdtemp(path.join(os.tmpdir(), 'dgos-network-r5-'));
  t.after(() => rm(root, { recursive: true, force: true }));
  execFileSync('openssl', ['req', '-x509', '-newkey', 'rsa:2048', '-noenc', '-keyout', path.join(root, 'key.pem'), '-out', path.join(root, 'cert.pem'), '-days', '1', '-subj', '/CN=target.test', '-addext', 'subjectAltName=DNS:target.test'], { stdio: 'ignore' });
  const ca = await readFile(path.join(root, 'cert.pem'));
  let targetCalls = 0;
  const targetServer = https.createServer({ key: await readFile(path.join(root, 'key.pem')), cert: ca }, (req, res) => {
    targetCalls++; assert.equal(req.headers['proxy-authorization'], undefined);
    if (req.url === '/stream' || req.url === '/stall') { res.writeHead(200); res.write('early'); if (req.url === '/stream') setTimeout(() => res.end('late'), 150); return; }
    res.writeHead(req.url === '/redirect' ? 302 : 200, req.url === '/redirect' ? { location: 'https://other.test/' } : {}); res.end('ok');
  });
  const targetPort = await listen(targetServer, 15181);
  t.after(() => { targetServer.closeAllConnections(); return close(targetServer); });
  const tunnels = [];
  const proxySockets = new Set();
  const proxy = net.createServer((client) => {
    proxySockets.add(client);
    client.once('close', () => proxySockets.delete(client));
    let pending = Buffer.alloc(0);
    const header = (chunk) => {
      pending = Buffer.concat([pending, chunk]);
      const end = pending.indexOf('\r\n\r\n');
      if (end < 0) return;
      client.off('data', header);
      const request = pending.subarray(0, end).toString('latin1');
      const authority = /^CONNECT (\S+) HTTP\/1\.1/.exec(request)?.[1];
      tunnels.push({ authority, authorization: /proxy-authorization: ([^\r\n]+)/i.exec(request)?.[1] });
      const upstream = net.connect(targetPort, '127.0.0.1', () => { client.write('HTTP/1.1 200 Connection Established\r\n\r\n'); const tail = pending.subarray(end + 4); if (tail.length) upstream.write(tail); client.pipe(upstream).pipe(client); });
      proxySockets.add(upstream);
      upstream.once('close', () => proxySockets.delete(upstream));
      upstream.on('error', () => client.destroy());
      client.on('error', () => upstream.destroy());
    };
    client.on('data', header);
  });
  const proxyPort = await listen(proxy, 15182);
  t.after(() => { for (const socket of proxySockets) socket.destroy(); return close(proxy); });
  let revoked = false;
  const secret = { async resolve(input) { assert.equal(input.purpose, 'network-proxy'); assert.equal(input.subjectId, 'system'); return { async read() { if (revoked) throw new Error('credential_unavailable'); return JSON.stringify({ url: `http://127.0.0.1:${proxyPort}/`, authorization: 'Basic dGVzdDpzZWNyZXQ=' }); } }; } };
  const lookup = async () => [{ address: '127.0.0.1' }];
  const egress = new ProviderEgress({ lookup, internalHosts: ['target.test'], ca });
  const route = createNetworkRouteFactory({ egress, secretService: secret, proxyLookup: lookup, ca, allowLocalFixture: true });
  const off = { settingsVersion: '1', settings: { network: { proxyMode: 'off' } } };
  const manual = { settingsVersion: '2', settings: { network: { proxyMode: 'manual', manualProxyRef: 'proxy-ref' } } };
  await route.activateFromSnapshot(off);
  const url = `https://target.test:${targetPort}/ok`;
  assert.equal(await (await route.request({ url })).text(), 'ok');
  assert.equal(tunnels.length, 0);
  assert.equal(route.active().effectiveRoute, 'direct');
  // Saving settings alone does not mutate the process route.
  assert.equal(await (await route.request({ url })).text(), 'ok');
  assert.equal(tunnels.length, 0);
  let activated;
  await route.activateFromSnapshot(manual, { onActivated: (value) => { activated = value; } });
  assert.equal(activated.effectiveRoute, 'manual');
  assert.equal(await (await route.request({ url })).text(), 'ok');
  assert.deepEqual(tunnels.map((entry) => entry.authority), [`127.0.0.1:${targetPort}`]);
  assert.equal(tunnels[0].authorization, 'Basic dGVzdDpzZWNyZXQ=');
  assert.equal(targetCalls, 3);
  await assert.rejects(() => route.activateFromSnapshot(off, { onActivated() { throw new Error('projection_failed'); } }), /projection_failed/);
  assert.equal(route.active().effectiveRoute, 'manual');
  await assert.rejects(() => route.request({ url: `https://target.test:${targetPort}/redirect` }), /policy_blocked/);
  await assert.rejects(() => route.request({ url: 'https://127.0.0.1/' }), /policy_blocked|endpoint_invalid/);
  const wrongCa = createNetworkRouteFactory({ egress, secretService: secret, proxyLookup: lookup, ca: 'wrong', allowLocalFixture: true });
  await wrongCa.activateFromSnapshot(manual);
  await assert.rejects(() => wrongCa.request({ url }), /tls_invalid/);
  revoked = true;
  const beforeRevoke = tunnels.length;
  await assert.rejects(() => route.request({ url }), /credential_unavailable/);
  assert.equal(tunnels.length, beforeRevoke);
  await assert.rejects(() => route.activateFromSnapshot(manual), /credential_unavailable/);
  assert.equal(route.active().effectiveRoute, 'manual');
  const system = await route.activateFromSnapshot({ settingsVersion: '3', settings: { network: { proxyMode: 'system' } } });
  assert.equal(system.effectiveRoute, 'direct');
  assert.equal(await (await route.request({ url })).text(), 'ok');
  assert.equal(tunnels.length, beforeRevoke);
  const systemProxy = createNetworkRouteFactory({ egress, secretService: secret, proxyLookup: lookup, ca, allowLocalFixture: true, systemProxyProvider: async () => ({ url: `http://127.0.0.1:${proxyPort}/` }) });
  assert.equal((await systemProxy.activateFromSnapshot({ settingsVersion: '4', settings: { network: { proxyMode: 'system' } } })).effectiveRoute, 'system');
  assert.equal(await (await systemProxy.request({ url })).text(), 'ok');
  assert.equal(tunnels.length, beforeRevoke + 1);
  await assert.rejects(() => systemProxy.request({ url, maxResponseBytes: 1 }), /response_too_large/);
  await assert.rejects(() => systemProxy.request({ url, signal: AbortSignal.abort() }), /cancelled/);
  const stream = await systemProxy.request({ url: `https://target.test:${targetPort}/stream`, streamResponse: true, timeoutMs: 1000 });
  const first = await stream.body.next();
  assert.equal(first.value.toString(), 'early');
  assert.equal(first.done, false);
  await assert.rejects(async () => { for await (const _chunk of (await systemProxy.request({ url: `https://target.test:${targetPort}/stream`, streamResponse: true, maxResponseBytes: 3 })).body) {} }, /response_too_large/);
  const controller = new AbortController();
  const aborted = await systemProxy.request({ url: `https://target.test:${targetPort}/stream`, streamResponse: true, signal: controller.signal });
  const next = aborted.body.next();
  controller.abort();
  await assert.rejects(next, /cancelled/);
  await stream.body.return();
  const stalled = await systemProxy.request({ url: `https://target.test:${targetPort}/stall`, streamResponse: true, timeoutMs: 100 });
  assert.equal((await stalled.body.next()).value.toString(), 'early');
  await assert.rejects(stalled.body.next(), /timed_out/);
  assert.throws(() => validateProxyConfig({ url: 'http://proxy.example/' }), /proxy_configuration_invalid/);
  const blockedProxy = createNetworkRouteFactory({ egress, secretService: secret, proxyLookup: async () => [{ address: '127.0.0.1' }], systemProxyProvider: async () => ({ url: 'https://proxy.example/' }) });
  await blockedProxy.activateFromSnapshot({ settingsVersion: '5', settings: { network: { proxyMode: 'system' } } });
  await assert.rejects(() => blockedProxy.request({ url }), /policy_blocked/);
  const leased = createNetworkRouteFactory({ egress, secretService: secret, ca, allowLocalFixture: true });
  leased.requireLease();
  await leased.activateFromSnapshot(off);
  await assert.rejects(() => leased.request({ url }), /route_unavailable/);
  leased.confirmLease(1000);
  assert.equal(await (await leased.request({ url })).text(), 'ok');
  leased.suspendLease();
  await assert.rejects(() => leased.request({ url }), /route_unavailable/);
  const hangingEgress = new ProviderEgress({ lookup: async () => new Promise(() => {}), allowHosts: ['hanging.test'] });
  const hanging = createNetworkRouteFactory({ egress: hangingEgress, secretService: secret, systemProxyProvider: async () => ({ url: `http://127.0.0.1:${proxyPort}/` }), allowLocalFixture: true });
  await hanging.activateFromSnapshot({ settingsVersion: '6', settings: { network: { proxyMode: 'system' } } });
  await assert.rejects(() => hanging.request({ url: 'https://hanging.test/', timeoutMs: 30 }), /timed_out/);
  const abortHanging = new AbortController();
  const pending = hanging.request({ url: 'https://hanging.test/', timeoutMs: 1000, signal: abortHanging.signal });
  abortHanging.abort();
  await assert.rejects(pending, /cancelled/);
});
