import test from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import pg from '../../apps/api/node_modules/pg/esm/index.mjs';
import { PostgresIdentityRepository } from '../../src/identity/repository.mjs';
import { InMemorySecretService } from '../../src/security/secret-service.mjs';
import { IdentityService } from '../../apps/api/src/identity-service.mjs';

const connectionString = process.env.DGOS_DATABASE_URL ?? 'postgres://dgos:dgos@127.0.0.1:5432/dgos';

test('PostgreSQL repository persists identity, key digest, and audit outbox', async (t) => {
  const pool = new pg.Pool({ connectionString });
  try { await pool.query('SELECT 1'); } catch (error) { await pool.end(); t.skip(`PostgreSQL unavailable: ${error.message}`); return; }
  await pool.query('DELETE FROM audit_outbox');
  await pool.query('DELETE FROM audit_events');
  await pool.query('DELETE FROM model_catalog_entries');
  await pool.query('DELETE FROM model_catalogs');
  await pool.query('DELETE FROM model_policies');
  await pool.query('DELETE FROM ai_task_events');
  await pool.query('DELETE FROM artifacts');
  await pool.query('DELETE FROM ai_task_attempts');
  await pool.query('DELETE FROM ai_tasks');
  await pool.query('DELETE FROM provider_configs');
  await pool.query('DELETE FROM provider_accounts');
  await pool.query('DELETE FROM api_key_records');
  await pool.query('DELETE FROM admin_sessions');
  await pool.query('DELETE FROM admin_principals');
  const repo = new PostgresIdentityRepository(pool);
  const secret = new InMemorySecretService();
  const service = new IdentityService({ repository: repo, secretService: secret });
  const suffix = Date.now().toString();
  const bootstrap = await service.bootstrap({ displayName: `Integration ${suffix}`, credential: `credential-${suffix}`, requestId: randomUUID() });
  const key = await service.createKey({ ownerId: bootstrap.principalId, name: `integration-${suffix}`, scopes: ['audit.read'], requestId: randomUUID(), actorId: bootstrap.principalId });
  assert.match(key.secret, /^dgos_/);
  const rows = await pool.query('SELECT digest, scope, state FROM api_key_records WHERE key_id = $1', [key.key.keyId]);
  assert.equal(rows.rows[0].digest.includes(key.secret), false);
  assert.deepEqual(rows.rows[0].scope.scopes, ['audit.read']);
  assert.equal(rows.rows[0].state, 'active');
  const outbox = await pool.query('SELECT count(*)::int AS count FROM audit_outbox');
  assert.ok(outbox.rows[0].count >= 2);
  const secondRepo = new PostgresIdentityRepository(pool);
  await assert.rejects(service.revokeKey({ keyId: key.key.keyId, actorId: randomUUID(), requestId: randomUUID() }), /permission_denied/);
  const originalAudit = repo.audit;
  repo.audit = { record: async () => { throw new Error('audit_unavailable'); } };
  await assert.rejects(service.rotateKey({ keyId: key.key.keyId, actorId: bootstrap.principalId, requestId: randomUUID() }), /audit_unavailable/);
  assert.equal((await repo.getKey(key.key.keyId)).state, 'active');
  assert.equal((await repo.listKeys(bootstrap.principalId)).length, 1);
  await assert.rejects(repo.renewSessionWithAudit(bootstrap.sessionId, 1, new Date(Date.now() + 60000), () => ({})), /audit_unavailable/);
  assert.equal((await repo.getSession(bootstrap.sessionId)).sessionVersion, 1);
  repo.audit = originalAudit;
  const rotated = await service.rotateKey({ keyId: key.key.keyId, actorId: bootstrap.principalId, baseVersion: key.key.version, requestId: randomUUID() });
  assert.equal((await repo.getKey(key.key.keyId)).state, 'rotation_pending');
  assert.equal((await repo.getKey(rotated.key.keyId)).state, 'active');
  assert.equal(rotated.key.rotationGroupId, key.key.rotationGroupId);
  const rotatedFromSecondInstance = await secondRepo.getKey(rotated.key.keyId);
  assert.equal(rotatedFromSecondInstance.state, 'active');
  await secondRepo.revokeKeyWithAudit(rotated.key.keyId, ({ keyId }) => ({ requestId: randomUUID(), actorId: bootstrap.principalId, action: 'api_key.revoke', targetType: 'api_key', targetId: keyId }));
  assert.equal((await repo.getKey(rotated.key.keyId)).state, 'revoked');
  await pool.query('DELETE FROM audit_outbox WHERE event_id IN (SELECT event_id FROM audit_events WHERE actor_id = $1)', [bootstrap.principalId]);
  await pool.query('DELETE FROM audit_events WHERE actor_id = $1', [bootstrap.principalId]);
  await pool.query('DELETE FROM api_key_records WHERE owner_id = $1', [bootstrap.principalId]);
  await pool.query('DELETE FROM admin_sessions WHERE principal_id = $1', [bootstrap.principalId]);
  await pool.query('DELETE FROM admin_principals WHERE principal_id = $1', [bootstrap.principalId]);
  await pool.end();
});
