import test from 'node:test';
import assert from 'node:assert/strict';
import { generateKeyPairSync, sign, createHash, randomUUID } from 'node:crypto';
import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import pg from '../../apps/api/node_modules/pg/lib/index.js';
import { DiskPackageStore, PackageService, canonicalJson } from '../../src/apps/package-service.mjs';
import { PostgresPackageRepository } from '../../src/apps/postgres-package-repository.mjs';

const digest = (value) => `sha256:${createHash('sha256').update(value).digest('hex')}`;
const envelope = (appId, channel, privateKey) => {
  const manifest = { format: 'dgos-app/v1', appId, version: '1.0.0', build: 1, releaseChannel: channel, minRuntimeVersion: '1.0.0', dataVersion: 1, name: { 'zh-CN': '测试', 'en-US': 'Test' }, description: { 'zh-CN': '测试', 'en-US': 'Test' }, category: 'productivity', icon: 'icon.svg', defaultWindow: { width: 800, height: 600 }, entrypoints: { web: 'index.html' }, permissions: [], capabilityAllowlist: [], trustLevel: 'standard', uninstallPolicy: 'user-removable', backgroundPolicy: 'release' };
  const bytes = Buffer.from(`<html>${channel}</html>`);
  const icon = Buffer.from('<svg xmlns="http://www.w3.org/2000/svg"/>');
  const resourceDigests = { 'index.html': digest(bytes), 'icon.svg': digest(icon) };
  return { requestId: randomUUID(), manifest, files: { 'index.html': bytes.toString('base64'), 'icon.svg': icon.toString('base64') }, resourceDigests, keyId: 'test', signature: sign(null, Buffer.from(canonicalJson({ manifest, resourceDigests })), privateKey).toString('base64') };
};

const testDatabase = process.env.DGOS_DATABASE_URL ? new URL(process.env.DGOS_DATABASE_URL).pathname.slice(1) : '';
const isolatedDatabase = /^(?:dgos_v1_packages|dgos_v1_integrated|dgos_v1_verify_[0-9a-f]{32})$/.test(testDatabase);
test('PostgreSQL signed releases distinguish channels and persist lifecycle', { skip: !process.env.DGOS_DATABASE_URL }, async (t) => {
  if (!isolatedDatabase) throw new Error('package_test_requires_isolated_v1_database');
  const pool = new pg.Pool({ connectionString: process.env.DGOS_DATABASE_URL });
  const dir = await mkdtemp(join(tmpdir(), 'dgos-pg-packages-'));
  const appId = `com.example.pg${randomUUID().replaceAll('-', '')}`;
  const subjectId = randomUUID(); const actorId = randomUUID();
  t.after(async () => {
    await pool.query('DELETE FROM app_package_operations WHERE app_id=$1', [appId]);
    await pool.query('DELETE FROM app_package_deployments WHERE app_id=$1', [appId]);
    await pool.query('DELETE FROM app_package_releases WHERE app_id=$1', [appId]);
    await pool.end(); await rm(dir, { recursive: true, force: true });
  });
  const { privateKey, publicKey } = generateKeyPairSync('ed25519');
  const repository = new PostgresPackageRepository(pool);
  const store = new DiskPackageStore(dir);
  const trustRoots = new Map([['test', { source: 'developer', publicKey }]]);
  const service = new PackageService({ repository, store, trustRoots });
  const stable = envelope(appId, 'stable', privateKey); const beta = envelope(appId, 'beta', privateKey);
  const stableRecord = await service.submit(stable); const betaRecord = await service.submit(beta);
  assert.notEqual(stableRecord.digest, betaRecord.digest);
  assert.equal((await repository.getPackage(appId, '1.0.0', 1, 'stable')).digest, stableRecord.digest);
  assert.equal((await repository.getPackage(appId, '1.0.0', 1, 'beta')).digest, betaRecord.digest);
  assert.equal(await repository.getPackage(appId, '1.0.0', 1), null);
  await assert.rejects(service.review({ appId, version: '1.0.0', build: 1, releaseChannel: 'stable', baseVersion: 2, decision: 'approved', actorId }), { message: 'review_conflict' });
  await service.review({ appId, version: '1.0.0', build: 1, releaseChannel: 'stable', baseVersion: 1, decision: 'approved', actorId });
  const install = await service.install({ subjectId, appId, version: '1.0.0', build: 1, releaseChannel: 'stable', actorId });
  assert.equal(install.versionNumber, 1); assert.equal(install.digest, stableRecord.digest);
  assert.deepEqual(await service.getAppDeployment(subjectId, appId), { appId, state: 'active', versionNumber: 1, dataRetained: true, activeRelease: { version: '1.0.0', build: 1, releaseChannel: 'stable', digest: stableRecord.digest, dataVersion: 1 } });
  await store.removePointer(subjectId, appId);
  const restarted = new PackageService({ repository: new PostgresPackageRepository(pool), store: new DiskPackageStore(dir), trustRoots });
  assert.deepEqual(await restarted.recover({ subjectId, appId }), { appId, state: 'active', digest: stableRecord.digest });
  assert.equal((await store.current(subjectId, appId)).digest, stableRecord.digest);
  await assert.rejects(service.uninstall({ subjectId, appId, baseVersion: 2, actorId }), { message: 'version_conflict' });
  const removed = await service.uninstall({ subjectId, appId, baseVersion: 1, actorId });
  assert.equal(removed.state, 'uninstalled'); assert.equal(removed.dataRetained, true);
  assert.equal((await repository.getDeployment(subjectId, appId)).versionNumber, 2);
  assert.equal((await service.getAppDeployment(subjectId, appId)).activeRelease, null);
  await store.switch(subjectId, appId, { manifest: stable.manifest, digest: stableRecord.digest });
  assert.deepEqual(await restarted.recover({ subjectId, appId }), { appId, state: 'uninstalled' });
  assert.equal(await store.current(subjectId, appId), null);
});

test('audit failure rolls back review; pointer crash windows recover from durable deployment', { skip: !process.env.DGOS_DATABASE_URL }, async (t) => {
  if (!isolatedDatabase) throw new Error('package_test_requires_isolated_v1_database');
  const pool = new pg.Pool({ connectionString: process.env.DGOS_DATABASE_URL });
  const dir = await mkdtemp(join(tmpdir(), 'dgos-pg-fault-'));
  const appId = `com.example.fault${randomUUID().replaceAll('-', '')}`;
  const subjectId = randomUUID(); const actorId = randomUUID();
  t.after(async () => { await pool.query('DELETE FROM app_package_operations WHERE app_id=$1', [appId]); await pool.query('DELETE FROM app_package_deployments WHERE app_id=$1', [appId]); await pool.query('DELETE FROM app_package_releases WHERE app_id=$1', [appId]); await pool.end(); await rm(dir, { recursive: true, force: true }); });
  const { privateKey, publicKey } = generateKeyPairSync('ed25519');
  const roots = new Map([['test', { source: 'developer', publicKey }]]);
  const repository = new PostgresPackageRepository(pool); const store = new DiskPackageStore(dir);
  const service = new PackageService({ repository, store, trustRoots: roots });
  const input = envelope(appId, 'stable', privateKey);
  const originalAudit = repository.auditEvent.bind(repository);
  repository.auditEvent = async () => { throw new Error('audit_injected_failure'); };
  await assert.rejects(service.submit(input), { message: 'audit_injected_failure' });
  assert.equal(await repository.getPackage(appId, '1.0.0', 1, 'stable'), undefined);
  repository.auditEvent = originalAudit;
  await service.submit(input);
  const submitAudit = await pool.query("SELECT e.event_id FROM audit_events e JOIN audit_outbox o ON o.event_id=e.event_id WHERE e.action='app.package.submit' AND e.summary->>'appId'=$1", [appId]);
  assert.equal(submitAudit.rows.length, 1);
  repository.auditEvent = async () => { throw new Error('audit_injected_failure'); };
  await assert.rejects(service.review({ appId, version: '1.0.0', build: 1, releaseChannel: 'stable', baseVersion: 1, decision: 'approved', actorId, requestId: randomUUID() }), { message: 'audit_injected_failure' });
  assert.equal((await repository.getPackage(appId, '1.0.0', 1, 'stable')).catalogState, 'pending_review');
  repository.auditEvent = originalAudit;
  await service.review({ appId, version: '1.0.0', build: 1, releaseChannel: 'stable', baseVersion: 1, decision: 'approved', actorId, requestId: randomUUID() });
  const reviewAudit = await pool.query("SELECT e.event_id FROM audit_events e JOIN audit_outbox o ON o.event_id=e.event_id WHERE e.action='app.catalog.approved' AND e.summary->>'appId'=$1", [appId]);
  assert.equal(reviewAudit.rows.length, 1);
  repository.auditEvent = async (event) => { if (event.action === 'app.install') throw new Error('audit_injected_failure'); return originalAudit(event); };
  await assert.rejects(service.install({ subjectId, appId, version: '1.0.0', build: 1, releaseChannel: 'stable', actorId, requestId: randomUUID() }), { message: 'audit_injected_failure' });
  assert.equal(await repository.getDeployment(subjectId, appId), null);
  assert.equal(await store.current(subjectId, appId), null);
  repository.auditEvent = originalAudit;
  const firstSwitch = store.switch.bind(store);
  store.switch = async (...args) => { await firstSwitch(...args); throw new Error('simulated_kill_after_install_pointer'); };
  await assert.rejects(service.install({ subjectId, appId, version: '1.0.0', build: 1, releaseChannel: 'stable', actorId, requestId: randomUUID() }), { message: 'simulated_kill_after_install_pointer' });
  store.switch = firstSwitch;
  assert.equal(await repository.getDeployment(subjectId, appId), null);
  const restarted = new PackageService({ repository: new PostgresPackageRepository(pool), store, trustRoots: roots });
  await restarted.recoverAll(); assert.equal(await store.current(subjectId, appId), null);
  const installed = await restarted.install({ subjectId, appId, version: '1.0.0', build: 1, releaseChannel: 'stable', actorId, requestId: randomUUID() });
  const originalRestartAudit = restarted.repository.auditEvent.bind(restarted.repository);
  restarted.repository.auditEvent = async (event) => { if (event.action === 'app.uninstall') throw new Error('audit_injected_failure'); return originalRestartAudit(event); };
  await assert.rejects(restarted.uninstall({ subjectId, appId, baseVersion: installed.versionNumber, actorId, requestId: randomUUID() }), { message: 'audit_injected_failure' });
  assert.equal((await repository.getDeployment(subjectId, appId)).state, 'active');
  assert.equal((await store.current(subjectId, appId)).digest, installed.digest);
  restarted.repository.auditEvent = originalRestartAudit;
  const removePointer = store.removePointer.bind(store);
  store.removePointer = async (...args) => { await removePointer(...args); throw new Error('simulated_kill_after_uninstall_pointer'); };
  await assert.rejects(restarted.uninstall({ subjectId, appId, baseVersion: installed.versionNumber, actorId, requestId: randomUUID() }), { message: 'simulated_kill_after_uninstall_pointer' });
  store.removePointer = removePointer;
  assert.equal((await repository.getDeployment(subjectId, appId)).state, 'active');
  await new PackageService({ repository: new PostgresPackageRepository(pool), store, trustRoots: roots }).recoverAll();
  assert.equal((await store.current(subjectId, appId)).digest, installed.digest);
});

test('PostgreSQL migration journal restores data after interrupted update', { skip: !process.env.DGOS_DATABASE_URL }, async (t) => {
  if (!isolatedDatabase) throw new Error('package_test_requires_isolated_v1_database');
  const pool = new pg.Pool({ connectionString: process.env.DGOS_DATABASE_URL });
  const dir = await mkdtemp(join(tmpdir(), 'dgos-pg-migration-'));
  const appId = `com.example.migrate${randomUUID().replaceAll('-', '')}`;
  const subjectId = randomUUID(); const actorId = randomUUID();
  t.after(async () => { await pool.query('DELETE FROM app_data_migrations WHERE app_id=$1', [appId]); await pool.query('DELETE FROM app_package_operations WHERE app_id=$1', [appId]); await pool.query('DELETE FROM app_package_deployments WHERE app_id=$1', [appId]); await pool.query('DELETE FROM app_package_releases WHERE app_id=$1', [appId]); await pool.end(); await rm(dir, { recursive: true, force: true }); });
  const { privateKey, publicKey } = generateKeyPairSync('ed25519'); const roots = new Map([['test', { source: 'official', publicKey }]]);
  const repository = new PostgresPackageRepository(pool); const store = new DiskPackageStore(dir); const service = new PackageService({ repository, store, trustRoots: roots });
  const first = envelope(appId, 'stable', privateKey); await service.submit(first);
  const installed = await service.install({ subjectId, appId, version: '1.0.0', build: 1, releaseChannel: 'stable', actorId, requestId: randomUUID() });
  await store.writeData(subjectId, appId, { prompt: 'preserve' });
  const next = envelope(appId, 'stable', privateKey); next.requestId = randomUUID(); next.manifest.version = '1.0.1'; next.manifest.build = 2; next.manifest.dataVersion = 2; next.manifest.dataMigration = { from: [1], entry: 'migrations/2.json' };
  const spec = Buffer.from(JSON.stringify({ moves: [{ from: 'prompt', to: 'last_prompt' }] })); next.files['migrations/2.json'] = spec.toString('base64'); next.resourceDigests['migrations/2.json'] = digest(spec);
  next.signature = sign(null, Buffer.from(canonicalJson({ manifest: next.manifest, resourceDigests: next.resourceDigests })), privateKey).toString('base64');
  await service.submit(next);
  const switchPointer = store.switch.bind(store);
  store.switch = async (...args) => { await switchPointer(...args); throw new Error('interrupted_after_migration'); };
  await assert.rejects(service.install({ subjectId, appId, version: '1.0.1', build: 2, releaseChannel: 'stable', baseVersion: installed.versionNumber, actorId, requestId: randomUUID() }), { message: 'interrupted_after_migration' });
  store.switch = switchPointer;
  assert.deepEqual(await store.readData(subjectId, appId), { last_prompt: 'preserve' });
  const pending = (await pool.query("SELECT source_package_digest,target_package_digest,before_digest,after_digest FROM app_data_migrations WHERE app_id=$1 AND state='prepared'", [appId])).rows[0];
  assert.equal(pending.source_package_digest, installed.digest);
  assert.equal(pending.target_package_digest, (await repository.getPackage(appId, '1.0.1', 2, 'stable')).digest);
  assert.notEqual(pending.before_digest, pending.after_digest);
  await new PackageService({ repository: new PostgresPackageRepository(pool), store, trustRoots: roots }).recoverAll();
  assert.deepEqual(await store.readData(subjectId, appId), { prompt: 'preserve' });
  assert.equal((await pool.query("SELECT state FROM app_data_migrations WHERE app_id=$1", [appId])).rows[0].state, 'rolled_back');
  assert.equal((await store.current(subjectId, appId)).digest, installed.digest);
});
