import test from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID, createHash } from 'node:crypto';
import { mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import pg from '../../apps/api/node_modules/pg/lib/index.js';
import { DiskPackageStore, canonicalJson } from '../../src/apps/package-service.mjs';
import { PostgresPackageRetention } from '../../src/apps/package-retention.mjs';
import { PostgresPackageRepository } from '../../src/apps/postgres-package-repository.mjs';
import { PostgresRetentionRepository, previewDigest } from '../../src/audit/retention.mjs';
import { PostgresAuditRepository } from '../../src/audit/outbox.mjs';

const db = process.env.DGOS_DATABASE_URL ? new URL(process.env.DGOS_DATABASE_URL).pathname.slice(1) : '';
const permitted = /^(?:dgos_v1_packages|dgos_v1_integrated|dgos_v1_verify_[0-9a-f]{32}|dgos_v1_retention_[0-9a-f]{32})$/.test(db);
test('package retention protects references, removes expired failed records, and resumes disk failure', { concurrency: false, skip: !process.env.DGOS_DATABASE_URL }, async (t) => {
  if (!permitted) throw new Error('isolated_retention_database_required');
  const pool = new pg.Pool({ connectionString: process.env.DGOS_DATABASE_URL });
  const root = await mkdtemp(join(tmpdir(), 'dgos-retention-'));
  const appId = `com.example.retention${randomUUID().replaceAll('-', '')}`;
  const subjectId = randomUUID();
  const requests = [];
  t.after(async () => {
    await pool.query('DELETE FROM app_package_cleanup_intents WHERE item_id IN (SELECT candidate_id FROM app_package_stage_candidates WHERE app_id=$1) OR item_id IN (SELECT operation_id FROM app_package_operations WHERE app_id=$1)', [appId]);
    await pool.query('DELETE FROM app_package_operations WHERE app_id=$1', [appId]);
    await pool.query('DELETE FROM app_package_stage_candidates WHERE app_id=$1', [appId]);
    await pool.query('DELETE FROM app_package_deployments WHERE app_id=$1', [appId]);
    await pool.query('DELETE FROM app_package_releases WHERE app_id=$1', [appId]);
    await pool.query('DELETE FROM app_package_cleanup_intents WHERE job_id IN (SELECT job_id FROM retention_jobs WHERE request_id=ANY($1::uuid[]))', [requests]);
    await pool.query('DELETE FROM retention_jobs WHERE request_id=ANY($1::uuid[])', [requests]);
    await pool.end(); await rm(root, { recursive: true, force: true });
  });
  const store = new DiskPackageStore(root);
  const audit = { record: async ({ requestId, actorId, action, targetType, targetId, summary }, client) => {
    await client.query('INSERT INTO audit_events(event_id,request_id,actor_type,actor_id,action,target_type,target_id,result,summary) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)', [randomUUID(), requestId, actorId ? 'admin' : 'system', actorId ?? null, action, targetType, targetId, 'succeeded', JSON.stringify(summary ?? {})]);
  } };
  const now = Date.now();
  const cleaner = new PostgresPackageRetention({ pool, store, audit });
  const repository = new PostgresRetentionRepository(pool, { audit, clock: () => now, packageRetention: cleaner });
  const manifest = { appId, releaseChannel: 'stable', version: '1.0.0', build: 1, entrypoints: { web: 'index.html' } };
  const content = Buffer.from('<html>retention fixture</html>');
  const resourceDigests = { 'index.html': `sha256:${createHash('sha256').update(content).digest('hex')}` };
  const digest = `sha256:${createHash('sha256').update(canonicalJson({ manifest, resourceDigests })).digest('hex')}`;
  const candidate = randomUUID(); const activeCandidate = randomUUID(); const youngCandidate = randomUUID();
  const releasePath = await store.stage(manifest, { digest, resourceDigests, files: new Map([['index.html', content]]) });
  for (const [id, age] of [[candidate, 31], [activeCandidate, 31], [youngCandidate, 30]]) await pool.query("INSERT INTO app_package_stage_candidates(candidate_id,app_id,manifest,package_digest,state,terminal_at) VALUES($1,$2,$3,$4,'failed',$5)", [id, appId, JSON.stringify(manifest), digest, new Date(now - age * 86400000)]);
  await pool.query('UPDATE app_package_stage_candidates SET package_digest=$2 WHERE candidate_id=$1', [youngCandidate, `sha256:${'f'.repeat(64)}`]);
  const failed = randomUUID(); const protectedOperation = randomUUID(); const youngOperation = randomUUID();
  for (const [id, age] of [[failed, 31], [protectedOperation, 31], [youngOperation, 30]]) await pool.query("INSERT INTO app_package_operations(operation_id,app_id,request_id,action,state,package_digest,occurred_at) VALUES($1,$2,$3,'install','rolled_back',$4,$5)", [id, appId, randomUUID(), digest, new Date(now - age * 86400000)]);
  await pool.query('UPDATE app_package_operations SET package_digest=$2 WHERE operation_id=$1', [protectedOperation, `sha256:${'e'.repeat(64)}`]);
  const releaseId = randomUUID();
  await pool.query("INSERT INTO app_package_releases(package_id,app_id,version,build,release_channel,manifest,package_digest,source,key_id,request_id,effective_trust_level,uninstall_policy,catalog_state) VALUES($1,$2,'1.0.0',1,'stable',$3,$4,'developer','fixture',$5,'standard','user-removable','approved')", [releaseId, appId, JSON.stringify(manifest), `sha256:${'e'.repeat(64)}`, randomUUID()]);
  await pool.query("INSERT INTO app_package_deployments(subject_id,app_id,package_id,version,build,release_channel,package_digest,previous_digest,state) VALUES($1,$2,$3,'1.0.0',1,'stable',$4,$5,'active')", [subjectId, appId, releaseId, `sha256:${'e'.repeat(64)}`, digest]);
  const dataPath = store.dataFor(subjectId, appId); await writeFile(dataPath, 'user-data').catch(async () => { const { mkdir } = await import('node:fs/promises'); const { dirname } = await import('node:path'); await mkdir(dirname(dataPath), { recursive: true }); await writeFile(dataPath, 'user-data'); });
  const before = await repository.preview();
  assert.equal(typeof before.packageRetention.plan.itemDigest, 'string');
  assert.equal(before.packageRetention.plan.policyVersion, '1');
  assert.deepEqual(before.packageRetention, { plan: before.packageRetention.plan, failedInstall: { eligibleCount: 0, protectedCount: 2 }, stagedPackage: { eligibleCount: 0, protectedCount: 2 } });
  await pool.query('UPDATE app_package_deployments SET previous_digest=NULL WHERE subject_id=$1 AND app_id=$2', [subjectId, appId]);
  const preview = await repository.preview();
  assert.notEqual(preview.packageRetention.plan.itemDigest, before.packageRetention.plan.itemDigest);
  assert.deepEqual(preview.packageRetention, { plan: preview.packageRetention.plan, failedInstall: { eligibleCount: 1, protectedCount: 1 }, stagedPackage: { eligibleCount: 2, protectedCount: 0 } });
  const requestId = randomUUID(); requests.push(requestId);
  const job = await repository.createJob({ previewDigest: previewDigest(preview), cutoffAt: preview.cutoffAt, confirmed: true, requestId });
  const originalRemove = store.removeStagedCandidate.bind(store);
  let first = true;
  store.removeStagedCandidate = async (...args) => { if (first) { first = false; throw new Error('injected_disk_failure'); } return originalRemove(...args); };
  const partial = await repository.runJob(job.jobId, 10);
  assert.equal(partial.state, 'partial'); assert.equal(partial.failureCount, 1);
  store.removeStagedCandidate = originalRemove;
  const resumed = new PostgresPackageRetention({ pool, store, audit, clock: () => now });
  const restarted = new PostgresRetentionRepository(pool, { audit, clock: () => now, packageRetention: resumed });
  const done = await restarted.runJob(job.jobId, 10);
  assert.equal(done.state, 'completed'); assert.equal(done.failureCount, 0);
  assert.equal(done.deletedCount, 3); assert.equal(done.skippedCount, 1);
  assert.equal((await pool.query('SELECT 1 FROM app_package_operations WHERE operation_id=$1', [failed])).rowCount, 0);
  assert.equal((await pool.query('SELECT 1 FROM app_package_operations WHERE operation_id=$1', [protectedOperation])).rowCount, 1);
  assert.equal((await pool.query('SELECT state FROM app_package_stage_candidates WHERE candidate_id=$1', [candidate])).rows[0].state, 'cleaned');
  await assert.rejects(readFile(join(releasePath, 'index.html')), { code: 'ENOENT' });
  assert.equal(await readFile(dataPath, 'utf8'), 'user-data');
});

test('audit failure after disk removal retains prepared intent and restart completes it', { concurrency: false, skip: !process.env.DGOS_DATABASE_URL }, async (t) => {
  if (!permitted) throw new Error('isolated_retention_database_required');
  const pool = new pg.Pool({ connectionString: process.env.DGOS_DATABASE_URL });
  const root = await mkdtemp(join(tmpdir(), 'dgos-retention-audit-'));
  const appId = `com.example.retention${randomUUID().replaceAll('-', '')}`;
  const candidateId = randomUUID(); const requestId = randomUUID();
  t.after(async () => {
    await pool.query('DELETE FROM app_package_cleanup_intents WHERE item_id=$1', [candidateId]);
    await pool.query('DELETE FROM app_package_stage_candidates WHERE candidate_id=$1', [candidateId]);
    await pool.query('DELETE FROM retention_jobs WHERE request_id=$1', [requestId]);
    await pool.end(); await rm(root, { recursive: true, force: true });
  });
  const store = new DiskPackageStore(root);
  const manifest = { appId, releaseChannel: 'stable', version: '1.0.0', build: 1, entrypoints: { web: 'index.html' } };
  const digest = `sha256:${createHash('sha256').update(appId).digest('hex')}`;
  await pool.query("INSERT INTO app_package_stage_candidates(candidate_id,app_id,manifest,package_digest,state,terminal_at) VALUES($1,$2,$3,$4,'failed',now()-interval '31 days')", [candidateId, appId, JSON.stringify(manifest), digest]);
  const target = store.pathFor(manifest, digest);
  const { mkdir } = await import('node:fs/promises');
  const { dirname } = await import('node:path');
  await mkdir(dirname(target), { recursive: true });
  await mkdir(`${target}.tmp-${candidateId}`, { recursive: true });
  await writeFile(join(`${target}.tmp-${candidateId}`, 'incomplete'), 'incomplete-stage');
  const audit = { record: async () => {} };
  const cleaner = new PostgresPackageRetention({ pool, store, audit });
  const job = { job_id: randomUUID(), request_id: requestId, actor_id: null };
  await pool.query("INSERT INTO retention_jobs(job_id,preview_digest,state,cutoff_at,request_id) VALUES($1,'fixture','planned',now(),$2)", [job.job_id, requestId]);
  let failAudit = false;
  audit.record = async (event) => { if (failAudit && event.action.endsWith('.removed')) throw new Error('audit_unavailable'); };
  const originalRemove = store.removeStagedCandidate.bind(store);
  store.removeStagedCandidate = async (...args) => { await originalRemove(...args); failAudit = true; };
  await assert.rejects(cleaner.runBatch(job, { cacheRetentionDays: 30 }), /audit_unavailable/);
  assert.equal((await pool.query('SELECT state FROM app_package_stage_candidates WHERE candidate_id=$1', [candidateId])).rows[0].state, 'cleaning');
  assert.equal((await pool.query("SELECT state FROM app_package_cleanup_intents WHERE item_id=$1", [candidateId])).rows[0].state, 'prepared');
  failAudit = false;
  const restarted = new PostgresPackageRetention({ pool, store: new DiskPackageStore(root), audit });
  await restarted.runBatch(job, { cacheRetentionDays: 30 });
  assert.equal((await pool.query('SELECT state FROM app_package_stage_candidates WHERE candidate_id=$1', [candidateId])).rows[0].state, 'cleaned');
  assert.equal((await pool.query("SELECT state FROM app_package_cleanup_intents WHERE item_id=$1", [candidateId])).rows[0].state, 'removed');
});

test('app lifecycle lock blocks cleanup and startup settles interrupted staging', { concurrency: false, skip: !process.env.DGOS_DATABASE_URL }, async (t) => {
  if (!permitted) throw new Error('isolated_retention_database_required');
  const pool = new pg.Pool({ connectionString: process.env.DGOS_DATABASE_URL });
  const root = await mkdtemp(join(tmpdir(), 'dgos-retention-lock-'));
  const appId = `com.example.retention${randomUUID().replaceAll('-', '')}`;
  const candidateId = randomUUID(); const requestId = randomUUID();
  t.after(async () => {
    await pool.query('DELETE FROM app_package_cleanup_intents WHERE item_id=$1', [candidateId]);
    await pool.query('DELETE FROM app_package_stage_candidates WHERE candidate_id=$1', [candidateId]);
    await pool.query('DELETE FROM retention_jobs WHERE request_id=$1', [requestId]);
    await pool.end(); await rm(root, { recursive: true, force: true });
  });
  const digest = `sha256:${createHash('sha256').update(appId).digest('hex')}`;
  const manifest = { appId, releaseChannel: 'stable', version: '1.0.0', build: 1, entrypoints: { web: 'index.html' } };
  await pool.query("INSERT INTO app_package_stage_candidates(candidate_id,app_id,manifest,package_digest,state) VALUES($1,$2,$3,$4,'pending')", [candidateId, appId, JSON.stringify(manifest), digest]);
  const cleaner = new PostgresPackageRetention({ pool, store: new DiskPackageStore(root), audit: { record: async () => {} } });
  await cleaner.ready();
  assert.equal((await pool.query('SELECT state FROM app_package_stage_candidates WHERE candidate_id=$1', [candidateId])).rows[0].state, 'failed');
  await pool.query("UPDATE app_package_stage_candidates SET terminal_at=now()-interval '31 days' WHERE candidate_id=$1", [candidateId]);
  const job = { job_id: randomUUID(), request_id: requestId, actor_id: null };
  await pool.query("INSERT INTO retention_jobs(job_id,preview_digest,state,cutoff_at,request_id) VALUES($1,'fixture','planned',now(),$2)", [job.job_id, requestId]);
  const lifecycle = new PostgresPackageRepository(pool);
  let releaseLock;
  const held = new Promise((resolve) => { releaseLock = resolve; });
  let lockAcquired;
  const acquired = new Promise((resolve) => { lockAcquired = resolve; });
  const holder = lifecycle.withAppLock(appId, async () => { lockAcquired(); await held; });
  await acquired;
  let finished = false;
  const sweep = cleaner.runBatch(job, { cacheRetentionDays: 30 }).then(() => { finished = true; });
  try {
    await new Promise((resolve) => setTimeout(resolve, 30));
    assert.equal(finished, false);
    assert.equal((await pool.query('SELECT state FROM app_package_stage_candidates WHERE candidate_id=$1', [candidateId])).rows[0].state, 'failed');
  } finally { releaseLock(); }
  await Promise.all([holder, sweep]);
  assert.equal((await pool.query('SELECT state FROM app_package_stage_candidates WHERE candidate_id=$1', [candidateId])).rows[0].state, 'cleaned');
});

test('confirmed preview rejects drift and failed install records continue across bounded batches', { concurrency: false, skip: !process.env.DGOS_DATABASE_URL }, async (t) => {
  if (!permitted) throw new Error('isolated_retention_database_required');
  const pool = new pg.Pool({ connectionString: process.env.DGOS_DATABASE_URL });
  const root = await mkdtemp(join(tmpdir(), 'dgos-retention-batch-'));
  const appId = `com.example.retention${randomUUID().replaceAll('-', '')}`;
  const requests = [randomUUID(), randomUUID()];
  t.after(async () => {
    await pool.query('DELETE FROM app_package_cleanup_intents WHERE job_id IN (SELECT job_id FROM retention_jobs WHERE request_id=ANY($1::uuid[]))', [requests]);
    await pool.query('DELETE FROM app_package_operations WHERE app_id=$1', [appId]);
    await pool.query('DELETE FROM retention_jobs WHERE request_id=ANY($1::uuid[])', [requests]);
    await pool.end(); await rm(root, { recursive: true, force: true });
  });
  const now = Date.now();
  const audit = { record: async () => {} };
  const cleaner = new PostgresPackageRetention({ pool, store: new DiskPackageStore(root), audit });
  const retention = new PostgresRetentionRepository(pool, { audit, clock: () => now, packageRetention: cleaner });
  const originalPreview = await retention.preview();
  const oldJob = await retention.createJob({ previewDigest: previewDigest(originalPreview), cutoffAt: originalPreview.cutoffAt, confirmed: true, requestId: requests[0] });
  for (let i = 0; i < 2; i += 1) await pool.query("INSERT INTO app_package_operations(operation_id,app_id,request_id,action,state,package_digest,occurred_at) VALUES($1,$2,$3,'install','rolled_back',$4,$5)", [randomUUID(), appId, randomUUID(), `sha256:${createHash('sha256').update(`${appId}:${i}`).digest('hex')}`, new Date(now - 31 * 86400000)]);
  await assert.rejects(retention.runJob(oldJob.jobId, 1), { message: 'retention_preview_conflict' });
  const preview = await retention.preview();
  const job = await retention.createJob({ previewDigest: previewDigest(preview), cutoffAt: preview.cutoffAt, confirmed: true, requestId: requests[1] });
  const first = await retention.runJob(job.jobId, 1);
  assert.equal(first.state, 'running'); assert.equal(first.deletedCount, 1);
  const second = await retention.runJob(job.jobId, 1);
  assert.equal(second.state, 'completed'); assert.equal(second.deletedCount, 2);
});

test('unpublished failure audit protects record and cleanup writes transactional outbox', { concurrency: false, skip: !process.env.DGOS_DATABASE_URL }, async (t) => {
  if (!permitted) throw new Error('isolated_retention_database_required');
  const pool = new pg.Pool({ connectionString: process.env.DGOS_DATABASE_URL });
  const root = await mkdtemp(join(tmpdir(), 'dgos-retention-outbox-'));
  const appId = `com.example.retention${randomUUID().replaceAll('-', '')}`;
  const failureRequestId = randomUUID(); const jobRequestId = randomUUID(); const operationId = randomUUID();
  t.after(async () => {
    await pool.query('DELETE FROM app_package_cleanup_intents WHERE item_id=$1', [operationId]);
    await pool.query('DELETE FROM app_package_operations WHERE operation_id=$1', [operationId]);
    await pool.query('DELETE FROM retention_jobs WHERE request_id=$1', [jobRequestId]);
    await pool.query('DELETE FROM audit_outbox WHERE event_id IN (SELECT event_id FROM audit_events WHERE request_id IN ($1,$2))', [failureRequestId, jobRequestId]);
    await pool.query('DELETE FROM audit_events WHERE request_id IN ($1,$2)', [failureRequestId, jobRequestId]);
    await pool.end(); await rm(root, { recursive: true, force: true });
  });
  const audit = new PostgresAuditRepository(pool);
  const cleaner = new PostgresPackageRetention({ pool, store: new DiskPackageStore(root), audit });
  const retention = new PostgresRetentionRepository(pool, { audit, packageRetention: cleaner });
  const failureEventId = await audit.record({ requestId: failureRequestId, action: 'app.install.failed', targetType: 'app', summary: { appId } });
  await pool.query("INSERT INTO app_package_operations(operation_id,app_id,request_id,action,state,package_digest,occurred_at) VALUES($1,$2,$3,'install','rolled_back',$4,now()-interval '31 days')", [operationId, appId, failureRequestId, `sha256:${createHash('sha256').update(appId).digest('hex')}`]);
  const protectedPreview = await retention.preview();
  assert.equal(protectedPreview.packageRetention.failedInstall.protectedCount, 1);
  await pool.query('UPDATE audit_outbox SET published_at=now() WHERE event_id=$1', [failureEventId]);
  const preview = await retention.preview();
  assert.equal(preview.packageRetention.failedInstall.eligibleCount, 1);
  const job = await retention.createJob({ previewDigest: previewDigest(preview), cutoffAt: preview.cutoffAt, confirmed: true, requestId: jobRequestId });
  const done = await retention.runJob(job.jobId);
  assert.equal(done.deletedCount, 1);
  const outbox = await pool.query("SELECT count(*)::int AS count FROM audit_events e JOIN audit_outbox o ON o.event_id=e.event_id WHERE e.request_id=$1 AND e.action='governance.retention.package.removed' AND o.published_at IS NULL", [jobRequestId]);
  assert.equal(outbox.rows[0].count, 1);
});
