import test from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { PostgresAiTaskRepository } from '../../src/ai-task/repository.mjs';
import { AiTaskService } from '../../src/ai-task/service.mjs';
import { createOpenAiCompatibleAdapter } from '../../src/provider-adapters/openai-compatible.mjs';
import { normalizeTextExecution } from '../../src/provider-config/text-parameters.mjs';
import { PostgresQuotaRepository } from '../../src/quota/repository.mjs';
import { QuotaService, createQuotaAdapter } from '../../src/quota/service.mjs';
import { PostgresAuditRepository } from '../../src/audit/outbox.mjs';
import { isAiTaskRegressionParent, isolatedAiTaskDatabase } from '../../test-support/ai-task-regression.mjs';

test('submission rollback, atomic terminal facts, and uncertain dispatch fence', async (t) => {
  if (!isAiTaskRegressionParent(process.env.DGOS_DATABASE_URL)) {
    t.skip('requires dedicated dgos_v1_task or Verify database'); return;
  }
  const database = await isolatedAiTaskDatabase(process.env.DGOS_DATABASE_URL);
  t.after(() => database.cleanup());
  const { pool } = database;
  const ownerId = randomUUID(); const accountId = randomUUID(); const configId = randomUUID();
  const repo = new PostgresAiTaskRepository(pool);
  const auditRepository = new PostgresAuditRepository(pool);
  const failAudit = new Set();
  const audit = { record: async (event, client) => {
    if (failAudit.delete(event.action)) throw new Error('injected_audit_failure');
    return auditRepository.record(event, client);
  } };
  const quota = createQuotaAdapter(new QuotaService({ repository: new PostgresQuotaRepository(pool, { audit }) }));
  const requestIds = [randomUUID(), randomUUID(), randomUUID()];
  const taskIds = [];
  await pool.query("INSERT INTO admin_principals(principal_id,status,credential_ref) VALUES($1,'invited','atomic-test')", [ownerId]);
  await pool.query("INSERT INTO provider_accounts(account_id,owner_type,owner_id,protocol_type,display_name,credential_ref,scope,state) VALUES($1,'admin',$2,'openai-compatible','atomic-test','secret-ref','{}','ready')", [accountId, ownerId]);
  await pool.query("INSERT INTO provider_configs(provider_config_id,owner_id,provider_account_id,protocol_type,display_name,base_url,status,protocol_version,descriptor_version,request_id) VALUES($1,$2,$3,'openai-compatible','atomic-test','https://example.test/v1','ready','v1','text.v1',$4)", [configId, ownerId, accountId, randomUUID()]);
  const config = { providerConfigId: configId, providerAccountId: accountId, ownerId, protocolType: 'openai-compatible', protocolVersion: 'v1', descriptorVersion: 'text.v1', version: '1' };
  const account = { accountId, ownerId, version: '1', _secretRef: 'secret-ref' };
  await pool.query("INSERT INTO model_policies(provider_config_id,model_id,enabled,assigned_capabilities,default_for,classification_source) VALUES($1,'text-model',true,'[\"text\"]','[]','user')", [configId]);
  let providerCalls = 0; let admissionOpen = true;
  const adapter = { ...createOpenAiCompatibleAdapter(), streamText: async function* () { providerCalls += 1; yield 'done'; } };
  const registry = { get: () => adapter };
  const policy = { modelId: 'text-model', enabled: true, assignedCapabilities: ['text'], policyVersion: '1' };
  const admission = async ({ parameters, input }) => admissionOpen ? ({
    config, account, model: { modelId: 'text-model', sourceDigest: 'atomic-fixture-model' }, policy,
    catalogVersion: '1', adapterDescriptor: adapter.descriptor(),
    execution: normalizeTextExecution({ adapter, parameters, input }),
  }) : undefined;
  const service = new AiTaskService({ repository: repo, configService: { repository: { get: async () => config, listPolicies: async () => [policy] } }, accountRepository: { getAccount: async () => account }, secretService: { resolve: async () => ({ read: async () => 'test-secret' }) }, registry, quota, audit, admission, dispatch: async () => {} });
  const submit = (requestId) => service.submit({ ownerId, requestId, target: 'text', intent: 'text.chat', input: { text: 'hello' }, options: { providerConfigId: configId, modelId: 'text-model' } });
  try {
    await assert.rejects(() => submit(requestIds[0]), /quota_exceeded/);
    const denied = await pool.query('SELECT count(*)::int AS n FROM ai_tasks WHERE owner_id=$1', [ownerId]);
    assert.equal(denied.rows[0].n, 0);
    await pool.query("INSERT INTO quota_policies(policy_id,scope_type,scope_id,metric,window_seconds,hard_limit,soft_limit,version,effective_at) VALUES($1,'subject',$2,'requests',3600,2,2,1,now())", [randomUUID(), ownerId]);
    failAudit.add('ai.task.submit');
    await assert.rejects(() => submit(randomUUID()), /injected_audit_failure/);
    assert.equal((await pool.query('SELECT count(*)::int AS n FROM ai_tasks WHERE owner_id=$1', [ownerId])).rows[0].n, 0);
    assert.equal((await pool.query('SELECT count(*)::int AS n FROM quota_reservations WHERE subject_id=$1', [ownerId])).rows[0].n, 0);
    const stateWriter = await pool.connect();
    try {
      await stateWriter.query('BEGIN');
      await stateWriter.query('SELECT account_id FROM provider_accounts WHERE account_id=$1 FOR UPDATE', [accountId]);
      const racingSubmit = submit(randomUUID());
      await new Promise((resolve) => setTimeout(resolve, 30));
      await stateWriter.query("UPDATE provider_accounts SET state='disabled' WHERE account_id=$1", [accountId]);
      await stateWriter.query('COMMIT');
      await assert.rejects(racingSubmit, /provider_unavailable/);
      assert.equal((await pool.query('SELECT count(*)::int AS n FROM ai_tasks WHERE owner_id=$1', [ownerId])).rows[0].n, 0);
      await pool.query("UPDATE provider_accounts SET state='ready' WHERE account_id=$1", [accountId]);
      await stateWriter.query('BEGIN');
      await stateWriter.query('SELECT provider_config_id FROM provider_configs WHERE provider_config_id=$1 FOR UPDATE', [configId]);
      const configRace = submit(randomUUID());
      await new Promise((resolve) => setTimeout(resolve, 30));
      await stateWriter.query("UPDATE provider_configs SET status='disabled' WHERE provider_config_id=$1", [configId]);
      await stateWriter.query('COMMIT');
      await assert.rejects(configRace, /provider_unavailable/);
      await pool.query("UPDATE provider_configs SET status='ready' WHERE provider_config_id=$1", [configId]);
    } finally { stateWriter.release(); }
    const accepted = await submit(requestIds[1]); taskIds.push(accepted.taskId);
    const replay = await submit(requestIds[1]); assert.equal(replay.taskId, accepted.taskId);
    const attempt = await repo.claimAttempt('atomic-worker');
    assert.equal(attempt.taskId, accepted.taskId);
    await service.run(accepted.taskId, 'hello', ownerId, { attempt, workerId: 'atomic-worker', isLeaseValid: () => true });
    assert.equal((await repo.getTask(accepted.taskId)).status, 'succeeded');
    const result = await pool.query('SELECT (SELECT count(*) FROM artifacts WHERE task_id=$1)::int AS artifacts,(SELECT count(*) FROM usage_events WHERE task_id=$1)::int AS usage,(SELECT count(*) FROM ai_task_events WHERE task_id=$1 AND event_type=$2)::int AS terminal', [accepted.taskId, 'task.completed']);
    assert.deepEqual(result.rows[0], { artifacts: 1, usage: 1, terminal: 1 });
    const audited = await pool.query("SELECT action,count(*)::int AS n FROM audit_events WHERE target_id=$1 GROUP BY action ORDER BY action", [accepted.taskId]);
    assert.deepEqual(audited.rows, [{ action: 'ai.task.complete', n: 1 }, { action: 'ai.task.submit', n: 1 }]);
    assert.equal((await pool.query('SELECT count(*)::int AS n FROM audit_outbox WHERE event_id IN (SELECT event_id FROM audit_events WHERE target_id=$1)', [accepted.taskId])).rows[0].n, 2);
    const cancelled = await submit(requestIds[2]); taskIds.push(cancelled.taskId);
    const cancelRace = await Promise.all([service.cancel(cancelled.taskId, ownerId, randomUUID()), repo.claimAttempt('cancel-race-worker')]);
    const raceAttempt = cancelRace[1];
    if (raceAttempt?.taskId === cancelled.taskId) await service.run(cancelled.taskId, 'hello', ownerId, { attempt: raceAttempt, workerId: 'cancel-race-worker', isLeaseValid: () => true });
    assert.equal((await repo.getTask(cancelled.taskId)).status, 'cancelled');
    assert.equal((await pool.query('SELECT state FROM quota_reservations WHERE task_id=$1', [cancelled.taskId])).rows[0].state, 'released');
    assert.equal((await pool.query('SELECT count(*)::int AS n FROM usage_events WHERE task_id=$1', [cancelled.taskId])).rows[0].n, 0);
    const cancelFailure = await submit(randomUUID()); taskIds.push(cancelFailure.taskId);
    failAudit.add('ai.task.fail');
    await assert.rejects(() => service.cancel(cancelFailure.taskId, ownerId, randomUUID()), /injected_audit_failure/);
    assert.equal((await repo.getTask(cancelFailure.taskId)).status, 'accepted');
    assert.equal((await pool.query('SELECT state FROM quota_reservations WHERE task_id=$1', [cancelFailure.taskId])).rows[0].state, 'reserved');
    assert.equal((await pool.query("SELECT count(*)::int AS n FROM ai_task_events WHERE task_id=$1 AND event_type='task.cancelled'", [cancelFailure.taskId])).rows[0].n, 0);
    await service.cancel(cancelFailure.taskId, ownerId, randomUUID());
    assert.equal((await pool.query('SELECT state FROM quota_reservations WHERE task_id=$1', [cancelFailure.taskId])).rows[0].state, 'released');
    const claimedFirstRequestId = randomUUID(); requestIds.push(claimedFirstRequestId);
    const claimedFirst = await submit(claimedFirstRequestId); taskIds.push(claimedFirst.taskId);
    const claimedBeforeCancel = await repo.claimAttempt('claimed-first-worker');
    assert.equal(claimedBeforeCancel.taskId, claimedFirst.taskId);
    await service.cancel(claimedFirst.taskId, ownerId, randomUUID());
    await service.run(claimedFirst.taskId, 'hello', ownerId, { attempt: claimedBeforeCancel, workerId: 'claimed-first-worker', isLeaseValid: () => true });
    assert.equal((await repo.getTask(claimedFirst.taskId)).status, 'cancelled');
    assert.equal((await pool.query('SELECT state FROM quota_reservations WHERE task_id=$1', [claimedFirst.taskId])).rows[0].state, 'released');
    const extraRequestId = randomUUID(); requestIds.push(extraRequestId);
    const uncertain = await submit(extraRequestId); taskIds.push(uncertain.taskId);
    await assert.rejects(() => submit(randomUUID()), /quota_exceeded/);
    const claimed = await repo.claimAttempt('crashed-worker');
    assert.equal(claimed.taskId, uncertain.taskId);
    await repo.markUpstreamDispatch(claimed.attemptId, 'crashed-worker');
    await pool.query("UPDATE ai_task_attempts SET lease_until=now()-interval '1 second' WHERE attempt_id=$1", [claimed.attemptId]);
    const reclaimed = await repo.claimAttempt('recovery-worker');
    await service.run(uncertain.taskId, 'hello', ownerId, { attempt: reclaimed, workerId: 'recovery-worker', isLeaseValid: () => true });
    assert.equal(providerCalls, 1);
    assert.deepEqual((await repo.getTask(uncertain.taskId)).error, { errorKey: 'upstream_outcome_unknown' });
    const review = await pool.query('SELECT state FROM quota_reservations WHERE task_id=$1', [uncertain.taskId]);
    assert.equal(review.rows[0].state, 'needs_review');
    await pool.query("INSERT INTO quota_policies(policy_id,scope_type,scope_id,metric,window_seconds,hard_limit,soft_limit,version,effective_at) VALUES($1,'subject',$2,'requests',3600,4,4,2,now())", [randomUUID(), ownerId]);
    const auditFailureRequestId = randomUUID();
    const auditFailure = await submit(auditFailureRequestId); taskIds.push(auditFailure.taskId);
    const auditFailureAttempt = await repo.claimAttempt('audit-failure-worker');
    failAudit.add('ai.task.complete');
    await assert.rejects(() => service.run(auditFailure.taskId, 'hello', ownerId, { attempt: auditFailureAttempt, workerId: 'audit-failure-worker', isLeaseValid: () => true }), /injected_audit_failure/);
    assert.equal((await repo.getTask(auditFailure.taskId)).status, 'running');
    assert.equal((await pool.query('SELECT count(*)::int AS n FROM artifacts WHERE task_id=$1', [auditFailure.taskId])).rows[0].n, 0);
    assert.equal((await pool.query('SELECT count(*)::int AS n FROM usage_events WHERE task_id=$1', [auditFailure.taskId])).rows[0].n, 0);
    assert.equal((await pool.query("SELECT count(*)::int AS n FROM audit_events WHERE target_id=$1 AND action='ai.task.complete'", [auditFailure.taskId])).rows[0].n, 0);
    await pool.query("UPDATE ai_task_attempts SET lease_until=now()-interval '1 second' WHERE attempt_id=$1", [auditFailureAttempt.attemptId]);
    const auditFailureRecovery = await repo.claimAttempt('audit-recovery-worker');
    await service.run(auditFailure.taskId, 'hello', ownerId, { attempt: auditFailureRecovery, workerId: 'audit-recovery-worker', isLeaseValid: () => true });
    assert.deepEqual((await repo.getTask(auditFailure.taskId)).error, { errorKey: 'upstream_outcome_unknown' });
    assert.equal(providerCalls, 2);
    assert.equal((await pool.query('SELECT state FROM quota_reservations WHERE task_id=$1', [auditFailure.taskId])).rows[0].state, 'needs_review');
    const disabledRequestId = randomUUID();
    const disabled = await submit(disabledRequestId); taskIds.push(disabled.taskId);
    const disabledAttempt = await repo.claimAttempt('disabled-worker');
    admissionOpen = false;
    await service.run(disabled.taskId, 'hello', ownerId, { attempt: disabledAttempt, workerId: 'disabled-worker', isLeaseValid: () => true });
    assert.equal((await repo.getTask(disabled.taskId)).status, 'failed');
    assert.equal((await pool.query('SELECT state FROM quota_reservations WHERE task_id=$1', [disabled.taskId])).rows[0].state, 'released');
    assert.equal(providerCalls, 2);
    admissionOpen = true;
    // One settled request and both uncertain dispatches still consume quota.
    // Give the independent reconciliation scenario room for exactly two more.
    assert.equal((await pool.query("SELECT count(*)::int AS n FROM quota_reservations WHERE subject_id=$1 AND state IN ('settled','needs_review')", [ownerId])).rows[0].n, 3);
    await pool.query("INSERT INTO quota_policies(policy_id,scope_type,scope_id,metric,window_seconds,hard_limit,soft_limit,version,effective_at) VALUES($1,'subject',$2,'requests',3600,5,5,3,now())", [randomUUID(), ownerId]);
    const reconRequestA = randomUUID(); const reconRequestB = randomUUID();
    const preDispatch = await submit(reconRequestA); taskIds.push(preDispatch.taskId);
    const dispatched = await submit(reconRequestB); taskIds.push(dispatched.taskId);
    await pool.query("UPDATE ai_tasks SET state='failed' WHERE task_id=ANY($1::uuid[])", [[preDispatch.taskId, dispatched.taskId]]);
    await pool.query("UPDATE ai_task_attempts SET upstream_dispatch_started_at=now() WHERE task_id=$1", [dispatched.taskId]);
    await pool.query("UPDATE quota_reservations SET expires_at=now()-interval '1 second' WHERE task_id=ANY($1::uuid[])", [[preDispatch.taskId, dispatched.taskId]]);
    const reconciliation = await quota.reconcile({ checkpointName: `atomic-${ownerId}`, subjectId: ownerId });
    assert.equal(reconciliation.repaired, 2);
    assert.equal(reconciliation.needsReview, 1);
    const reconciled = await pool.query('SELECT task_id,state FROM quota_reservations WHERE task_id=ANY($1::uuid[])', [[preDispatch.taskId, dispatched.taskId]]);
    assert.equal(new Map(reconciled.rows.map((row) => [row.task_id, row.state])).get(preDispatch.taskId), 'released');
    assert.equal(new Map(reconciled.rows.map((row) => [row.task_id, row.state])).get(dispatched.taskId), 'needs_review');
    const replaySettle = await quota.settle({ subjectId: ownerId, requestId: reconRequestA, reservationId: (await pool.query('SELECT reservation_id FROM quota_reservations WHERE task_id=$1', [preDispatch.taskId])).rows[0].reservation_id, taskId: preDispatch.taskId, attemptId: (await repo.findAttemptByTask(preDispatch.taskId)).attemptId, terminalState: 'completed', amount: 1, usageStatus: 'final' });
    assert.equal(replaySettle.usageEventId, undefined);
  } finally {
    await pool.query('DELETE FROM audit_outbox WHERE event_id IN (SELECT event_id FROM audit_events WHERE actor_id=$1)', [ownerId]);
    await pool.query('DELETE FROM audit_events WHERE actor_id=$1', [ownerId]);
    await pool.query('DELETE FROM usage_events WHERE task_id=ANY($1::uuid[])', [taskIds]);
    await pool.query('DELETE FROM quota_reconciliation_items WHERE task_id=ANY($1::uuid[])', [taskIds]);
    await pool.query('DELETE FROM quota_reservations WHERE task_id=ANY($1::uuid[])', [taskIds]);
    await pool.query('DELETE FROM artifacts WHERE task_id=ANY($1::uuid[])', [taskIds]);
    await pool.query('DELETE FROM ai_task_events WHERE task_id=ANY($1::uuid[])', [taskIds]);
    await pool.query('DELETE FROM ai_task_attempts WHERE task_id=ANY($1::uuid[])', [taskIds]);
    await pool.query('DELETE FROM ai_tasks WHERE task_id=ANY($1::uuid[])', [taskIds]);
    await pool.query('DELETE FROM quota_policies WHERE scope_id=$1', [ownerId]);
    await pool.query('DELETE FROM quota_reconciliation_checkpoints WHERE checkpoint_name=$1', [`atomic-${ownerId}`]);
    await pool.query('DELETE FROM model_policies WHERE provider_config_id=$1', [configId]);
    await pool.query('DELETE FROM provider_configs WHERE provider_config_id=$1', [configId]);
    await pool.query('DELETE FROM provider_accounts WHERE account_id=$1', [accountId]);
    await pool.query('DELETE FROM admin_principals WHERE principal_id=$1', [ownerId]);
  }
});
