import { randomUUID } from 'node:crypto';
const terminal = new Set(['succeeded', 'failed', 'cancelled', 'timed_out']);
export class InMemoryAiTaskRepository {
  tasks = new Map(); attempts = new Map(); events = new Map(); artifacts = new Map();
  async findByRequest(ownerId, requestId, inputDigest) { const prior = [...this.tasks.values()].find((t) => t.ownerId === ownerId && t.requestId === requestId); if (prior && prior.inputDigest !== inputDigest) throw Object.assign(new Error('version_conflict'), { errorKey: 'version_conflict', statusCode: 409 }); return prior; }
  async createTask(input) { const task = { taskId: randomUUID(), ...input, status: 'accepted', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), text: '', artifactIds: [], leaseOwner: null, leaseUntil: null, attempts: 0 }; this.tasks.set(task.taskId, task); this.events.set(task.taskId, []); return task; }
  async getTask(taskId) { return this.tasks.get(taskId); }
  async createAttempt(input) { const attempt = { attemptId: randomUUID(), ...input, state: 'queued', createdAt: new Date().toISOString(), leaseOwner: null, leaseUntil: null, attempts: 0 }; this.attempts.set(attempt.attemptId, attempt); return attempt; }
  async findAttemptByTask(taskId) { return [...this.attempts.values()].find((attempt) => attempt.taskId === taskId); }
  async claimAttempt(workerId, leaseMs = 15_000) { const nowMs = Date.now(); const attempt = [...this.attempts.values()].filter((x) => x.state === 'queued' || (x.state === 'running' && (!x.leaseUntil || x.leaseUntil <= nowMs))).sort((a, b) => a.createdAt.localeCompare(b.createdAt))[0]; if (!attempt) return undefined; Object.assign(attempt, { state: 'running', leaseOwner: workerId, leaseUntil: nowMs + leaseMs, attempts: attempt.attempts + 1 }); return { ...attempt }; }
  async renewAttemptLease(attemptId, workerId, leaseMs = 15_000) { const attempt = this.attempts.get(attemptId); if (!attempt || attempt.state !== 'running' || attempt.leaseOwner !== workerId) return undefined; attempt.leaseUntil = Date.now() + leaseMs; return { ...attempt }; }
  async finishAttempt(attemptId, state, patch = {}, workerId) { const attempt = this.attempts.get(attemptId); if (!attempt || !['queued', 'running'].includes(attempt.state) || workerId && attempt.leaseOwner !== workerId) return undefined; Object.assign(attempt, patch, { state, completedAt: new Date().toISOString(), leaseOwner: null, leaseUntil: null }); return { ...attempt }; }
  async updateAttempt(id, patch) { const a = this.attempts.get(id); if (a) Object.assign(a, patch); return a; }
  async updateAttemptOwned(id, workerId, patch) { const a = this.attempts.get(id); if (!a || a.state !== 'running' || a.leaseOwner !== workerId) return undefined; Object.assign(a, patch); return { ...a }; }
  async getAttempt(id) { const a = this.attempts.get(id); return a && { ...a }; }
  async transition(taskId, status, patch = {}) { const task = this.tasks.get(taskId); if (!task || terminal.has(task.status) || status === 'running' && task.status === 'cancel_requested') return task; Object.assign(task, patch, { status, updatedAt: new Date().toISOString() }); return task; }
  async event(taskId, type, payload = {}) { const list = this.events.get(taskId) ?? []; const event = { eventId: randomUUID(), taskId, sequence: list.length + 1, type, createdAt: new Date().toISOString(), ...payload }; list.push(event); this.events.set(taskId, list); return event; }
  async listEvents(taskId, after = 0) { return (this.events.get(taskId) ?? []).filter((e) => e.sequence > Number(after || 0)).slice(0, 8); }
  async createArtifact(input) { const artifact = { artifactId: randomUUID(), ...input, createdAt: new Date().toISOString() }; this.artifacts.set(artifact.artifactId, artifact); return artifact; }
  async getArtifact(id) { return this.artifacts.get(id); }
}
export class PostgresAiTaskRepository {
  constructor(pool) { this.pool = pool; }
  async createSubmission(input, reserve, audit, recheckAdmission) {
    const client = await this.pool.connect();
    try {
      await client.query('BEGIN');
      await client.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))', [`ai-task-request:${input.ownerId}:${input.requestId}`]);
      const existing = await client.query('SELECT * FROM ai_tasks WHERE owner_id=$1 AND request_id=$2', [input.ownerId, input.requestId]);
      if (existing.rows[0]) {
        if (existing.rows[0].input_digest !== input.inputDigest) throw Object.assign(new Error('version_conflict'), { errorKey: 'version_conflict', statusCode: 409 });
        await client.query('COMMIT'); return { task: this.taskRow(existing.rows[0]), replay: true };
      }
      const taskId = randomUUID(); const attemptId = randomUUID();
      const configRef = await client.query('SELECT provider_account_id FROM provider_configs WHERE provider_config_id=$1', [input.providerConfigId]);
      if (configRef.rows[0]?.provider_account_id !== input.providerAccountId) throw Object.assign(new Error('provider_config_not_found'), { statusCode: 404 });
      const accountLock = await client.query('SELECT owner_id,protocol_type,state FROM provider_accounts WHERE account_id=$1 FOR UPDATE', [input.providerAccountId]);
      const configLock = await client.query('SELECT owner_id,provider_account_id,protocol_type,status FROM provider_configs WHERE provider_config_id=$1 FOR UPDATE', [input.providerConfigId]);
      const account = accountLock.rows[0]; const config = configLock.rows[0];
      if (!account || !config || account.owner_id !== input.ownerId || config.owner_id !== input.ownerId || config.provider_account_id !== input.providerAccountId || account.protocol_type !== config.protocol_type || account.state !== 'ready' || config.status !== 'ready') throw Object.assign(new Error('provider_unavailable'), { statusCode: 422 });
      const admitted = recheckAdmission ? await recheckAdmission(client) : undefined;
      if (recheckAdmission && !admitted?.executionSnapshot) throw Object.assign(new Error('protocol_unavailable'), { errorKey: 'protocol_unavailable' });
      const executionSnapshot = admitted?.executionSnapshot ?? input.executionSnapshot;
      const executionDigest = executionSnapshot?.executionDigest ?? null;
      const { rows } = await client.query('INSERT INTO ai_tasks (task_id,owner_id,request_id,target,intent,model_id,provider_config_id,input_digest,input_text,state,execution_snapshot,execution_digest) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) ON CONFLICT(owner_id,request_id,input_digest) DO NOTHING RETURNING *', [taskId, input.ownerId, input.requestId, input.target, input.intent, input.modelId, input.providerConfigId, input.inputDigest, input.inputText, 'accepted', executionSnapshot ? JSON.stringify(executionSnapshot) : null, executionDigest]);
      if (!rows[0]) throw Object.assign(new Error('version_conflict'), { errorKey: 'version_conflict', statusCode: 409 });
      const attempt = await client.query('INSERT INTO ai_task_attempts (attempt_id,task_id,provider_config_id,provider_account_id,model_id,state) VALUES ($1,$2,$3,$4,$5,$6) RETURNING *', [attemptId, taskId, input.providerConfigId, input.providerAccountId, input.modelId, 'queued']);
      const reservation = await reserve({ taskId, attemptId }, client);
      await client.query('UPDATE ai_task_attempts SET quota_reservation_ref=$2 WHERE attempt_id=$1', [attemptId, reservation.reservationId ?? reservation.reservationRef]);
      await client.query('INSERT INTO ai_task_events (event_id,task_id,sequence,event_type,payload) VALUES ($1,$2,1,$3,$4)', [randomUUID(), taskId, 'task.accepted', '{}']);
      if (!audit?.record) throw new Error('audit_unavailable');
      await audit.record({ requestId: input.requestId, actorId: input.ownerId, action: 'ai.task.submit', targetType: 'ai_task', targetId: taskId, summary: { taskId, modelId: input.modelId, inputDigest: input.inputDigest } }, client);
      await client.query('COMMIT');
      return { task: this.taskRow(rows[0]), attempt: this.attemptRow(attempt.rows[0]), reservation, replay: false };
    } catch (error) { await client.query('ROLLBACK'); throw error; } finally { client.release(); }
  }
  attemptRow(r) { return r && { attemptId: r.attempt_id, taskId: r.task_id, providerConfigId: r.provider_config_id, providerAccountId: r.provider_account_id, modelId: r.model_id, state: r.state, errorClass: r.error_class, quotaReservationRef: r.quota_reservation_ref, upstreamDispatchStartedAt: r.upstream_dispatch_started_at, leaseOwner: r.lease_owner, leaseUntil: r.lease_until, attempts: r.attempts, startedAt: r.started_at, completedAt: r.completed_at }; }
  async findByRequest(ownerId, requestId, inputDigest) { const { rows } = await this.pool.query('SELECT * FROM ai_tasks WHERE owner_id=$1 AND request_id=$2', [ownerId, requestId]); if (rows[0] && rows[0].input_digest !== inputDigest) throw Object.assign(new Error('version_conflict'), { errorKey: 'version_conflict', statusCode: 409 }); return rows[0] && this.taskRow(rows[0]); }
  taskRow(r) { return { taskId: r.task_id, ownerId: r.owner_id, requestId: r.request_id, target: r.target, intent: r.intent, modelId: r.model_id, providerConfigId: r.provider_config_id, inputDigest: r.input_digest, inputText: r.input_text ?? '', executionSnapshot: r.execution_snapshot, executionDigest: r.execution_digest, status: r.state, text: r.text ?? '', artifactIds: r.artifact_ids ?? [], error: r.error, createdAt: r.created_at.toISOString(), updatedAt: r.updated_at.toISOString() }; }
  async createTask(x) { const { rows } = await this.pool.query('INSERT INTO ai_tasks (task_id,owner_id,request_id,target,intent,model_id,provider_config_id,input_digest,input_text,state,execution_snapshot,execution_digest) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) RETURNING *', [x.taskId ?? randomUUID(), x.ownerId, x.requestId, x.target, x.intent, x.modelId, x.providerConfigId, x.inputDigest, x.inputText ?? null, 'accepted', x.executionSnapshot ? JSON.stringify(x.executionSnapshot) : null, x.executionSnapshot?.executionDigest ?? null]); return this.taskRow(rows[0]); }
  async getTask(id) { const { rows } = await this.pool.query('SELECT * FROM ai_tasks WHERE task_id=$1', [id]); return rows[0] && this.taskRow(rows[0]); }
  async createAttempt(x) { const { rows } = await this.pool.query('INSERT INTO ai_task_attempts (attempt_id,task_id,provider_config_id,provider_account_id,model_id,state) VALUES ($1,$2,$3,$4,$5,$6) RETURNING *', [x.attemptId ?? randomUUID(), x.taskId, x.providerConfigId, x.providerAccountId, x.modelId, 'queued']); return this.attemptRow(rows[0]); }
  async findAttemptByTask(taskId) { const { rows } = await this.pool.query('SELECT * FROM ai_task_attempts WHERE task_id=$1 ORDER BY attempt_id LIMIT 1', [taskId]); return this.attemptRow(rows[0]); }
  async claimAttempt(workerId, leaseMs = 15_000) { return this.pool.query("WITH candidate AS (SELECT a.attempt_id FROM ai_task_attempts a WHERE (a.state='queued' OR (a.state='running' AND (a.lease_until IS NULL OR a.lease_until < now()))) AND EXISTS (SELECT 1 FROM audit_events e JOIN audit_outbox o ON o.event_id=e.event_id WHERE e.target_type='ai_task' AND e.target_id=a.task_id::text AND e.action='ai.task.submit') ORDER BY a.attempt_id FOR UPDATE OF a SKIP LOCKED LIMIT 1) UPDATE ai_task_attempts SET state='running', lease_owner=$1, lease_until=now()+($2::int * interval '1 millisecond'), attempts=attempts+1 WHERE attempt_id=(SELECT attempt_id FROM candidate) RETURNING *", [workerId, leaseMs]).then(({ rows }) => this.attemptRow(rows[0])); }
  async renewAttemptLease(attemptId, workerId, leaseMs = 15_000) { const { rows } = await this.pool.query("UPDATE ai_task_attempts SET lease_until=now()+($3::int * interval '1 millisecond') WHERE attempt_id=$1 AND lease_owner=$2 AND state='running' RETURNING *", [attemptId, workerId, leaseMs]); return this.attemptRow(rows[0]); }
  async finishAttempt(attemptId, state, patch = {}, workerId) { const values = [attemptId, state]; const sets = Object.entries(patch).map(([field, value]) => { values.push(value); return `${field.replace(/[A-Z]/g, (m) => `_${m.toLowerCase()}`)}=$${values.length}`; }); let owner = ''; if (workerId) { values.push(workerId); owner = ` AND lease_owner=$${values.length}`; } const { rows } = await this.pool.query(`UPDATE ai_task_attempts SET state=$2,${sets.length ? `${sets.join(',')},` : ''}completed_at=now(),lease_owner=NULL,lease_until=NULL WHERE attempt_id=$1 AND state IN ('queued','running')${owner} RETURNING *`, values); return this.attemptRow(rows[0]); }
  async updateAttempt(id, patch) { const fields = Object.keys(patch); const values = Object.values(patch); const sets = fields.map((f, i) => `${f.replace(/[A-Z]/g, (m) => `_${m.toLowerCase()}`)}=$${i + 2}`).join(','); const { rows } = await this.pool.query(`UPDATE ai_task_attempts SET ${sets} WHERE attempt_id=$1 RETURNING *`, [id, ...values]); return rows[0]; }
  async updateAttemptOwned(id, workerId, patch) { const fields = Object.keys(patch); if (!fields.length) return this.getAttempt(id); const values = Object.values(patch); const sets = fields.map((f, i) => `${f.replace(/[A-Z]/g, (m) => `_${m.toLowerCase()}`)}=$${i + 3}`).join(','); const { rows } = await this.pool.query(`UPDATE ai_task_attempts SET ${sets} WHERE attempt_id=$1 AND lease_owner=$2 AND state='running' RETURNING *`, [id, workerId, ...values]); return rows[0]; }
  async getAttempt(id) { const { rows } = await this.pool.query('SELECT * FROM ai_task_attempts WHERE attempt_id=$1', [id]); return this.attemptRow(rows[0]); }
  async markUpstreamDispatch(attemptId, workerId, recheckAdmission) { const client = await this.pool.connect(); try { await client.query('BEGIN'); if (recheckAdmission) { const { rows: refs } = await client.query('SELECT provider_account_id,provider_config_id FROM ai_task_attempts WHERE attempt_id=$1', [attemptId]); if (!refs[0]) { await client.query('COMMIT'); return undefined; } await client.query('SELECT account_id FROM provider_accounts WHERE account_id=$1 FOR UPDATE', [refs[0].provider_account_id]); await client.query('SELECT provider_config_id FROM provider_configs WHERE provider_config_id=$1 FOR UPDATE', [refs[0].provider_config_id]); await recheckAdmission(client); } const task = await client.query("SELECT t.state FROM ai_tasks t WHERE t.task_id=(SELECT task_id FROM ai_task_attempts WHERE attempt_id=$1) AND EXISTS (SELECT 1 FROM audit_events e JOIN audit_outbox o ON o.event_id=e.event_id WHERE e.target_type='ai_task' AND e.target_id=t.task_id::text AND e.action='ai.task.submit') FOR UPDATE", [attemptId]); if (!task.rows[0] || ['cancel_requested','cancelled','failed','succeeded','timed_out'].includes(task.rows[0].state)) { await client.query('COMMIT'); return undefined; } const { rows } = await client.query("UPDATE ai_task_attempts SET upstream_dispatch_started_at=COALESCE(upstream_dispatch_started_at,now()) WHERE attempt_id=$1 AND lease_owner=$2 AND state='running' RETURNING *", [attemptId, workerId]); await client.query('COMMIT'); return this.attemptRow(rows[0]); } catch (error) { await client.query('ROLLBACK'); throw error; } finally { client.release(); } }
  async completeAttempt({ attemptId, workerId, state, errorKey, text = '', ownerId, usageStatus = 'unavailable', usage, release = false, uncertain = false, onlyQueued = false, audit }) {
    const client = await this.pool.connect();
    try {
      await client.query('BEGIN');
      const taskResult = await client.query('SELECT * FROM ai_tasks WHERE task_id=(SELECT task_id FROM ai_task_attempts WHERE attempt_id=$1) FOR UPDATE', [attemptId]);
      const locked = await client.query('SELECT * FROM ai_task_attempts WHERE attempt_id=$1 FOR UPDATE', [attemptId]);
      const attempt = locked.rows[0];
      if (!attempt || !['queued', 'running'].includes(attempt.state) || (onlyQueued && attempt.state !== 'queued') || (workerId && attempt.lease_owner !== workerId)) { await client.query('COMMIT'); return undefined; }
      const task = taskResult.rows[0];
      if (!task || terminal.has(task.state)) { await client.query('COMMIT'); return undefined; }
      let artifactId;
      if (state === 'succeeded') {
        artifactId = randomUUID();
        await client.query('INSERT INTO artifacts(artifact_id,task_id,owner_id,mime_type,content) VALUES($1,$2,$3,$4,$5)', [artifactId, attempt.task_id, ownerId, 'text/plain', text]);
      }
      if (attempt.quota_reservation_ref) {
        const reservation = await client.query('SELECT * FROM quota_reservations WHERE reservation_id=$1 FOR UPDATE', [attempt.quota_reservation_ref]);
        if (!reservation.rows[0]) throw new Error('reservation_not_found');
        const targetState = uncertain ? 'needs_review' : release ? 'released' : 'settled';
        await client.query("UPDATE quota_reservations SET state=$2,updated_at=now() WHERE reservation_id=$1 AND state='reserved'", [attempt.quota_reservation_ref, targetState]);
        if (!release && !uncertain) await client.query(`INSERT INTO usage_events(usage_event_id,request_id,subject_id,provider_account_id,provider_config_id,model_ref,task_id,attempt_id,metric,amount,unit,usage_status,estimated,input_tokens,output_tokens,total_tokens,estimated_cost,source_digest,operation,occurred_at,reservation_id,window_start) VALUES($1,$2,$3,$4,$5,$6,$7,$8,'requests',1,'count',$9,$10,$11,$12,$13,$14,$15,'ai.task',now(),$16,$17) ON CONFLICT(task_id,attempt_id,metric) DO NOTHING`, [randomUUID(), task.request_id, task.owner_id, attempt.provider_account_id, attempt.provider_config_id, attempt.model_id, task.task_id, attemptId, usageStatus, Boolean(usage?.estimated), usage?.inputTokens ?? null, usage?.outputTokens ?? null, usage?.totalTokens ?? null, usage?.estimatedCost ?? null, usage?.sourceDigest ?? null, attempt.quota_reservation_ref, reservation.rows[0].window_start]);
      }
      await client.query('UPDATE ai_task_attempts SET state=$2,error_class=$3,completed_at=now(),lease_owner=NULL,lease_until=NULL WHERE attempt_id=$1', [attemptId, state, errorKey ?? null]);
      const updated = await client.query('UPDATE ai_tasks SET state=$2,text=$3,error=$4,artifact_ids=$5,updated_at=now() WHERE task_id=$1 RETURNING *', [task.task_id, state, text, errorKey ? JSON.stringify({ errorKey }) : null, JSON.stringify(artifactId ? [artifactId] : [])]);
      const eventType = state === 'succeeded' ? 'task.completed' : state === 'cancelled' ? 'task.cancelled' : 'task.failed';
      const snapshot = { taskId: task.task_id, status: state, text: text || undefined, artifactIds: artifactId ? [artifactId] : [], error: errorKey ? { errorKey } : undefined };
      await client.query('INSERT INTO ai_task_events(event_id,task_id,sequence,event_type,payload) VALUES($1,$2,COALESCE((SELECT MAX(sequence)+1 FROM ai_task_events WHERE task_id=$2),1),$3,$4)', [randomUUID(), task.task_id, eventType, JSON.stringify({ snapshot })]);
      if (!audit?.record) throw new Error('audit_unavailable');
      await audit.record({ requestId: task.request_id, actorId: ownerId ?? task.owner_id, action: state === 'succeeded' ? 'ai.task.complete' : 'ai.task.fail', targetType: 'ai_task', targetId: task.task_id, result: state === 'succeeded' ? 'succeeded' : 'failed', summary: { taskId: task.task_id, attemptId, errorClass: errorKey ?? undefined } }, client);
      await client.query('COMMIT');
      return { task: this.taskRow(updated.rows[0]), artifactId };
    } catch (error) { await client.query('ROLLBACK'); throw error; } finally { client.release(); }
  }
  async transition(id, status, patch = {}) { const map = { text: patch.text ?? null, error: patch.error ? JSON.stringify(patch.error) : null, artifact_ids: patch.artifactIds ? JSON.stringify(patch.artifactIds) : null }; const { rows } = await this.pool.query("UPDATE ai_tasks SET state=$2,text=COALESCE($3,text),error=$4,artifact_ids=COALESCE($5,artifact_ids),updated_at=now() WHERE task_id=$1 AND state NOT IN ('succeeded','failed','cancelled','timed_out') AND NOT (state='cancel_requested' AND $2='running') RETURNING *", [id, status, map.text, map.error, map.artifact_ids]); return rows[0] && this.taskRow(rows[0]); }
  async event(taskId, type, payload = {}) { const client = await this.pool.connect(); try { await client.query('BEGIN'); await client.query('SELECT task_id FROM ai_tasks WHERE task_id=$1 FOR UPDATE', [taskId]); const { rows } = await client.query('INSERT INTO ai_task_events (event_id,task_id,sequence,event_type,payload) VALUES ($1,$2,COALESCE((SELECT MAX(sequence)+1 FROM ai_task_events WHERE task_id=$2),1),$3,$4) RETURNING *', [randomUUID(), taskId, type, JSON.stringify(payload)]); await client.query('COMMIT'); return { eventId: rows[0].event_id, taskId, sequence: rows[0].sequence, type: rows[0].event_type, ...payload, createdAt: rows[0].created_at.toISOString() }; } catch (e) { await client.query('ROLLBACK'); throw e; } finally { client.release(); } }
  async listEvents(taskId, after = 0) { const { rows } = await this.pool.query('SELECT * FROM ai_task_events WHERE task_id=$1 AND sequence>$2 ORDER BY sequence LIMIT 8', [taskId, Number(after)]); return rows.map((r) => ({ eventId: r.event_id, taskId, sequence: r.sequence, type: r.event_type, ...r.payload, createdAt: r.created_at.toISOString() })); }
  async createArtifact(x) { const { rows } = await this.pool.query('INSERT INTO artifacts (artifact_id,task_id,owner_id,mime_type,content) VALUES ($1,$2,$3,$4,$5) RETURNING *', [randomUUID(), x.taskId, x.ownerId, x.mimeType, x.content]); return { artifactId: rows[0].artifact_id, taskId: rows[0].task_id, ownerId: rows[0].owner_id, mimeType: rows[0].mime_type, content: rows[0].content }; }
  async getArtifact(id) { const { rows } = await this.pool.query('SELECT * FROM artifacts WHERE artifact_id=$1', [id]); return rows[0] && { artifactId: rows[0].artifact_id, taskId: rows[0].task_id, ownerId: rows[0].owner_id, mimeType: rows[0].mime_type, content: rows[0].content }; }
}
