import { randomUUID } from 'node:crypto';
const terminal = new Set(['succeeded', 'failed', 'cancelled', 'timed_out']);
export class InMemoryAiTaskRepository {
  tasks = new Map(); attempts = new Map(); events = new Map(); artifacts = new Map();
  async findByRequest(ownerId, requestId, inputDigest) { return [...this.tasks.values()].find((t) => t.ownerId === ownerId && t.requestId === requestId && t.inputDigest === inputDigest); }
  async createTask(input) { const task = { taskId: randomUUID(), ...input, status: 'accepted', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), text: '', artifactIds: [], leaseOwner: null, leaseUntil: null, attempts: 0 }; this.tasks.set(task.taskId, task); this.events.set(task.taskId, []); return task; }
  async getTask(taskId) { return this.tasks.get(taskId); }
  async createAttempt(input) { const attempt = { attemptId: randomUUID(), ...input, state: 'queued', createdAt: new Date().toISOString(), leaseOwner: null, leaseUntil: null, attempts: 0 }; this.attempts.set(attempt.attemptId, attempt); return attempt; }
  async findAttemptByTask(taskId) { return [...this.attempts.values()].find((attempt) => attempt.taskId === taskId); }
  async claimAttempt(workerId, leaseMs = 15_000) { const nowMs = Date.now(); const attempt = [...this.attempts.values()].filter((x) => x.state === 'queued' || (x.state === 'running' && (!x.leaseUntil || x.leaseUntil <= nowMs))).sort((a, b) => a.createdAt.localeCompare(b.createdAt))[0]; if (!attempt) return undefined; Object.assign(attempt, { state: 'running', leaseOwner: workerId, leaseUntil: nowMs + leaseMs, attempts: attempt.attempts + 1 }); return { ...attempt }; }
  async renewAttemptLease(attemptId, workerId, leaseMs = 15_000) { const attempt = this.attempts.get(attemptId); if (!attempt || attempt.state !== 'running' || attempt.leaseOwner !== workerId) return undefined; attempt.leaseUntil = Date.now() + leaseMs; return { ...attempt }; }
  async finishAttempt(attemptId, state, patch = {}, workerId) { const attempt = this.attempts.get(attemptId); if (!attempt || !['queued', 'running'].includes(attempt.state) || workerId && attempt.leaseOwner !== workerId) return undefined; Object.assign(attempt, patch, { state, completedAt: new Date().toISOString(), leaseOwner: null, leaseUntil: null }); return { ...attempt }; }
  async updateAttempt(id, patch) { const a = this.attempts.get(id); if (a) Object.assign(a, patch); return a; }
  async updateAttemptOwned(id, workerId, patch) { const a = this.attempts.get(id); if (!a || a.state !== 'running' || a.leaseOwner !== workerId) return undefined; Object.assign(a, patch); return { ...a }; }
  async getAttempt(id) { const a = this.attempts.get(id); return a && { ...a }; }
  async transition(taskId, status, patch = {}) { const task = this.tasks.get(taskId); if (!task || terminal.has(task.status)) return task; Object.assign(task, patch, { status, updatedAt: new Date().toISOString() }); return task; }
  async event(taskId, type, payload = {}) { const list = this.events.get(taskId) ?? []; const event = { eventId: randomUUID(), taskId, sequence: list.length + 1, type, createdAt: new Date().toISOString(), ...payload }; list.push(event); this.events.set(taskId, list); return event; }
  async listEvents(taskId, after = 0) { return (this.events.get(taskId) ?? []).filter((e) => e.sequence > Number(after || 0)); }
  async createArtifact(input) { const artifact = { artifactId: randomUUID(), ...input, createdAt: new Date().toISOString() }; this.artifacts.set(artifact.artifactId, artifact); return artifact; }
  async getArtifact(id) { return this.artifacts.get(id); }
}
export class PostgresAiTaskRepository {
  constructor(pool) { this.pool = pool; }
  attemptRow(r) { return r && { attemptId: r.attempt_id, taskId: r.task_id, providerConfigId: r.provider_config_id, providerAccountId: r.provider_account_id, modelId: r.model_id, state: r.state, errorClass: r.error_class, quotaReservationRef: r.quota_reservation_ref, startedAt: r.started_at, completedAt: r.completed_at, leaseOwner: r.lease_owner, leaseUntil: r.lease_until, attempts: r.attempts }; }
  async findByRequest(ownerId, requestId, inputDigest) { const { rows } = await this.pool.query('SELECT * FROM ai_tasks WHERE owner_id=$1 AND request_id=$2 AND input_digest=$3', [ownerId, requestId, inputDigest]); return rows[0] && this.taskRow(rows[0]); }
  taskRow(r) { return { taskId: r.task_id, ownerId: r.owner_id, requestId: r.request_id, target: r.target, intent: r.intent, modelId: r.model_id, providerConfigId: r.provider_config_id, inputDigest: r.input_digest, inputText: r.input_text ?? '', status: r.state, text: r.text ?? '', artifactIds: r.artifact_ids ?? [], error: r.error, createdAt: r.created_at.toISOString(), updatedAt: r.updated_at.toISOString() }; }
  async createTask(x) { const { rows } = await this.pool.query('INSERT INTO ai_tasks (task_id,owner_id,request_id,target,intent,model_id,provider_config_id,input_digest,input_text,state) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING *', [x.taskId ?? randomUUID(), x.ownerId, x.requestId, x.target, x.intent, x.modelId, x.providerConfigId, x.inputDigest, x.inputText ?? null, 'accepted']); return this.taskRow(rows[0]); }
  async getTask(id) { const { rows } = await this.pool.query('SELECT * FROM ai_tasks WHERE task_id=$1', [id]); return rows[0] && this.taskRow(rows[0]); }
  async createAttempt(x) { const { rows } = await this.pool.query('INSERT INTO ai_task_attempts (attempt_id,task_id,provider_config_id,provider_account_id,model_id,state) VALUES ($1,$2,$3,$4,$5,$6) RETURNING *', [x.attemptId ?? randomUUID(), x.taskId, x.providerConfigId, x.providerAccountId, x.modelId, 'queued']); return this.attemptRow(rows[0]); }
  async findAttemptByTask(taskId) { const { rows } = await this.pool.query('SELECT * FROM ai_task_attempts WHERE task_id=$1 ORDER BY attempt_id LIMIT 1', [taskId]); return this.attemptRow(rows[0]); }
  async claimAttempt(workerId, leaseMs = 15_000) { return this.pool.query("WITH candidate AS (SELECT attempt_id FROM ai_task_attempts WHERE (state='queued' OR (state='running' AND (lease_until IS NULL OR lease_until < now()))) ORDER BY attempt_id FOR UPDATE SKIP LOCKED LIMIT 1) UPDATE ai_task_attempts SET state='running', lease_owner=$1, lease_until=now()+($2::int * interval '1 millisecond'), attempts=attempts+1 WHERE attempt_id=(SELECT attempt_id FROM candidate) RETURNING *", [workerId, leaseMs]).then(({ rows }) => this.attemptRow(rows[0])); }
  async renewAttemptLease(attemptId, workerId, leaseMs = 15_000) { const { rows } = await this.pool.query("UPDATE ai_task_attempts SET lease_until=now()+($3::int * interval '1 millisecond') WHERE attempt_id=$1 AND lease_owner=$2 AND state='running' RETURNING *", [attemptId, workerId, leaseMs]); return this.attemptRow(rows[0]); }
  async finishAttempt(attemptId, state, patch = {}, workerId) { const fields = Object.keys(patch); const values = Object.values(patch); const sets = fields.map((f, i) => `${f.replace(/[A-Z]/g, (m) => `_${m.toLowerCase()}`)}=$${i + 3}`).join(','); const owner = workerId ? ' AND lease_owner=$2' : ''; const { rows } = await this.pool.query(`UPDATE ai_task_attempts SET state=$${fields.length + 3},${sets ? `${sets},` : ''}completed_at=now(),lease_owner=NULL,lease_until=NULL WHERE attempt_id=$1${owner} RETURNING *`, [attemptId, ...(workerId ? [workerId] : []), ...values, state]); return this.attemptRow(rows[0]); }
  async updateAttempt(id, patch) { const fields = Object.keys(patch); const values = Object.values(patch); const sets = fields.map((f, i) => `${f.replace(/[A-Z]/g, (m) => `_${m.toLowerCase()}`)}=$${i + 2}`).join(','); const { rows } = await this.pool.query(`UPDATE ai_task_attempts SET ${sets} WHERE attempt_id=$1 RETURNING *`, [id, ...values]); return rows[0]; }
  async updateAttemptOwned(id, workerId, patch) { const fields = Object.keys(patch); if (!fields.length) return this.getAttempt(id); const values = Object.values(patch); const sets = fields.map((f, i) => `${f.replace(/[A-Z]/g, (m) => `_${m.toLowerCase()}`)}=$${i + 3}`).join(','); const { rows } = await this.pool.query(`UPDATE ai_task_attempts SET ${sets} WHERE attempt_id=$1 AND lease_owner=$2 AND state='running' RETURNING *`, [id, workerId, ...values]); return rows[0]; }
  async getAttempt(id) { const { rows } = await this.pool.query('SELECT * FROM ai_task_attempts WHERE attempt_id=$1', [id]); return this.attemptRow(rows[0]); }
  async transition(id, status, patch = {}) { const map = { text: patch.text ?? null, error: patch.error ? JSON.stringify(patch.error) : null, artifact_ids: patch.artifactIds ? JSON.stringify(patch.artifactIds) : null }; const { rows } = await this.pool.query('UPDATE ai_tasks SET state=$2,text=COALESCE($3,text),error=$4,artifact_ids=COALESCE($5,artifact_ids),updated_at=now() WHERE task_id=$1 AND state NOT IN (\'succeeded\',\'failed\',\'cancelled\',\'timed_out\') RETURNING *', [id, status, map.text, map.error, map.artifact_ids]); return rows[0] && this.taskRow(rows[0]); }
  async event(taskId, type, payload = {}) { const client = await this.pool.connect(); try { await client.query('BEGIN'); await client.query('SELECT task_id FROM ai_tasks WHERE task_id=$1 FOR UPDATE', [taskId]); const { rows } = await client.query('INSERT INTO ai_task_events (event_id,task_id,sequence,event_type,payload) VALUES ($1,$2,COALESCE((SELECT MAX(sequence)+1 FROM ai_task_events WHERE task_id=$2),1),$3,$4) RETURNING *', [randomUUID(), taskId, type, JSON.stringify(payload)]); await client.query('COMMIT'); return { eventId: rows[0].event_id, taskId, sequence: rows[0].sequence, type: rows[0].event_type, ...payload, createdAt: rows[0].created_at.toISOString() }; } catch (e) { await client.query('ROLLBACK'); throw e; } finally { client.release(); } }
  async listEvents(taskId, after = 0) { const { rows } = await this.pool.query('SELECT * FROM ai_task_events WHERE task_id=$1 AND sequence>$2 ORDER BY sequence', [taskId, Number(after)]); return rows.map((r) => ({ eventId: r.event_id, taskId, sequence: r.sequence, type: r.event_type, ...r.payload, createdAt: r.created_at.toISOString() })); }
  async createArtifact(x) { const { rows } = await this.pool.query('INSERT INTO artifacts (artifact_id,task_id,owner_id,mime_type,content) VALUES ($1,$2,$3,$4,$5) RETURNING *', [randomUUID(), x.taskId, x.ownerId, x.mimeType, x.content]); return { artifactId: rows[0].artifact_id, taskId: rows[0].task_id, ownerId: rows[0].owner_id, mimeType: rows[0].mime_type, content: rows[0].content }; }
  async getArtifact(id) { const { rows } = await this.pool.query('SELECT * FROM artifacts WHERE artifact_id=$1', [id]); return rows[0] && { artifactId: rows[0].artifact_id, taskId: rows[0].task_id, ownerId: rows[0].owner_id, mimeType: rows[0].mime_type, content: rows[0].content }; }
}
