import { randomUUID } from 'node:crypto';
import { normalizeRequestParameters, normalizeTextExecution, executionDigest } from '../provider-config/text-parameters.mjs';
const safe = (task) => ({ taskId: task.taskId, status: task.status, text: task.text || undefined, artifactIds: task.artifactIds ?? [], error: task.error });
const snapshotFor = (admitted, modelId) => {
  const { config, account, model, policy, catalogVersion, textProfile, declarationDigest, adapterDescriptor, execution } = admitted;
  const core = { executionSnapshotVersion: 1, normalizedParameters: execution.normalizedParameters, resolvedProfile: { protocolType: config.protocolType, adapterVersion: config.protocolVersion, descriptorVersion: config.descriptorVersion, operationProfile: textProfile?.operationProfile ?? 'chat.completions', workflow: textProfile?.workflow ?? 'text.chat', modelId, profileId: textProfile?.profileId ?? 'builtin.text.v1', ...(textProfile ? { protocolId: config.capabilityProtocolId, protocolVersion: config.capabilityProtocolVersion, declarationDigest } : { builtinVersion: config.descriptorVersion, descriptorDigest: executionDigest(adapterDescriptor) }) }, effectiveDefaults: execution.effectiveDefaults, effectiveLimits: execution.effectiveLimits, uiSchemas: execution.uiSchemas, bindingSnapshot: { providerConfigId: config.providerConfigId, configVersion: config.version, providerAccountId: account.accountId, accountVersion: account.version, catalogVersion, modelSourceDigest: model.sourceDigest, policyVersion: policy.policyVersion } };
  return { ...core, executionDigest: executionDigest(core) };
};
const verifySnapshot = (snapshot, admitted, registry, inputText) => {
  if (!admitted?.config || !admitted?.account || !admitted?.model) throw Object.assign(new Error('model_not_allowed'), { errorKey: 'model_not_allowed' });
  if (admitted.config.version !== snapshot.bindingSnapshot.configVersion || admitted.account.version !== snapshot.bindingSnapshot.accountVersion || admitted.config.providerAccountId !== snapshot.bindingSnapshot.providerAccountId || admitted.config.protocolVersion !== snapshot.resolvedProfile.adapterVersion || admitted.catalogVersion !== snapshot.bindingSnapshot.catalogVersion || admitted.policy.policyVersion !== snapshot.bindingSnapshot.policyVersion || admitted.model.sourceDigest !== snapshot.bindingSnapshot.modelSourceDigest) throw Object.assign(new Error('version_conflict'), { errorKey: 'version_conflict' });
  if ((admitted.textProfile?.operationProfile ?? 'chat.completions') !== snapshot.resolvedProfile.operationProfile || admitted.declarationDigest !== snapshot.resolvedProfile.declarationDigest) throw Object.assign(new Error('protocol_unavailable'), { errorKey: 'protocol_unavailable' });
  if ((admitted.textProfile?.profileId ?? 'builtin.text.v1') !== snapshot.resolvedProfile.profileId || (admitted.config.capabilityProtocolId ?? undefined) !== snapshot.resolvedProfile.protocolId || (admitted.config.capabilityProtocolVersion ?? undefined) !== snapshot.resolvedProfile.protocolVersion) throw Object.assign(new Error('protocol_unavailable'), { errorKey: 'protocol_unavailable' });
  if (!admitted.textProfile && snapshot.resolvedProfile.descriptorDigest !== executionDigest(admitted.adapterDescriptor)) throw Object.assign(new Error('version_conflict'), { errorKey: 'version_conflict' });
  normalizeTextExecution({ adapter: registry.get(admitted.config.protocolType), textProfile: admitted.textProfile, parameters: snapshot.normalizedParameters, input: inputText });
};
export class AiTaskService {
  constructor({ repository, configService, accountRepository, secretService, registry, egress, quota, audit, providerRunner, dispatch, admission }) { Object.assign(this, { repository, configService, accountRepository, secretService, registry, egress, quota, audit, providerRunner, dispatch, admission }); this.controllers = new Map(); }
  async submit({ ownerId, requestId, target, intent, input, options = {} }) {
    if (intent !== 'text.chat' || typeof input?.text !== 'string') throw Object.assign(new Error('invalid_request'), { statusCode: 422 });
    if (!options || typeof options !== 'object' || Array.isArray(options) || Object.keys(options).some((key) => !['providerConfigId', 'modelId', 'parameters'].includes(key))) throw Object.assign(new Error('invalid_request'), { errorKey: 'invalid_request', statusCode: 422 });
    const parameters = normalizeRequestParameters(options.parameters);
    if (Object.keys(input).some((key) => key !== 'text')) throw Object.assign(new Error('invalid_request'), { errorKey: 'invalid_request', statusCode: 422 });
    const inputDigest = executionDigest({ target, intent, input, options: { providerConfigId: options.providerConfigId, modelId: options.modelId, parameters } });
    const prior = await this.repository.findByRequest(ownerId, requestId, inputDigest);
    if (prior) return { taskId: prior.taskId, requestId, status: prior.status };
    const admitted = this.admission ? await this.admission({ ownerId, providerConfigId: options.providerConfigId, modelId: options.modelId, intent, parameters, input: input.text }) : null;
    if (this.admission && (!admitted?.config || !admitted?.account || !admitted?.model)) throw Object.assign(new Error('model_not_allowed'), { statusCode: 422 });
    const resolved = admitted?.config ?? (options.providerConfigId ? await this.configService.repository.get(options.providerConfigId) : null);
    if (!resolved || resolved.ownerId !== ownerId) throw Object.assign(new Error('provider_config_not_found'), { statusCode: 404 });
    if (!admitted) { const policies = await this.configService.repository.listPolicies(resolved.providerConfigId); const policy = policies.find((p) => p.modelId === options.modelId && p.enabled && p.assignedCapabilities.includes('text')); if (!policy) throw Object.assign(new Error('model_not_allowed'), { statusCode: 422 }); }
    const account = admitted?.account ?? await this.accountRepository.getAccount(resolved.providerAccountId);
    if (!account) throw Object.assign(new Error('provider_account_not_found'), { statusCode: 404 });
    const executionSnapshot = admitted ? snapshotFor(admitted, options.modelId) : undefined;
    if (this.repository.createSubmission && this.quota?.reserve) {
      const submission = await this.repository.createSubmission({ ownerId, requestId, target, intent, modelId: options.modelId, providerConfigId: resolved.providerConfigId, providerAccountId: account.accountId, inputDigest, inputText: input.text, executionSnapshot }, ({ taskId, attemptId }, client) => this.quota.reserve({ requestId, subjectId: ownerId, taskId, attemptId, scopeType: 'subject', scopeId: ownerId, providerAccountId: account.accountId, providerConfigId: resolved.providerConfigId, modelRef: options.modelId, metric: 'requests', amount: 1 }, client), this.audit, this.admission ? async (client) => ({ executionSnapshot: snapshotFor(await this.admission({ ownerId, providerConfigId: resolved.providerConfigId, modelId: options.modelId, intent, parameters, input: input.text, transactionClient: client }), options.modelId) }) : undefined);
      if (submission.replay) return { taskId: submission.task.taskId, requestId, status: submission.task.status };
      if (this.dispatch) await this.dispatch({ taskId: submission.task.taskId, text: input.text, ownerId });
      return { taskId: submission.task.taskId, requestId, status: 'queued', descriptorVersion: resolved.descriptorVersion };
    }
    if (this.quota?.preflight) await this.quota.preflight({ subjectId: ownerId, intent, metric: 'requests', amount: 1, requestId });
    if (!this.audit?.record) throw new Error('audit_unavailable');
    const taskId = randomUUID();
    await this.audit.record({ requestId, actorId: ownerId, action: 'ai.task.submit', targetType: 'ai_task', targetId: taskId, summary: { taskId, modelId: options.modelId, inputDigest } });
    const task = await this.repository.createTask({ taskId, ownerId, requestId, target, intent, modelId: options.modelId, providerConfigId: resolved.providerConfigId, inputDigest, inputText: input.text, executionSnapshot });
    await this.repository.createAttempt({ taskId: task.taskId, providerConfigId: resolved.providerConfigId, providerAccountId: account.accountId, modelId: options.modelId });
    await this.repository.event(task.taskId, 'task.accepted', {});
    if (this.dispatch) await this.dispatch({ taskId: task.taskId, text: input.text, ownerId });
    else queueMicrotask(() => this.run(task.taskId, input.text, ownerId).catch(() => {}));
    return { taskId: task.taskId, requestId, status: 'queued', descriptorVersion: resolved.descriptorVersion };
  }
  async run(taskId, text, ownerId, options = {}) {
    const task = await this.repository.getTask(taskId);
    if (!task || task.status === 'cancelled') return;
    if (task.status === 'cancel_requested') {
      if (options.attempt && this.repository.completeAttempt) await this.repository.completeAttempt({ attemptId: options.attempt.attemptId, workerId: options.workerId, state: 'cancelled', errorKey: 'cancelled', ownerId, release: !options.attempt.upstreamDispatchStartedAt, uncertain: Boolean(options.attempt.upstreamDispatchStartedAt), audit: this.audit });
      return;
    }
    let attempt = options.attempt; let reservationId = attempt?.quotaReservationRef; let providerStarted = false; let finalized = false; let terminalCommitFailed = false;
    const completeTerminal = async (input) => { try { return await this.repository.completeAttempt({ ...input, audit: this.audit }); } catch (error) { terminalCommitFailed = true; throw error; } };
    const recordTerminal = async (event) => { try { if (!this.audit?.record) throw new Error('audit_unavailable'); await this.audit.record(event); } catch (error) { terminalCommitFailed = true; throw error; } };
    const assertLease = () => { if (options.attempt && options.isLeaseValid && !options.isLeaseValid()) throw Object.assign(new Error('lease_lost'), { errorKey: 'lease_lost' }); };
    const finalizeQuota = async ({ terminalState, usageStatus = 'unavailable', estimated = false, release = false, usage }) => {
      if (finalized || !reservationId || !this.quota) return; finalized = true;
      const input = { requestId: task.requestId, subjectId: task.ownerId, reservationId, taskId, attemptId: attempt.attemptId, terminalState, metric: 'requests', amount: 1, unit: 'count', usageStatus, estimated, operation: 'ai.task', release, inputTokens: usage?.inputTokens ?? null, outputTokens: usage?.outputTokens ?? null, totalTokens: usage?.totalTokens ?? null, estimatedCost: usage?.estimatedCost ?? null, sourceDigest: usage?.sourceDigest ?? null };
      return release && this.quota.release ? this.quota.release(input) : this.quota.settle(input);
    };
    try {
      if (options.attempt?.upstreamDispatchStartedAt) {
        await completeTerminal({ attemptId: attempt.attemptId, workerId: options.workerId, state: 'failed', errorKey: 'upstream_outcome_unknown', ownerId, uncertain: true });
        return;
      }
      const snapshot = task.executionSnapshot;
      if (this.admission && (!snapshot || snapshot.executionSnapshotVersion !== 1 || snapshot.executionDigest !== executionDigest(Object.fromEntries(Object.entries(snapshot).filter(([key]) => key !== 'executionDigest'))))) throw Object.assign(new Error('protocol_unavailable'), { errorKey: 'protocol_unavailable' });
      if (this.admission) {
        const currentAdmission = await this.admission({ ownerId, providerConfigId: task.providerConfigId, modelId: task.modelId, intent: task.intent, input: task.inputText });
        verifySnapshot(snapshot, currentAdmission, this.registry, task.inputText);
      }
      const config = await this.configService.repository.get(task.providerConfigId); if (!config) throw Object.assign(new Error('provider_config_not_found'), { errorKey: 'provider_config_not_found' });
      const account = await this.accountRepository.getAccount(config.providerAccountId); if (!account) throw Object.assign(new Error('provider_account_not_found'), { errorKey: 'provider_account_not_found' });
      const adapter = this.registry.get(config.protocolType); if (!adapter) throw Object.assign(new Error('protocol_unavailable'), { errorKey: 'protocol_unavailable' });
      const handle = await this.secretService.resolve({ secretRef: account._secretRef, purpose: 'provider-account', subjectId: ownerId }); const credential = await handle.read();
      attempt = options.attempt ?? await this.repository.createAttempt({ taskId, providerConfigId: config.providerConfigId, providerAccountId: account.accountId, modelId: task.modelId }); assertLease();
      if (this.quota?.reserve && !reservationId) { const reservation = await this.quota.reserve({ requestId: task.requestId, subjectId: ownerId, taskId, attemptId: attempt.attemptId, scopeType: 'subject', scopeId: ownerId, providerAccountId: account.accountId, providerConfigId: config.providerConfigId, modelRef: task.modelId, metric: 'requests', amount: 1 }); reservationId = reservation.reservationId ?? reservation.reservationRef; if (options.workerId && this.repository.updateAttemptOwned) await this.repository.updateAttemptOwned(attempt.attemptId, options.workerId, { quotaReservationRef: reservationId }); else await this.repository.updateAttempt(attempt.attemptId, { quotaReservationRef: reservationId }); }
      if (!options.attempt) await this.repository.updateAttempt(attempt.attemptId, { state: 'running', startedAt: new Date() });
      await this.repository.transition(taskId, 'running'); await this.repository.event(taskId, 'task.progress', { status: 'running' });
      let output = ''; let providerUsage; const controller = new AbortController(); this.controllers.set(taskId, controller);
      if (options.workerId && this.repository.markUpstreamDispatch && !await this.repository.markUpstreamDispatch(attempt.attemptId, options.workerId, this.admission ? async (client) => verifySnapshot(snapshot, await this.admission({ ownerId, providerConfigId: task.providerConfigId, modelId: task.modelId, intent: task.intent, input: task.inputText, transactionClient: client }), this.registry, task.inputText) : undefined)) { const current = await this.repository.getTask(taskId); if (current?.status === 'cancel_requested') throw Object.assign(new Error('cancelled'), { errorKey: 'cancelled' }); throw Object.assign(new Error('lease_lost'), { errorKey: 'lease_lost' }); }
      const iterator = this.providerRunner ? this.providerRunner({ task, config, account, adapter, credential, egress: this.egress, signal: controller.signal, executionSnapshot: snapshot }) : adapter.streamText({ config, credential, egress: this.egress, modelId: task.modelId, input: task.inputText ?? text, signal: controller.signal, executionSnapshot: snapshot }); providerStarted = true;
      for await (const chunk of iterator) { const delta = typeof chunk === 'string' ? chunk : chunk?.delta; if (chunk && typeof chunk === 'object' && chunk.usage && chunk.usage.trusted === true) providerUsage = chunk.usage; if (typeof delta !== 'string') continue; const current = await this.repository.getTask(taskId); assertLease(); if (current.status === 'cancel_requested' || current.status === 'cancelled') { if (this.repository.completeAttempt) await completeTerminal({ attemptId: attempt.attemptId, workerId: options.workerId, state: 'cancelled', errorKey: 'cancelled', ownerId, release: true }); else { await recordTerminal({ requestId: task.requestId, actorId: ownerId, action: 'ai.task.fail', targetType: 'ai_task', targetId: taskId, result: 'failed', summary: { taskId, errorClass: 'cancelled' } }); await this.repository.updateAttempt(attempt.attemptId, { state: 'cancelled', completedAt: new Date() }); await finalizeQuota({ terminalState: 'cancelled', release: true }); await this.repository.transition(taskId, 'cancelled'); await this.repository.event(taskId, 'task.cancelled', {}); } return; } output += delta; await this.repository.transition(taskId, 'running', { text: output }); for (let offset = 0; offset < delta.length; offset += 8192) await this.repository.event(taskId, 'text.delta', { delta: delta.slice(offset, offset + 8192) }); }
      assertLease(); if (['cancel_requested', 'cancelled'].includes((await this.repository.getTask(taskId)).status)) throw Object.assign(new Error('cancelled'), { errorKey: 'cancelled' }); if (this.repository.completeAttempt) { const completed = await completeTerminal({ attemptId: attempt.attemptId, workerId: options.workerId, state: 'succeeded', text: output, ownerId, usageStatus: providerUsage ? 'final' : 'unavailable', usage: providerUsage }); if (!completed) return; } else { await recordTerminal({ requestId: task.requestId, actorId: ownerId, action: 'ai.task.complete', targetType: 'ai_task', targetId: taskId, summary: { taskId, attemptId: attempt.attemptId } }); const artifact = await this.repository.createArtifact({ taskId, ownerId, mimeType: 'text/plain', content: output }); const finished = options.workerId ? await this.repository.finishAttempt(attempt.attemptId, 'succeeded', {}, options.workerId) : await this.repository.updateAttempt(attempt.attemptId, { state: 'succeeded', completedAt: new Date() }); if (options.workerId && !finished) throw Object.assign(new Error('lease_lost'), { errorKey: 'lease_lost' }); await finalizeQuota({ terminalState: 'completed', usageStatus: providerUsage ? 'final' : 'unavailable', usage: providerUsage }); await this.repository.transition(taskId, 'succeeded', { text: output, artifactIds: [artifact.artifactId] }); await this.repository.event(taskId, 'task.completed', { snapshot: safe({ ...(await this.repository.getTask(taskId)), artifactIds: [artifact.artifactId] }) }); }
    } catch (error) { if (terminalCommitFailed) throw error; const key = error.errorKey ?? 'upstream_unavailable'; const terminalState = key === 'timed_out' ? 'timed_out' : key === 'cancelled' ? 'cancelled' : 'failed'; if (key === 'lease_lost') return; if (attempt && this.repository.completeAttempt) { const completed = await completeTerminal({ attemptId: attempt.attemptId, workerId: options.workerId, state: terminalState, errorKey: key, ownerId, usageStatus: 'unavailable', usage: { estimated: terminalState === 'timed_out' && providerStarted }, release: terminalState === 'cancelled' || !providerStarted }); if (!completed) return; } else { await recordTerminal({ requestId: task.requestId, actorId: ownerId, action: 'ai.task.fail', targetType: 'ai_task', targetId: taskId, result: 'failed', summary: { taskId, errorClass: key, quotaFinalized: Boolean(reservationId) } }); if (attempt) { const finished = options.workerId ? await this.repository.finishAttempt(attempt.attemptId, terminalState, { errorClass: key }, options.workerId) : await this.repository.updateAttempt(attempt.attemptId, { state: terminalState, errorClass: key, completedAt: new Date() }); if (options.workerId && !finished) return; } if (attempt) await finalizeQuota({ terminalState, usageStatus: 'unavailable', estimated: terminalState === 'timed_out' && providerStarted, release: terminalState === 'cancelled' || !providerStarted }); if (terminalState === 'cancelled') { await this.repository.transition(taskId, 'cancelled'); await this.repository.event(taskId, 'task.cancelled', {}); } else { await this.repository.transition(taskId, terminalState, { error: { errorKey: key } }); await this.repository.event(taskId, 'task.failed', { snapshot: safe({ ...(await this.repository.getTask(taskId)), error: { errorKey: key } }) }); } }
    } finally { this.controllers.delete(taskId); }
  }
  async get(taskId, ownerId) { const task = await this.repository.getTask(taskId); if (!task || task.ownerId !== ownerId) throw Object.assign(new Error('task_not_found'), { statusCode: 404 }); return safe(task); }
  async events(taskId, ownerId, after) { await this.get(taskId, ownerId); return this.repository.listEvents(taskId, after); }
  async cancel(taskId, ownerId, requestId) { const task = await this.repository.getTask(taskId); if (!task || task.ownerId !== ownerId) throw Object.assign(new Error('task_not_found'), { statusCode: 404 }); if (['succeeded', 'failed', 'cancelled', 'timed_out'].includes(task.status)) return safe(task); if (task.status === 'accepted' || task.status === 'queued') { const attempt = await this.repository.findAttemptByTask?.(taskId); if (attempt?.state === 'queued' && this.repository.completeAttempt) { const completed = await this.repository.completeAttempt({ attemptId: attempt.attemptId, state: 'cancelled', errorKey: 'cancelled', ownerId, release: true, onlyQueued: true, audit: this.audit }); if (completed) return safe(await this.repository.getTask(taskId)); } if (attempt?.state === 'queued' && !this.repository.completeAttempt) { if (!this.audit?.record) throw new Error('audit_unavailable'); await this.audit.record({ requestId, actorId: ownerId, action: 'ai.task.fail', targetType: 'ai_task', targetId: taskId, result: 'failed', summary: { taskId, errorClass: 'cancelled' } }); await this.repository.updateAttempt(attempt.attemptId, { state: 'cancelled', completedAt: new Date() }); await this.repository.transition(taskId, 'cancelled'); await this.repository.event(taskId, 'task.cancelled', {}); return safe(await this.repository.getTask(taskId)); } } await this.repository.transition(taskId, 'cancel_requested'); this.controllers.get(taskId)?.abort(); await this.repository.event(taskId, 'task.progress', { status: 'cancel_requested' }); return safe(await this.repository.getTask(taskId)); }
  async artifact(id, ownerId) { const artifact = await this.repository.getArtifact(id); if (!artifact || artifact.ownerId !== ownerId) throw Object.assign(new Error('artifact_not_found'), { statusCode: 404 }); return { artifactId: artifact.artifactId, mimeType: artifact.mimeType, content: artifact.content }; }
}
