import test from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import pg from '../../apps/api/node_modules/pg/lib/index.js';
import { InMemorySecretService } from '../../src/security/secret-service.mjs';
import { createExtensionCredentialFingerprint } from '../../src/extensions/credential-fingerprint.mjs';
import { PostgresExtensionManagementRepository } from '../../src/extensions/management-repository.mjs';
import { ExtensionManagementService } from '../../src/extensions/management-service.mjs';
import { PostgresExtensionRepository } from '../../src/extensions/repository.mjs';
import { ExtensionService } from '../../src/extensions/service.mjs';
import { ExtensionSourceResolver } from '../../src/extensions/source-resolver.mjs';
import { PostgresAuditRepository } from '../../src/audit/outbox.mjs';
import { IsolatedExtensionRunner } from '../../apps/extension-runner/src/runner.mjs';
import { fileURLToPath } from 'node:url';

const url=process.env.DGOS_EXTENSION_TEST_DATABASE_URL;
test('credential fingerprint is shared, replay survives revocation, and recovery cannot revoke slow writes',{skip:!url},async()=>{
  if(!/^\/(?:dgos_v1_extensions(?:_[a-z0-9]+)?|dgos_v1_verify_[0-9a-f]{32})$/.test(new URL(url).pathname))throw new Error('test database name mismatch');
  const pool=new pg.Pool({connectionString:url,max:6});
  const secretService=new InMemorySecretService();
  const audit=new PostgresAuditRepository(pool);
  const managementRepository=new PostgresExtensionManagementRepository(pool,audit);
  const fingerprintA=await createExtensionCredentialFingerprint({pool,secretService});
  const fingerprintB=await createExtensionCredentialFingerprint({pool,secretService});
  assert.deepEqual(fingerprintA({a:'one',b:'two'}),fingerprintB({b:'two',a:'one'}));
  const subjectId=randomUUID();
  const sourceResolver=new ExtensionSourceResolver();
  const manifest={kind:'mcp',id:`credential_${randomUUID().replaceAll('-','')}`,version:'1.0.0',requiresCredential:true,operations:['echo','credential'].map((operationId)=>({operationId,permission:'mcp.tool.invoke',risk:'low',sideEffects:false,inputSchema:{type:'object',properties:{}}}))};
  sourceResolver.register('system:credential_test',{trustState:'trusted',manifest});
  const config={transport:'stdio',runnerProfileId:'test'};
  const runner=new IsolatedExtensionRunner({runnerProfiles:{test:{command:process.execPath,allowedCommand:process.execPath,args:[fileURLToPath(new URL('./stdio-mcp-fixture.mjs',import.meta.url))],cwd:fileURLToPath(new URL('.',import.meta.url)),credentialEnv:{apiKey:'DGOS_MCP_TEST_CREDENTIAL'},timeoutMs:2000}}});
  const extensions=new ExtensionService({repository:new PostgresExtensionRepository(pool),managementRepository,audit,sourceResolver,secretService,runner,permissions:{check:async()=>({decision:'allow'})},appAccess:async()=>true,verifyConfirmation:async()=>true});
  const template={templateId:'test',version:'1.0.0',source:'system:credential_test',name:'Test',config,credentialFields:[{name:'apiKey',label:'API key',required:true}]};
  const management=new ExtensionManagementService({extensions,repository:managementRepository,templates:[template],secretService,credentialFingerprint:fingerprintA});extensions.management=management;
  const preview=await extensions.preview({kind:'mcp',source:template.source,subjectId,requestId:randomUUID()});
  await assert.rejects(extensions.install({kind:'mcp',source:template.source,previewId:preview.previewId,previewDigest:preview.digest,subjectId,confirmed:true,requestId:randomUUID(),config}),/credential_unavailable/);
  const installed=await extensions.install({kind:'mcp',source:template.source,previewId:preview.previewId,previewDigest:preview.digest,subjectId,confirmed:true,requestId:randomUUID(),config,templateId:'test',templateVersion:'1.0.0',credentials:{apiKey:'fixture-secret'},secureTransport:true});
  try {
    const requestId=randomUUID();
    const input={subjectId,requestId,id:manifest.id,baseVersion:installed.stateVersion,config,credentials:{apiKey:'fixture-secret'},confirmed:true,secureTransport:true};
    const first=await management.updateMcpConfig(input);
    assert.equal(first.credentialStatus,'configured');
    const enabled=await extensions.setState({kind:'mcp',id:manifest.id,subjectId,desiredState:'enabled',baseVersion:first.stateVersion,requestId:randomUUID()});
    const stopped=await extensions.setState({kind:'mcp',id:manifest.id,subjectId,desiredState:'disabled',baseVersion:enabled.stateVersion,requestId:randomUUID()});
    const reenabled=await extensions.setState({kind:'mcp',id:manifest.id,subjectId,desiredState:'enabled',baseVersion:stopped.stateVersion,requestId:randomUUID()});
    await extensions.connect({id:manifest.id,subjectId,baseVersion:reenabled.stateVersion,requestId:randomUUID(),confirmed:true});
    const worker=new ExtensionService({repository:extensions.repository,audit,sourceResolver,secretService,runner,permissions:{check:async()=>({decision:'allow'})},appAccess:async()=>true,verifyConfirmation:async()=>true,managementRepository});
    await worker.processConnectionIntents();
    const connected=await extensions.getRecord(subjectId,'mcp',manifest.id);
    assert.equal(connected.connectionState,'connected');
    const run=await extensions.submit({kind:'mcp',id:manifest.id,operationId:'credential',extensionVersion:'1.0.0',input:{},subjectId,appId:'fixture',requestId:randomUUID(),confirmationId:'fixture'});
    await worker.process(run.runId);
    assert.deepEqual((await extensions.getRun({runId:run.runId,subjectId})).resultSummary,{accepted:true});
    const disconnected=await extensions.disconnect({id:manifest.id,subjectId,baseVersion:(await extensions.getRecord(subjectId,'mcp',manifest.id)).stateVersion,requestId:randomUUID()});
    assert.equal(disconnected.connectionState,'stopping');await worker.processConnectionIntents();
    const oldRef=(await extensions.getRecord(subjectId,'mcp',manifest.id)).credentialRef;
    assert.deepEqual(await management.updateMcpConfig(input),first);
    await assert.rejects(management.updateMcpConfig({...input,credentials:{apiKey:'changed'}}),/request_conflict/);
    const beforeSecond=(await extensions.getRecord(subjectId,'mcp',manifest.id)).stateVersion;
    const second=await management.updateMcpConfig({...input,requestId:randomUUID(),baseVersion:beforeSecond,credentials:{apiKey:'second'}});
    await extensions.processSecretRevokes();
    assert.equal((await secretService.inspect(oldRef)).credentialState,'unavailable');
    assert.deepEqual(await management.updateMcpConfig(input),first);
    assert.equal(second.stateVersion,beforeSecond+1);

    let releasePut;let enteredPut;
    const entered=new Promise((resolve)=>{enteredPut=resolve;});
    const gate=new Promise((resolve)=>{releasePut=resolve;});
    const slowSecret={...secretService,put:async(args)=>{enteredPut();await gate;return secretService.put(args);},revoke:(ref)=>secretService.revoke(ref)};
    const slowRepository=new PostgresExtensionManagementRepository(pool,audit);
    const slow=slowRepository.updateMcpConfig({subjectId,requestId:randomUUID(),id:manifest.id,baseVersion:second.stateVersion,config,credentials:{apiKey:'third'},credentialFingerprint:fingerprintB({apiKey:'third'}),record:await extensions.getRecord(subjectId,'mcp',manifest.id),secretService:slowSecret,fingerprint:'slow-write-test',audit});
    await entered;
    assert.equal(await managementRepository.recoverSecretWrites(secretService),0);
    releasePut();
    await slow;
    const latest=await extensions.getRecord(subjectId,'mcp',manifest.id);
    assert.equal((await secretService.inspect(latest.credentialRef)).credentialState,'available');
    assert.equal((await pool.query("SELECT state FROM extension_secret_write_intents WHERE secret_ref=$1",[latest.credentialRef])).rows[0].state,'committed');
    const orphanId=randomUUID(); const orphanRef=`mcp-credential:${subjectId}:${manifest.id}:${orphanId}`;
    await managementRepository.prepareSecret({intentId:orphanId,subjectId,extensionId:manifest.id,secretRef:orphanRef,oldSecretRef:latest.credentialRef,requestId:randomUUID(),credentialFingerprint:fingerprintA({apiKey:'orphan'})});
    await secretService.put({secretRef:orphanRef,value:JSON.stringify({apiKey:'orphan'}),purpose:'mcp-credential',subjectId,ttlMs:60000});
    assert.equal(await managementRepository.recoverSecretWrites(secretService,{intentId:orphanId}),1);
    assert.equal((await secretService.inspect(orphanRef)).credentialState,'unavailable');
    assert.equal((await pool.query('SELECT state FROM extension_secret_write_intents WHERE intent_id=$1',[orphanId])).rows[0].state,'revoked');
  } finally {await runner.close();await pool.end();}
});
