// Public classifications only. Never return a thrown transport/SQL message verbatim.
export const publicErrorMessages = Object.freeze({
  policy_blocked: 'Network policy blocks this endpoint',
  connection_test_required: 'A successful connection test for this account version is required',
  provider_config_in_use: 'Provider configuration has active tasks',
  invalid_package_files: 'Package resources are invalid',
  invalid_package_path: 'Package path is invalid',
  invalid_package_file: 'Package resource encoding is invalid',
  invalid_package_json: 'Package declaration is invalid',
  package_too_large: 'Package exceeds configured limits',
  missing_package_resource: 'A required package resource is missing',
  integrity_error: 'Package integrity verification failed',
  untrusted_package: 'Package signer is not trusted for this operation',
  invalid_app_id: 'Application identifier is invalid',
  request_id_required: 'A request identifier is required',
  invalid_review_decision: 'Review decision is invalid',
  review_forbidden: 'Review is not permitted for this package',
  test_install_forbidden: 'Test installation is not permitted',
  data_migration_required: 'Application data requires migration',
  rollback_required: 'Installation failed and requires rollback',
  app_entry_unavailable: 'Application entry is unavailable',
  app_data_migration_schema_required: 'Application migration storage is unavailable',
  source_unavailable: 'Extension source is unavailable',
  source_digest_mismatch: 'Extension source integrity verification failed',
  source_untrusted: 'Extension source is not trusted',
  preview_expired: 'Refresh the extension preview',
  extension_not_found: 'Extension was not found',
  extension_disabled: 'Extension is disabled',
  extension_in_use: 'Extension has active references or runs',
  connection_not_ready: 'Extension connection is not ready',
  operation_not_found: 'Extension operation was not found',
  confirmation_not_found: 'Confirmation was not found',
  confirmation_expired: 'Confirmation expired or was consumed',
  run_not_found: 'Extension run was not found',
  runner_profile_unavailable: 'Extension runtime profile is unavailable',
  handler_unavailable: 'Extension handler is unavailable',
  extension_config_unavailable: 'Extension runtime configuration is unavailable',
  extension_config_invalid: 'Extension runtime configuration is invalid',
  sandbox_required: 'Extension runtime isolation is unavailable',
  action_owner_conflict: 'Action belongs to another application',
  invalid_action_manifest: 'Application action declaration is invalid',
  action_handler_unavailable: 'Application action handler is unavailable',
  capability_unavailable: 'Application capability is unavailable',
  launch_ticket_invalid: 'Application launch expired; launch the app again',
  app_instance_invalid: 'Application instance is no longer valid',
  model_profile_unavailable: 'Model profile is unavailable',
  model_profile_missing: 'No applicable model profile is registered',
  permission_unavailable: 'Permission service is unavailable',
  audit_unavailable: 'Audit service is unavailable',
  data_migration_invalid: 'Application data migration declaration is invalid',
  data_migration_conflict: 'Application data migration conflicts with retained data',
  proxy_configuration_invalid: 'Proxy configuration is invalid',
  route_unavailable: 'The configured network route is unavailable',
  secret_unavailable: 'Secret storage is unavailable',
  task_unavailable: 'Task service is unavailable',
  source_changed: 'Extension source changed; refresh its preview',
  translation_not_found: 'Translation task was not found',
  translation_not_ready: 'Translation task has not completed successfully',
  translation_invalid: 'Translation result does not match the selected fields',
});
