import { randomUUID } from 'node:crypto';
import { invalid } from './validation.mjs';

function sameConfirmation(a,b) { return ['subjectId','appId','kind','extensionId','operationId','extensionVersion','inputDigest','requestId'].every((key)=>a[key]===b[key]); }

export class InMemoryExtensionRepository {
  constructor() { this.previews = new Map(); this.installs = new Map(); this.mutations = new Map(); this.runs = new Map(); this.events = new Map(); this.connectionIntents=new Map(); this.secretRevokes=new Map(); this.confirmations=new Map(); }
  key(subjectId, kind, id) { return `${subjectId}:${kind}:${id}`; }
  async savePreview(x) { const old = [...this.previews.values()].find((p) => p.subjectId === x.subjectId && p.requestId === x.requestId); if (old) return old; this.previews.set(x.previewId, structuredClone(x)); return x; }
  async getPreview(id, subjectId) { const x = this.previews.get(id); return x?.subjectId === subjectId ? structuredClone(x) : undefined; }
  async getInstall(subjectId, kind, id) { const x = this.installs.get(this.key(subjectId, kind, id)); return x && structuredClone(x); }
  async list(subjectId, kind) { return [...this.installs.values()].filter((x) => x.subjectId === subjectId && x.kind === kind && x.state !== 'removed').map((x)=>structuredClone(x)); }
  async putInstall(x) { const key = this.key(x.subjectId, x.kind, x.id); const old = this.installs.get(key); if (old && old.state !== 'removed') throw invalid('extension_conflict', 409); this.installs.set(key, structuredClone(x)); return x; }
  async updateInstall(subjectId, kind, id, expectedVersion, patch) { const key = this.key(subjectId, kind, id); const old = this.installs.get(key); if (!old || old.state === 'removed') return undefined; if (expectedVersion != null && old.stateVersion !== expectedVersion) throw invalid('version_conflict', 409); const next = { ...old, ...structuredClone(patch), stateVersion: old.stateVersion + 1 }; this.installs.set(key, next); return structuredClone(next); }
  async mutation(subjectId, requestId, operation, fingerprint, work) { const key = `${subjectId}:${requestId}`; const old = this.mutations.get(key); if (old) { if (old.operation !== operation || old.fingerprint !== fingerprint) throw invalid('request_conflict', 409); return structuredClone(old.result); } const result = await work(); this.mutations.set(key, { operation, fingerprint, result: structuredClone(result) }); return result; }
  async createRun(x,onCreated) { const old = [...this.runs.values()].find((r) => r.subjectId === x.subjectId && r.requestId === x.requestId); if (old) { if (old.inputDigest !== x.inputDigest || old.operationId !== x.operationId || old.extensionId !== x.extensionId) throw invalid('request_conflict', 409); return { run: structuredClone(old), created: false }; } const run = { ...x, runId: x.runId ?? randomUUID(), state: 'queued', sequence: 1, handlerClaimed: false, handlerCalls: 0 }; await onCreated?.(run); this.runs.set(run.runId, structuredClone(run)); this.events.set(run.runId, [{ runId: run.runId, sequence: 1, state: 'queued' }]); return { run, created: true }; }
  async getRun(id, subjectId) { const r = this.runs.get(id); return r?.subjectId === subjectId ? structuredClone(r) : undefined; }
  async getRunByRequest(subjectId,requestId) { const r=[...this.runs.values()].find((item)=>item.subjectId===subjectId&&item.requestId===requestId); return r&&structuredClone(r); }
  async listRunnable() { return [...this.runs.values()].filter((r) => ['queued','running','cancel_requested'].includes(r.state)).map((r)=>structuredClone(r)); }
  async transition(id, from, state, patch = {}) { const r = this.runs.get(id); if (!r || !from.includes(r.state)) return undefined; Object.assign(r, structuredClone(patch), { state, sequence: r.sequence + 1 }); this.events.get(id).push({ runId: id, sequence: r.sequence, state, reasonCode: r.reasonCode }); return structuredClone(r); }
  async claim(id, workerId, leaseMs) { const r = this.runs.get(id); if (!r || r.state !== 'queued' || r.handlerClaimed || (r.leaseUntil && Date.parse(r.leaseUntil) > Date.now())) return undefined; return this.transition(id, ['queued'], 'running', { leaseOwner: workerId, leaseUntil: new Date(Date.now() + leaseMs).toISOString(), handlerClaimed: true, handlerCalls: 1 }); }
  async eventsAfter(id, subjectId, after = 0) { if (!await this.getRun(id, subjectId)) return undefined; return this.events.get(id).filter((e) => e.sequence > Number(after)); }
  async transitionWithAudit(id,from,state,patch,auditEvent,audit) { const r=this.runs.get(id); if(!r||!from.includes(r.state))return undefined; await audit.record(auditEvent); return this.transition(id,from,state,patch); }
  async updateConnectionWithAudit(subjectId,kind,id,version,patch,intent,auditEvent,audit) { const old=await this.getInstall(subjectId,kind,id); if(!old||old.stateVersion!==version)throw invalid('version_conflict',409); await audit.record(auditEvent); const next=await this.updateInstall(subjectId,kind,id,version,patch); if(intent)this.connectionIntents.set(intent.intentId,{...intent,state:'queued'}); return next; }
  async listConnectionIntents() { return [...this.connectionIntents.values()].filter((x)=>x.state==='queued').map((x)=>structuredClone(x)); }
  async claimConnectionIntent(id) { const x=this.connectionIntents.get(id); if(!x||x.state!=='queued')return false; x.state='claimed'; return true; }
  async finishConnectionIntent(intentId,state) { const x=this.connectionIntents.get(intentId); if(x)x.state=state; }
  async finishConnectionWithAudit(subjectId,kind,id,version,patch,intentId,event,audit) { const next=await this.updateConnectionWithAudit(subjectId,kind,id,version,patch,null,event,audit); await this.finishConnectionIntent(intentId,'completed'); return next; }
  async queueSecretRevoke(x) { this.secretRevokes.set(x.intentId,{...x,state:'pending'}); }
  async listSecretRevokes() { return [...this.secretRevokes.values()].filter((x)=>x.state==='pending'); }
  async finishSecretRevoke(id) { const x=this.secretRevokes.get(id); if(x)x.state='completed'; }
  async createConfirmation(x) { const old=[...this.confirmations.values()].find((v)=>v.subjectId===x.subjectId&&v.requestId===x.requestId); if(old) { if(!sameConfirmation(old,x))throw invalid('request_conflict',409); if(Date.parse(old.expiresAt)<=Date.now())throw invalid('confirmation_expired',409); return structuredClone(old); } this.confirmations.set(x.confirmationId,structuredClone(x)); return x; }
  async approveConfirmation(id,subjectId) { const x=this.confirmations.get(id); if(!x||x.subjectId!==subjectId||x.state!=='pending'||Date.parse(x.expiresAt)<=Date.now())return undefined; x.state='approved'; return structuredClone(x); }
  async getConfirmation(id,subjectId) { const x=this.confirmations.get(id); return x?.subjectId===subjectId?structuredClone(x):undefined; }
  async createRunWithConfirmation(x,confirmationId,onCreated) { const ticket=await this.getConfirmation(confirmationId,x.subjectId); if(!ticket||ticket.requestId!==x.requestId||ticket.appId!==x.appId||ticket.kind!==x.kind||ticket.extensionId!==x.extensionId||ticket.operationId!==x.operationId||ticket.extensionVersion!==x.extensionVersion||ticket.inputDigest!==x.inputDigest)throw invalid('confirmation_required',409); if(ticket.state==='consumed') { const old=[...this.runs.values()].find((r)=>r.subjectId===x.subjectId&&r.requestId===x.requestId); if(!old||old.appId!==x.appId||old.kind!==x.kind||old.extensionId!==x.extensionId||old.operationId!==x.operationId||old.extensionVersion!==x.extensionVersion||old.manifestDigest!==x.manifestDigest||old.inputDigest!==x.inputDigest)throw invalid('request_conflict',409); return {run:structuredClone(old),created:false}; } if(ticket.state!=='approved'||Date.parse(ticket.expiresAt)<=Date.now())throw invalid('confirmation_required',409); const result=await this.createRun(x,onCreated); if(result.created)this.confirmations.get(confirmationId).state='consumed'; return result; }
}

export class PostgresExtensionRepository {
  constructor(pool) { this.pool = pool; }
  async tx(work) { const c = await this.pool.connect(); try { await c.query('BEGIN'); const value = await work(c); await c.query('COMMIT'); return value; } catch (e) { await c.query('ROLLBACK'); throw e; } finally { c.release(); } }
  previewRow(r) { return r && { previewId:r.preview_id, subjectId:r.subject_id, requestId:r.request_id, kind:r.kind, sourceRef:r.source_ref, digest:r.digest, manifest:r.manifest, trustState:r.trust_state, expiresAt:r.expires_at.toISOString() }; }
  installRow(r) { return r && { subjectId:r.subject_id, kind:r.kind, id:r.extension_id, packageId:r.package_id, version:r.version, sourceRef:r.source_ref, manifestDigest:r.manifest_digest, manifest:r.manifest, state:r.state, connectionState:r.connection_state, config:r.config, credentialRef:r.credential_ref, toolCatalog:r.tool_catalog, stateVersion:Number(r.state_version), connectionAttemptId:r.connection_attempt_id }; }
  runRow(r) { return r && { runId:r.run_id, requestId:r.request_id, subjectId:r.subject_id, appId:r.app_id, kind:r.kind, extensionId:r.extension_id, operationId:r.operation_id, extensionVersion:r.extension_version, manifestDigest:r.manifest_digest, inputDigest:r.input_digest, input:r.input_payload, state:r.state, sequence:Number(r.sequence), handlerClaimed:r.handler_claimed, handlerCalls:r.handler_calls, leaseOwner:r.lease_owner, leaseUntil:r.lease_until?.toISOString(), timeoutAt:r.timeout_at.toISOString(), resultSummary:r.result_summary, reasonCode:r.reason_code, taskId:r.task_id }; }
  async savePreview(x) { const { rows } = await this.pool.query('INSERT INTO extension_previews(preview_id,subject_id,request_id,kind,source_ref,digest,manifest,trust_state,expires_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) ON CONFLICT(subject_id,request_id) DO UPDATE SET request_id=EXCLUDED.request_id RETURNING *',[x.previewId,x.subjectId,x.requestId,x.kind,x.sourceRef,x.digest,JSON.stringify(x.manifest),x.trustState,x.expiresAt]); return this.previewRow(rows[0]); }
  async getPreview(id, subjectId) { const { rows } = await this.pool.query('SELECT * FROM extension_previews WHERE preview_id=$1 AND subject_id=$2',[id,subjectId]); return this.previewRow(rows[0]); }
  async getInstall(subjectId,kind,id) { const { rows } = await this.pool.query('SELECT * FROM extension_installs WHERE subject_id=$1 AND kind=$2 AND extension_id=$3',[subjectId,kind,id]); return this.installRow(rows[0]); }
  async list(subjectId,kind) { const { rows } = await this.pool.query("SELECT * FROM extension_installs WHERE subject_id=$1 AND kind=$2 AND state<>'removed' ORDER BY extension_id",[subjectId,kind]); return rows.map((r)=>this.installRow(r)); }
  async putInstall(x, client=this.pool) { const { rows } = await client.query("INSERT INTO extension_installs(subject_id,kind,extension_id,package_id,version,source_ref,manifest_digest,manifest,state,connection_state,config,credential_ref,tool_catalog) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13) ON CONFLICT(subject_id,kind,extension_id) DO NOTHING RETURNING *",[x.subjectId,x.kind,x.id,x.packageId??null,x.version,x.sourceRef,x.manifestDigest,JSON.stringify(x.manifest),x.state,x.connectionState,JSON.stringify(x.config),x.credentialRef??null,JSON.stringify(x.toolCatalog??[])]); if (!rows[0]) throw invalid('extension_conflict',409); return this.installRow(rows[0]); }
  async updateInstall(subjectId,kind,id,expectedVersion,patch,client=this.pool) { const cols={ state:'state',connectionState:'connection_state',credentialRef:'credential_ref',toolCatalog:'tool_catalog',connectionAttemptId:'connection_attempt_id' }; const values=[subjectId,kind,id,expectedVersion]; const sets=[]; for(const [key,col] of Object.entries(cols)) if(Object.hasOwn(patch,key)) { values.push(key==='toolCatalog'?JSON.stringify(patch[key]):patch[key]); sets.push(`${col}=$${values.length}`); } if(!sets.length) throw invalid(); const { rows }=await client.query(`UPDATE extension_installs SET ${sets.join(',')},state_version=state_version+1,updated_at=now() WHERE subject_id=$1 AND kind=$2 AND extension_id=$3 AND ($4::bigint IS NULL OR state_version=$4) AND state<>'removed' RETURNING *`,values); return this.installRow(rows[0]); }
  async mutation(subjectId,requestId,operation,fingerprint,work) { return this.tx(async(c)=>{ await c.query('SELECT pg_advisory_xact_lock(hashtext($1))',[`${subjectId}:${requestId}`]); const old=await c.query('SELECT * FROM extension_mutations WHERE subject_id=$1 AND request_id=$2 FOR UPDATE',[subjectId,requestId]); if(old.rows[0]) { if(old.rows[0].operation!==operation||old.rows[0].fingerprint!==fingerprint) throw invalid('request_conflict',409); return old.rows[0].result; } const result=await work(c); await c.query('INSERT INTO extension_mutations(subject_id,request_id,operation,fingerprint,result) VALUES($1,$2,$3,$4,$5)',[subjectId,requestId,operation,fingerprint,JSON.stringify(result)]); return result; }); }
  async createRun(x,onCreated) { return this.tx(async(c)=>{ const {rows}=await c.query("INSERT INTO extension_runs(run_id,request_id,subject_id,app_id,kind,extension_id,operation_id,extension_version,manifest_digest,input_digest,input_payload,state,timeout_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,'queued',$12) ON CONFLICT(subject_id,request_id) DO NOTHING RETURNING *",[x.runId,x.requestId,x.subjectId,x.appId,x.kind,x.extensionId,x.operationId,x.extensionVersion,x.manifestDigest,x.inputDigest,JSON.stringify(x.input),x.timeoutAt]); let row=rows[0]; if(!row) { const found=await c.query('SELECT * FROM extension_runs WHERE subject_id=$1 AND request_id=$2',[x.subjectId,x.requestId]); row=found.rows[0]; if(row.input_digest!==x.inputDigest||row.operation_id!==x.operationId||row.extension_id!==x.extensionId) throw invalid('request_conflict',409); } else { await c.query("INSERT INTO extension_run_events(run_id,sequence,state) VALUES($1,1,'queued')",[x.runId]); await onCreated?.(this.runRow(row),c); } return {run:this.runRow(row),created:Boolean(rows[0])}; }); }
  async getRun(id,subjectId) { const {rows}=await this.pool.query('SELECT * FROM extension_runs WHERE run_id=$1 AND subject_id=$2',[id,subjectId]); return this.runRow(rows[0]); }
  async getRunByRequest(subjectId,requestId) { const {rows}=await this.pool.query('SELECT * FROM extension_runs WHERE subject_id=$1 AND request_id=$2',[subjectId,requestId]); return this.runRow(rows[0]); }
  async listRunnable() { const {rows}=await this.pool.query("SELECT * FROM extension_runs WHERE state IN ('queued','running','cancel_requested') ORDER BY created_at LIMIT 100"); return rows.map((r)=>this.runRow(r)); }
  async transition(id,from,state,patch={}) { return this.tx(async(c)=>{ const {rows}=await c.query("UPDATE extension_runs SET state=$3,sequence=sequence+1,result_summary=COALESCE($4,result_summary),reason_code=COALESCE($5,reason_code),updated_at=now() WHERE run_id=$1 AND state=ANY($2::text[]) RETURNING *",[id,from,state,patch.resultSummary?JSON.stringify(patch.resultSummary):null,patch.reasonCode??null]); if(!rows[0]) return undefined; await c.query('INSERT INTO extension_run_events(run_id,sequence,state,reason_code) VALUES($1,$2,$3,$4)',[id,rows[0].sequence,state,rows[0].reason_code]); return this.runRow(rows[0]); }); }
  async claim(id,workerId,leaseMs) { return this.tx(async(c)=>{ const {rows}=await c.query("UPDATE extension_runs SET state='running',sequence=sequence+1,handler_claimed=true,handler_calls=1,lease_owner=$2,lease_until=now()+($3::int * interval '1 millisecond'),updated_at=now() WHERE run_id=$1 AND state='queued' AND handler_claimed=false AND (lease_until IS NULL OR lease_until<now()) RETURNING *",[id,workerId,leaseMs]); if(!rows[0]) return undefined; await c.query("INSERT INTO extension_run_events(run_id,sequence,state) VALUES($1,$2,'running')",[id,rows[0].sequence]); return this.runRow(rows[0]); }); }
  async eventsAfter(id,subjectId,after=0) { if(!await this.getRun(id,subjectId)) return undefined; const {rows}=await this.pool.query('SELECT run_id,sequence,state,reason_code,created_at FROM extension_run_events WHERE run_id=$1 AND sequence>$2 ORDER BY sequence',[id,after]); return rows.map((r)=>({runId:r.run_id,sequence:Number(r.sequence),state:r.state,reasonCode:r.reason_code,createdAt:r.created_at.toISOString()})); }
  async transitionWithAudit(id,from,state,patch,event,audit) { return this.tx(async(c)=>{ const {rows}=await c.query("UPDATE extension_runs SET state=$3,sequence=sequence+1,result_summary=COALESCE($4,result_summary),reason_code=COALESCE($5,reason_code),updated_at=now() WHERE run_id=$1 AND state=ANY($2::text[]) RETURNING *",[id,from,state,patch.resultSummary?JSON.stringify(patch.resultSummary):null,patch.reasonCode??null]); if(!rows[0])return undefined; await c.query('INSERT INTO extension_run_events(run_id,sequence,state,reason_code) VALUES($1,$2,$3,$4)',[id,rows[0].sequence,state,rows[0].reason_code]); await audit.record(event,c); return this.runRow(rows[0]); }); }
  async updateConnectionWithAudit(subjectId,kind,id,version,patch,intent,event,audit) { return this.tx(async(c)=>{ const next=await this.updateInstall(subjectId,kind,id,version,patch,c); if(!next)throw invalid('version_conflict',409); if(intent)await c.query("INSERT INTO extension_connection_intents(intent_id,subject_id,kind,extension_id,extension_version,config_digest,action,state,request_id) VALUES($1,$2,$3,$4,$5,$6,$7,'queued',$8)",[intent.intentId,intent.subjectId,intent.kind,intent.extensionId,intent.extensionVersion,intent.configDigest,intent.action,intent.requestId]); await audit.record(event,c); return next; }); }
  async listConnectionIntents() { const {rows}=await this.pool.query("SELECT * FROM extension_connection_intents WHERE state='queued' OR (state='claimed' AND lease_until<now()) ORDER BY created_at LIMIT 100"); return rows.map((r)=>({intentId:r.intent_id,subjectId:r.subject_id,kind:r.kind,extensionId:r.extension_id,extensionVersion:r.extension_version,configDigest:r.config_digest,action:r.action,requestId:r.request_id})); }
  async claimConnectionIntent(id,workerId) { const {rows}=await this.pool.query("UPDATE extension_connection_intents SET state='claimed',lease_owner=$2,lease_until=now()+interval '30 seconds',attempts=attempts+1 WHERE intent_id=$1 AND (state='queued' OR (state='claimed' AND lease_until<now())) RETURNING *",[id,workerId]); return Boolean(rows[0]); }
  async finishConnectionIntent(id,state) { await this.pool.query("UPDATE extension_connection_intents SET state=$2,completed_at=now(),lease_owner=NULL,lease_until=NULL WHERE intent_id=$1",[id,state]); }
  async finishConnectionWithAudit(subjectId,kind,id,version,patch,intentId,event,audit) { return this.tx(async(c)=>{ const next=await this.updateInstall(subjectId,kind,id,version,patch,c); if(!next)throw invalid('version_conflict',409); await audit.record(event,c); await c.query("UPDATE extension_connection_intents SET state='completed',completed_at=now(),lease_owner=NULL,lease_until=NULL WHERE intent_id=$1 AND state='claimed'",[intentId]); return next; }); }
  async queueSecretRevoke(x,client=this.pool) { await client.query("INSERT INTO extension_secret_revoke_intents(intent_id,subject_id,kind,extension_id,secret_ref,state) VALUES($1,$2,$3,$4,$5,'pending')",[x.intentId,x.subjectId,x.kind,x.extensionId,x.secretRef]); }
  async listSecretRevokes() { const {rows}=await this.pool.query("SELECT * FROM extension_secret_revoke_intents WHERE state='pending' ORDER BY created_at LIMIT 100"); return rows.map((r)=>({intentId:r.intent_id,subjectId:r.subject_id,kind:r.kind,extensionId:r.extension_id,secretRef:r.secret_ref})); }
  async finishSecretRevoke(id) { await this.pool.query("UPDATE extension_secret_revoke_intents SET state='completed',completed_at=now() WHERE intent_id=$1 AND state='pending'",[id]); }
  confirmationRow(r) { return r&&({confirmationId:r.confirmation_id,subjectId:r.subject_id,appId:r.app_id,kind:r.kind,extensionId:r.extension_id,operationId:r.operation_id,extensionVersion:r.extension_version,inputDigest:r.input_digest,requestId:r.request_id,state:r.state,expiresAt:r.expires_at.toISOString()}); }
  async createConfirmation(x) { const {rows}=await this.pool.query('INSERT INTO extension_confirmations(confirmation_id,subject_id,app_id,kind,extension_id,operation_id,extension_version,input_digest,request_id,state,expires_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) ON CONFLICT(subject_id,request_id) DO UPDATE SET request_id=EXCLUDED.request_id RETURNING *',[x.confirmationId,x.subjectId,x.appId,x.kind,x.extensionId,x.operationId,x.extensionVersion,x.inputDigest,x.requestId,x.state,x.expiresAt]); const ticket=this.confirmationRow(rows[0]); if(!sameConfirmation(ticket,x))throw invalid('request_conflict',409); if(Date.parse(ticket.expiresAt)<=Date.now())throw invalid('confirmation_expired',409); return ticket; }
  async approveConfirmation(id,subjectId) { const {rows}=await this.pool.query("UPDATE extension_confirmations SET state='approved' WHERE confirmation_id=$1 AND subject_id=$2 AND state='pending' AND expires_at>now() RETURNING *",[id,subjectId]); return this.confirmationRow(rows[0]); }
  async getConfirmation(id,subjectId) { const {rows}=await this.pool.query('SELECT * FROM extension_confirmations WHERE confirmation_id=$1 AND subject_id=$2',[id,subjectId]); return this.confirmationRow(rows[0]); }
  async createRunWithConfirmation(x,confirmationId,onCreated) { return this.tx(async(c)=>{ const ticketResult=await c.query('SELECT * FROM extension_confirmations WHERE confirmation_id=$1 AND subject_id=$2 FOR UPDATE',[confirmationId,x.subjectId]); const ticket=this.confirmationRow(ticketResult.rows[0]); if(!ticket||ticket.requestId!==x.requestId||ticket.appId!==x.appId||ticket.kind!==x.kind||ticket.extensionId!==x.extensionId||ticket.operationId!==x.operationId||ticket.extensionVersion!==x.extensionVersion||ticket.inputDigest!==x.inputDigest)throw invalid('confirmation_required',409); if(ticket.state==='consumed') { const old=await c.query('SELECT * FROM extension_runs WHERE subject_id=$1 AND request_id=$2',[x.subjectId,x.requestId]); const run=this.runRow(old.rows[0]); if(!run||run.appId!==x.appId||run.kind!==x.kind||run.extensionId!==x.extensionId||run.operationId!==x.operationId||run.extensionVersion!==x.extensionVersion||run.manifestDigest!==x.manifestDigest||run.inputDigest!==x.inputDigest)throw invalid('request_conflict',409); return {run,created:false}; } if(ticket.state!=='approved'||Date.parse(ticket.expiresAt)<=Date.now())throw invalid('confirmation_required',409); const {rows}=await c.query("INSERT INTO extension_runs(run_id,request_id,subject_id,app_id,kind,extension_id,operation_id,extension_version,manifest_digest,input_digest,input_payload,state,timeout_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,'queued',$12) ON CONFLICT(subject_id,request_id) DO NOTHING RETURNING *",[x.runId,x.requestId,x.subjectId,x.appId,x.kind,x.extensionId,x.operationId,x.extensionVersion,x.manifestDigest,x.inputDigest,JSON.stringify(x.input),x.timeoutAt]); if(!rows[0]) {const old=await c.query('SELECT * FROM extension_runs WHERE subject_id=$1 AND request_id=$2',[x.subjectId,x.requestId]); return {run:this.runRow(old.rows[0]),created:false};} await c.query("INSERT INTO extension_run_events(run_id,sequence,state) VALUES($1,1,'queued')",[x.runId]); await onCreated?.(this.runRow(rows[0]),c); if(x.taskIntent)await c.query('INSERT INTO extension_task_intents(run_id,subject_id,skill_id,definition_version,content_digest,task_request_id,task_input,options) VALUES($1,$2,$3,$4,$5,$6,$7,$8)',[x.runId,x.subjectId,x.extensionId,x.taskIntent.definitionVersion,x.taskIntent.contentDigest,x.taskIntent.taskRequestId,x.taskIntent.taskInput,JSON.stringify(x.taskIntent.options)]); await c.query("UPDATE extension_confirmations SET state='consumed' WHERE confirmation_id=$1",[confirmationId]); return {run:this.runRow(rows[0]),created:true}; }); }
}
