import { randomUUID } from 'node:crypto';
import { PostgresAuditRepository, InMemoryAuditRepository } from '../audit/outbox.mjs';

const iso = (value) => value instanceof Date ? value.toISOString() : new Date(value).toISOString();

function accountRow(row) {
  return row && { accountId: row.account_id, ownerId: row.owner_id, ownerType: row.owner_type, protocolType: row.protocol_type, displayName: row.display_name, scope: row.scope, status: row.state, credentialState: row.credential_state ?? 'configured', defaultForProtocol: Boolean(row.scope?.defaultForProtocol), version: String(row.version), createdAt: iso(row.created_at), updatedAt: iso(row.updated_at), _secretRef: row.credential_ref };
}

function testRow(row) {
  return row && { testId: row.test_id, requestId: row.request_id, accountId: row.account_id, providerConfigId: row.provider_config_id, accountVersion: String(row.account_version), configVersion: String(row.config_version), protocolVersion: row.protocol_version, status: row.state, reasonCode: row.reason_code ?? undefined, latencyMs: row.duration_ms ?? undefined, leaseOwner: row.lease_owner, leaseUntil: row.lease_until && iso(row.lease_until), createdAt: iso(row.created_at), completedAt: row.finished_at && iso(row.finished_at) };
}

export class PostgresProviderRepository {
  constructor(pool) { this.pool = pool; this.audit = new PostgresAuditRepository(pool); }
  async withTransaction(work) { const client = await this.pool.connect(); try { await client.query('BEGIN'); const result = await work(client); await client.query('COMMIT'); return result; } catch (error) { await client.query('ROLLBACK'); throw error; } finally { client.release(); } }
  async listAccounts(ownerId) { const { rows } = await this.pool.query('SELECT * FROM provider_accounts WHERE owner_id = $1 AND state <> $2 ORDER BY created_at DESC', [ownerId, 'revoked']); return rows.map(accountRow); }
  async createAccount(input, client = this.pool) { const { rows } = await client.query('INSERT INTO provider_accounts (account_id, owner_type, owner_id, protocol_type, display_name, credential_ref, scope, state) VALUES ($1, $2, $3, $4, $5, $6, $7, $8) RETURNING *', [input.accountId ?? randomUUID(), 'admin', input.ownerId, input.protocolType, input.displayName, input.credentialRef, JSON.stringify({ ...(input.scope ?? {}), defaultForProtocol: Boolean(input.defaultForProtocol) }), input.state ?? 'credential_pending']); return accountRow(rows[0]); }
  async createAccountWithAudit(input, audit) { return this.withTransaction(async (client) => { const account = await this.createAccount(input, client); await this.writeAudit(audit(account), client); return account; }); }
  async getAccount(accountId, client = this.pool) { const { rows } = await client.query('SELECT * FROM provider_accounts WHERE account_id = $1', [accountId]); return accountRow(rows[0]); }
  async hasActiveReferences(accountId) { const { rows } = await this.pool.query("SELECT EXISTS(SELECT 1 FROM provider_configs WHERE provider_account_id=$1 AND status <> 'revoked' UNION ALL SELECT 1 FROM provider_bindings WHERE account_id=$1 AND state='active' UNION ALL SELECT 1 FROM connection_tests WHERE account_id=$1 AND state IN ('queued','running','cancel_requested') UNION ALL SELECT 1 FROM ai_task_attempts WHERE provider_account_id=$1 AND state IN ('queued','running')) AS used", [accountId]); return rows[0].used; }
  async updateAccountState(accountId, expectedVersion, state) { const { rows } = await this.pool.query('UPDATE provider_accounts SET state = $3, version = version + 1, updated_at = now() WHERE account_id = $1 AND version = $2 AND state <> $4 RETURNING *', [accountId, expectedVersion, state, 'revoked']); return accountRow(rows[0]); }
  async revokeAccount(accountId, expectedVersion) { return this.updateAccountState(accountId, expectedVersion, 'revoked'); }
  async setAccountStateWithAudit({ accountId, ownerId, expectedVersion, state, audit, connectionTestId, requirePassedTest = false }) { return this.withTransaction(async (client) => { const { rows: locked } = await client.query('SELECT * FROM provider_accounts WHERE account_id=$1 FOR UPDATE', [accountId]); const current = accountRow(locked[0]); if (!current || current.ownerId !== ownerId || current.version !== String(expectedVersion) || current.status === 'revoked') return undefined; if (requirePassedTest) { const { rows } = await client.query("SELECT EXISTS(SELECT 1 FROM connection_tests WHERE test_id=$1 AND account_id=$2 AND account_version=$3 AND state='succeeded') AS passed", [connectionTestId, accountId, current.version]); if (!rows[0].passed) throw Object.assign(new Error('connection_test_required'), { statusCode: 422 }); } const { rows } = await client.query('UPDATE provider_accounts SET state=$2,version=version+1,updated_at=now() WHERE account_id=$1 RETURNING *', [accountId, state]); const result = accountRow(rows[0]); await this.writeAudit(audit(result), client); return result; }); }
  async deleteAccountWithAudit({ accountId, ownerId, expectedVersion, audit }) { return this.withTransaction(async (client) => { const { rows: locked } = await client.query('SELECT * FROM provider_accounts WHERE account_id=$1 FOR UPDATE', [accountId]); const current = accountRow(locked[0]); if (!current || current.ownerId !== ownerId || current.version !== String(expectedVersion) || current.status === 'revoked') return undefined; const { rows: configs } = await client.query('SELECT provider_config_id FROM provider_configs WHERE provider_account_id=$1 ORDER BY provider_config_id FOR UPDATE', [accountId]); const { rows: refs } = await client.query("SELECT EXISTS(SELECT 1 FROM provider_configs WHERE provider_account_id=$1 AND status<>'revoked' UNION ALL SELECT 1 FROM provider_bindings WHERE account_id=$1 AND state='active' UNION ALL SELECT 1 FROM connection_tests WHERE account_id=$1 AND state IN ('queued','running','cancel_requested') UNION ALL SELECT 1 FROM ai_task_attempts WHERE provider_account_id=$1 AND state IN ('queued','running')) AS used", [accountId]); if (refs[0].used) throw Object.assign(new Error('provider_account_in_use'), { statusCode: 409 }); const { rows } = await client.query("UPDATE provider_accounts SET state='revoked',version=version+1,updated_at=now() WHERE account_id=$1 RETURNING *", [accountId]); const result = accountRow(rows[0]); await client.query("INSERT INTO provider_secret_revoke_intents(intent_id,account_id,secret_ref,state) VALUES($1,$2,$3,'pending') ON CONFLICT(account_id,secret_ref) DO NOTHING", [randomUUID(), accountId, current._secretRef]); await this.writeAudit(audit(result), client); return result; }); }
  async listPendingSecretRevocations(limit = 20) { const { rows } = await this.pool.query("SELECT intent_id,account_id,secret_ref FROM provider_secret_revoke_intents WHERE state='pending' ORDER BY created_at LIMIT $1", [limit]); return rows.map((row) => ({ intentId: row.intent_id, accountId: row.account_id, secretRef: row.secret_ref })); }
  async completeSecretRevocation(intentId) { const { rows } = await this.pool.query("UPDATE provider_secret_revoke_intents SET state='completed',completed_at=now(),attempts=attempts+1 WHERE intent_id=$1 AND state='pending' RETURNING intent_id", [intentId]); return Boolean(rows[0]); }
  async createBinding({ accountId, providerConfigId, policyVersion, bindingId = randomUUID() }, client = this.pool) { const { rows } = await client.query("INSERT INTO provider_bindings (binding_id, account_id, provider_config_id, policy_version, state) VALUES ($1, $2, $3, $4, 'active') ON CONFLICT(account_id,provider_config_id) DO UPDATE SET state='active', policy_version=EXCLUDED.policy_version, version=provider_bindings.version+1 RETURNING *", [bindingId, accountId, providerConfigId, policyVersion ?? 1]); return { bindingId: rows[0].binding_id, accountId: rows[0].account_id, providerConfigId: rows[0].provider_config_id, version: String(rows[0].version), state: rows[0].state }; }
  async createBindingWithAudit(input, audit) { return this.withTransaction(async (client) => { const binding = await this.createBinding(input, client); await this.writeAudit(audit(binding), client); return binding; }); }
  async createConnectionTest(input, client = this.pool) { const { rows } = await client.query("INSERT INTO connection_tests (test_id, request_id, account_id, provider_config_id, account_version, config_version, protocol_version, state) VALUES ($1, $2, $3, $4, $5, $6, $7, 'queued') ON CONFLICT (request_id, account_id, account_version, config_version) DO UPDATE SET request_id=EXCLUDED.request_id RETURNING *", [input.testId ?? randomUUID(), input.requestId, input.accountId, input.providerConfigId ?? null, input.accountVersion, input.configVersion, input.protocolVersion]); return testRow(rows[0]); }
  async createConnectionTestWithAudit(input, audit) { return this.withTransaction(async (client) => { const test = await this.createConnectionTest(input, client); await this.writeAudit(audit(test), client); return test; }); }
  async claimConnectionTest(workerId, leaseMs = 15_000) { const client = await this.pool.connect(); try { await client.query('BEGIN'); const { rows } = await client.query("SELECT test_id FROM connection_tests WHERE (state = 'queued' AND lease_owner IS NULL) OR (state IN ('running','cancel_requested') AND lease_until < now()) ORDER BY created_at FOR UPDATE SKIP LOCKED LIMIT 1"); if (!rows[0]) { await client.query('COMMIT'); return undefined; } const result = await client.query("UPDATE connection_tests SET state = CASE WHEN state='cancel_requested' THEN state ELSE 'running' END, lease_owner = $1, lease_until = now() + ($2::int * interval '1 millisecond'), attempts = attempts + 1 WHERE test_id = $3 RETURNING *", [workerId, leaseMs, rows[0].test_id]); await client.query('COMMIT'); return testRow(result.rows[0]); } catch (error) { await client.query('ROLLBACK'); throw error; } finally { client.release(); } }
  async renewConnectionTestLease(testId, workerId, leaseMs = 15_000) { const { rows } = await this.pool.query("UPDATE connection_tests SET lease_until = now() + ($3::int * interval '1 millisecond') WHERE test_id = $1 AND lease_owner = $2 AND state IN ('running','cancel_requested') RETURNING *", [testId, workerId, leaseMs]); return testRow(rows[0]); }
  async getConnectionTest(testId) { const { rows } = await this.pool.query('SELECT * FROM connection_tests WHERE test_id = $1', [testId]); return testRow(rows[0]); }
  async hasSuccessfulConnectionTest(accountId, accountVersion) { const { rows } = await this.pool.query("SELECT EXISTS(SELECT 1 FROM connection_tests WHERE account_id=$1 AND account_version=$2 AND state='succeeded') AS passed", [accountId, accountVersion]); return rows[0].passed; }
  async getConnectionTestForOwner(testId, ownerId) { const { rows } = await this.pool.query('SELECT t.* FROM connection_tests t JOIN provider_accounts a ON a.account_id=t.account_id WHERE t.test_id=$1 AND a.owner_id=$2', [testId, ownerId]); return testRow(rows[0]); }
  async finishConnectionTest(testId, state, reasonCode, durationMs, workerId) { const ownerClause = workerId ? ' AND lease_owner = $5' : ''; const params = workerId ? [testId, state, reasonCode ?? null, durationMs ?? null, workerId] : [testId, state, reasonCode ?? null, durationMs ?? null]; const { rows } = await this.pool.query(`UPDATE connection_tests SET state = $2, reason_code = $3, duration_ms = $4, finished_at = now(), lease_owner = NULL, lease_until = NULL WHERE test_id = $1 AND (state IN ('queued','running') OR (state='cancel_requested' AND $2='cancelled'))${ownerClause} RETURNING *`, params); return testRow(rows[0]); }
  async finishConnectionTestWithAudit(testId, state, reasonCode, durationMs, workerId, audit) { return this.withTransaction(async (client) => { const ownerClause = workerId ? ' AND lease_owner = $5' : ''; const params = workerId ? [testId, state, reasonCode ?? null, durationMs ?? null, workerId] : [testId, state, reasonCode ?? null, durationMs ?? null]; const { rows } = await client.query(`UPDATE connection_tests SET state = $2, reason_code = $3, duration_ms = $4, finished_at = now(), lease_owner = NULL, lease_until = NULL WHERE test_id = $1 AND (state IN ('queued','running') OR (state='cancel_requested' AND $2='cancelled'))${ownerClause} RETURNING *`, params); const result = testRow(rows[0]); if (result) await this.writeAudit(audit(result), client); return result; }); }
  async cancelConnectionTest(testId) { const { rows } = await this.pool.query("UPDATE connection_tests SET state=CASE WHEN state='queued' THEN 'cancelled' ELSE 'cancel_requested' END, finished_at=CASE WHEN state='queued' THEN now() ELSE NULL END WHERE test_id=$1 AND state IN ('queued','running') RETURNING *", [testId]); return testRow(rows[0]) ?? this.getConnectionTest(testId); }
  async writeAudit(event, client = this.pool) { return this.audit.record(event, client); }
}

export class InMemoryProviderRepository {
  audit = new InMemoryAuditRepository();
  accounts = new Map(); bindings = new Map(); tests = new Map();
  async listAccounts(ownerId) { return [...this.accounts.values()].filter((account) => account.ownerId === ownerId && account.status !== 'revoked'); }
  async createAccount(input) { const account = { accountId: input.accountId ?? randomUUID(), ownerId: input.ownerId, ownerType: 'admin', protocolType: input.protocolType, displayName: input.displayName, scope: input.scope ?? {}, status: input.state ?? 'credential_pending', credentialState: 'configured', defaultForProtocol: Boolean(input.defaultForProtocol), version: '1', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), _secretRef: input.credentialRef }; this.accounts.set(account.accountId, account); return account; }
  async getAccount(id) { return this.accounts.get(id); }
  async hasActiveReferences(id) { return [...this.bindings.values()].some((item) => item.accountId === id && item.state === 'active') || [...this.tests.values()].some((item) => item.accountId === id && ['queued','running','cancel_requested'].includes(item.status)); }
  async updateAccountState(id, expectedVersion, state) { const account = this.accounts.get(id); if (!account || account.version !== String(expectedVersion)) return undefined; account.status = state; account.version = String(Number(account.version) + 1); return account; }
  async revokeAccount(id, version) { return this.updateAccountState(id, version, 'revoked'); }
  secretRevocations = new Map();
  async setAccountStateWithAudit({ accountId, ownerId, expectedVersion, state, audit, connectionTestId, requirePassedTest = false }) { const account = this.accounts.get(accountId); if (!account || account.ownerId !== ownerId || account.version !== String(expectedVersion)) return undefined; const test = this.tests.get(connectionTestId); if (requirePassedTest && (!test || test.accountId !== accountId || test.accountVersion !== account.version || test.status !== 'succeeded')) throw Object.assign(new Error('connection_test_required'), { statusCode: 422 }); await this.writeAudit(audit({ ...account, status: state })); return this.updateAccountState(accountId, expectedVersion, state); }
  async deleteAccountWithAudit({ accountId, ownerId, expectedVersion, audit }) { const account = this.accounts.get(accountId); if (!account || account.ownerId !== ownerId || account.version !== String(expectedVersion)) return undefined; if (await this.hasActiveReferences(accountId)) throw Object.assign(new Error('provider_account_in_use'), { statusCode: 409 }); await this.writeAudit(audit({ ...account, status: 'revoked' })); const result = await this.revokeAccount(accountId, expectedVersion); this.secretRevocations.set(accountId, { intentId: accountId, accountId, secretRef: account._secretRef }); return result; }
  async listPendingSecretRevocations() { return [...this.secretRevocations.values()]; }
  async completeSecretRevocation(intentId) { return this.secretRevocations.delete(intentId); }
  async createBinding(input) { const binding = { bindingId: randomUUID(), ...input, version: '1', state: 'active' }; this.bindings.set(binding.bindingId, binding); return binding; }
  async createConnectionTest(input) { const prior = [...this.tests.values()].find((item) => item.requestId === input.requestId && item.accountId === input.accountId && item.accountVersion === input.accountVersion && item.configVersion === input.configVersion); if (prior) return prior; const test = { testId: randomUUID(), ...input, status: 'queued', createdAt: new Date().toISOString(), attempts: 0, leaseOwner: null, leaseUntil: null }; this.tests.set(test.testId, test); return test; }
  async claimConnectionTest(workerId, leaseMs = 15_000) { const now = Date.now(); const test = [...this.tests.values()].filter((item) => item.status === 'queued' || (['running','cancel_requested'].includes(item.status) && (!item.leaseUntil || item.leaseUntil <= now))).sort((a, b) => a.createdAt.localeCompare(b.createdAt))[0]; if (!test) return undefined; if (test.status !== 'cancel_requested') test.status = 'running'; test.leaseOwner = workerId; test.leaseUntil = now + leaseMs; test.attempts += 1; return test; }
  async renewConnectionTestLease(testId, workerId, leaseMs = 15_000) { const test = this.tests.get(testId); if (!test || !['running','cancel_requested'].includes(test.status) || test.leaseOwner !== workerId) return undefined; test.leaseUntil = Date.now() + leaseMs; return test; }
  async getConnectionTest(id) { return this.tests.get(id); }
  async hasSuccessfulConnectionTest(accountId, accountVersion) { return [...this.tests.values()].some((test) => test.accountId === accountId && test.accountVersion === String(accountVersion) && test.status === 'succeeded'); }
  async getConnectionTestForOwner(id, ownerId) { const test = this.tests.get(id); return test && this.accounts.get(test.accountId)?.ownerId === ownerId ? test : undefined; }
  async finishConnectionTest(id, state, reasonCode, durationMs, workerId) { const test = this.tests.get(id); if (!test || !['queued', 'running', 'cancel_requested'].includes(test.status) || workerId && test.leaseOwner !== workerId) return undefined; if (test.status === 'cancel_requested' && state !== 'cancelled') return undefined; Object.assign(test, { status: state, reasonCode, latencyMs: durationMs, completedAt: new Date().toISOString(), leaseOwner: null, leaseUntil: null }); return test; }
  async cancelConnectionTest(id) { const test = this.tests.get(id); if (!test) return undefined; if (test.status === 'running') test.status = 'cancel_requested'; else if (test.status === 'queued') await this.finishConnectionTest(id, 'cancelled'); return test; }
  async writeAudit(event) { return this.audit.record(event); }
  async createAccountWithAudit(input, audit) { const account = await this.createAccount(input); await this.writeAudit(audit(account)); return account; }
  async createBindingWithAudit(input, audit) { const binding = await this.createBinding(input); await this.writeAudit(audit(binding)); return binding; }
  async createConnectionTestWithAudit(input, audit) { const test = await this.createConnectionTest(input); await this.writeAudit(audit(test)); return test; }
  async finishConnectionTestWithAudit(id, state, reasonCode, durationMs, workerId, audit) { const test = await this.finishConnectionTest(id, state, reasonCode, durationMs, workerId); if (test) await this.writeAudit(audit(test)); return test; }
}
