import test from 'node:test';
import assert from 'node:assert/strict';
import { validateManifest, manifestDigest } from '../../src/apps/manifest-validator.mjs';
import { InMemoryAppRepository } from '../../src/apps/repository.mjs';
import { CatalogService } from '../../src/apps/catalog-service.mjs';
import { AppRuntimeService } from '../../src/apps/runtime-service.mjs';
import { InMemoryPermissionRepository } from '../../src/permissions/repository.mjs';
import { PermissionBroker } from '../../src/permissions/broker.mjs';
import { ActionRegistry } from '../../src/actions/registry.mjs';
import { ActionService } from '../../src/actions/service.mjs';
import { SystemService } from '../../src/system/service.mjs';

const manifest = (overrides = {}) => ({ appId: 'com.example.demo', version: '1.0.0', build: '1', releaseChannel: 'stable', minRuntimeVersion: '1.0.0', entrypoints: { web: 'index.html' }, permissions: ['settings.read'], capabilityAllowlist: ['settings.read'], trustLevel: 'official', uninstallPolicy: 'allowed', backgroundPolicy: 'none', ...overrides });
test('manifest validation and digest', () => { assert.equal(validateManifest(manifest()).valid, true); assert.equal(validateManifest(manifest({ entrypoints: { web: '/tmp/x' } })).valid, false); assert.match(manifestDigest(manifest()), /^sha256:/); });
test('catalog visibility and developer test install', async () => { const repo = new InMemoryAppRepository(); const catalog = new CatalogService({ repository: repo }); await catalog.submit({ manifest: manifest({ trustLevel: 'developer' }), catalogState: 'pending_review' }); assert.equal((await catalog.list()).items.length, 0); const runtime = new AppRuntimeService({ repository: repo }); const installed = await runtime.install({ subjectId: 'u', appId: 'com.example.demo', version: '1.0.0', build: '1', developerTest: true }); assert.equal(installed.state, 'active'); });
test('health failure rolls back and uninstall retains data', async () => { const repo = new InMemoryAppRepository(); const catalog = new CatalogService({ repository: repo }); await catalog.submit({ manifest: manifest(), catalogState: 'official' }); await catalog.submit({ manifest: manifest({ version: '1.0.1', build: '2' }), catalogState: 'official' }); let healthy = true; const runtime = new AppRuntimeService({ repository: repo, healthCheck: async () => healthy }); await runtime.install({ subjectId: 'u', appId: 'com.example.demo', version: '1.0.0', build: '1' }); healthy = false; await assert.rejects(runtime.update({ subjectId: 'u', appId: 'com.example.demo', version: '1.0.1', build: '2' })); const current = await repo.getInstall('u', 'com.example.demo'); assert.equal(current.dataRetained, true); });
test('permission deny precedence and revoke', async () => { const broker = new PermissionBroker({ repository: new InMemoryPermissionRepository() }); await broker.decide({ subjectId: 'u', appId: 'a', capability: 'files.read', decision: 'allow' }); assert.equal(broker.check({ subjectId: 'u', appId: 'a', capability: 'files.read', declared: ['files.read'] }).decision, 'allow'); await broker.decide({ subjectId: 'u', appId: 'a', capability: 'files.read', decision: 'deny' }); assert.equal(broker.check({ subjectId: 'u', appId: 'a', capability: 'files.read', declared: ['files.read'] }).decision, 'deny'); });
test('action plan has no handler side effect and executes once', async () => { const permissions = new PermissionBroker({ repository: new InMemoryPermissionRepository() }); await permissions.decide({ subjectId: 'u', appId: 'a', capability: 'settings.write', decision: 'allow' }); const registry = new ActionRegistry(); const service = new ActionService({ registry, permissions }); let calls = 0; service.register({ actionId: 'settings.open', ownerAppId: 'a', requiredCapability: 'settings.write', riskLevel: 'low' }, async () => { calls += 1; }); const plan = await service.plan({ actionId: 'settings.open', subjectId: 'u', input: {} }); assert.equal(calls, 0); const run = await service.execute({ actionId: 'settings.open', planId: plan.planId, subjectId: 'u', confirmed: true, requestId: 'r' }); await new Promise((resolve) => setImmediate(resolve)); assert.equal(calls, 1); assert.equal(run.handlerCalls, 1); });
test('settings optimistic concurrency and context redaction', async () => { const system = new SystemService(); const first = await system.patch({ baseVersion: '1', patch: { domain: 'network', value: { proxySecretRef: 'secret:1' } } }); assert.equal(first.contextVersion, '2'); await assert.rejects(system.patch({ baseVersion: '1', patch: { domain: 'locale', value: { language: 'zh-CN' } } })); assert.deepEqual(system.context().settings.network, { proxySecretRef: 'secret:1' }); });
